ISSUE #2197 - Fix clickable URL in comments section
3drepo/3drepo.io pull request #2220
Opened 2020-09-25 06:19 UTC by MajaZubko

This fixes #2197

2020-09-25 06:52 UTC, m1chalkubiak commented
@MajaZubko Please fix lint errors

2020-09-25 06:53 UTC, m1chalkubiak requested changes
@MajaZubko Please fix lint errors

2020-09-25 07:19 UTC, m1chalkubiak submitted a review, later dismissed

2020-09-28 13:29 UTC, MajaZubko commented
@carmenfan this fix would be useful for us in other issues. Can you please look at it?

2020-09-28 14:22 UTC, carmenfan requested changes
- [ ] The link should spawn a new tab instead of going to the page directly.

2020-09-28 14:22 UTC, carmenfan commented on frontend/package.json
> +    "markdown-linkify": "^1.0.1",
lock down the version please

We've had plenty of troubles in the past where a later version of the library changed the API and randomly broke deployments 😢

2020-09-29 13:08 UTC, carmenfan approved these changes
Looks fine now!

@MajaZubko In the future please avoid rewriting history and altering a pre-existing commit. Just make a new commit!

It's not too big of a deal with a couple of line changes like this one, but if we are doing a 2nd review it's much faster to just see what you've changed base on what we've reviewed last time, instead of going through all the file changes again to look for a specific change. :)

2020-09-29 13:09 UTC, merged