ISSUE #2185 - Add character counter and abbreviate screenshot url in comments
3drepo/3drepo.io pull request #2234
Opened 2020-10-02 07:02 UTC by MajaZubko

This fixes #2185

2020-10-02 10:43 UTC, m1chalkubiak requested changes

2020-10-02 10:43 UTC, m1chalkubiak commented on frontend/helpers/comments.ts
> +		let referenceType;
```js
const referenceType = type === 'risk' ? 'risk' : 'issues';
```
We don't have any third option and it will be simpler and clearer this way.

2020-10-02 10:43 UTC, m1chalkubiak commented on frontend/helpers/comments.ts
> +		uniqViewpointReferences.forEach(({0: viewpointReference}) => {
`{ 0: viewpointReference }`
There should be additional spaces, it just our syntax convention, not an error.

2020-10-02 10:43 UTC, m1chalkubiak commented on frontend/helpers/comments.ts
> +		const teamspace = details.account;
Destructuring with variable renaming is something that will be useful to you many times

```js
const { account: teamspace, model: projectId, _id: issueId } = details;
```

2020-10-05 07:15 UTC, m1chalkubiak submitted a review, later dismissed

2020-10-05 10:38 UTC, carmenfan commented
/azp run

2020-10-05 16:52 UTC, har00n-haider commented
Implementation looks good. I can see the word count tick up for input characters, and the short links work really well.

#### Side notes

As a side note would it be better to block the user from posting the comment if the char limit is exceeded? Especially seeing as the user cannot edit comments that have already sent. 

Pasting the generated short link does not work across tickets. Not sure if this is ever likely to happen:
![image](https://user-images.githubusercontent.com/72197495/95108611-67bb8080-0733-11eb-9927-0bb1c22627b9.png)

2020-10-08 10:41 UTC, m1chalkubiak commented
Hi @har00n-haider 

> As a side note would it be better to block the user from posting the comment if the char limit is exceeded? Especially seeing as the user cannot edit comments that have already sent.

I think this was a small issue with presenting error, We are blocking sending comments above 220 char. Previously, the information about the number of characters turned red also when it was equal to 220. I corrected it.
 
> Pasting the generated short link does not work across tickets. Not sure if this is ever likely to happen:

Currently, our shortcode contains only the last part, i.e. `viewpointId`, and code assume that the remaining information matches the place where we are trying to call it. In order to be able to use this shortcode between tickets, the shortcode would also need to contain a `ticketId`, if we wanted to use it between different risk / issue ticket types, we would also have to pass this information, etc.
 Which inevitably leads us to the point where the shortcode is similar in length to the real link, which no longer makes sense. So the question is what do we want to allow? @carmenfan 

```js
${teamspace}/${projectId}/${referenceType}/${ticketId}/viewpoints/${viewpointId}/screenshot.png
```

2020-10-08 10:48 UTC, carmenfan commented
@m1chalkubiak Nah I think it'll be overkill. Considering we currently don't allow users to quote a picture from a different issue/risk via the UI, the user will have to be some what markdown competent to do it, if they really want to do it, they can just share the full url of the screenshot.

2020-10-08 10:49 UTC, carmenfan commented
@m1chalkubiak  i'm assuming you can still display a picture with the right markdown syntax and a valid url to an image?

2020-10-08 12:15 UTC, m1chalkubiak commented
> @m1chalkubiak i'm assuming you can still display a picture with the right markdown syntax and a valid url to an image?

Of course, we did not change any of native markdown behavior.

2020-10-09 10:42 UTC, carmenfan requested changes
Looks good in general, just a couple of minor points:

- [ ] The word count is really really faint in colour, can we darken it? (maybe the same font colour as the comments (not the current comment (black) but existing (darker grey)?

![image](https://user-images.githubusercontent.com/11945337/95573877-07bf2580-0a24-11eb-99ae-bd30ab219833.png)

- [ ] Can we move it to the right? 
![image](https://user-images.githubusercontent.com/11945337/95574079-5076de80-0a24-11eb-98e7-297684fa352d.png)

2020-10-16 09:35 UTC, carmenfan approved these changes

2020-10-16 09:35 UTC, merged