ISSUE 2372 - Remove Mongoose from Ref
3drepo/3drepo.io pull request #2376
Opened 2021-01-05 16:35 UTC by Charence

This fixes #2372

2021-01-06 17:48 UTC, carmenfan requested changes

2021-01-06 17:48 UTC, carmenfan commented on backend/models/helper/model.js
> +			return findRef(account, model, {
This is very high coupling. This should be calling getRefNodes instead. ids to pass in is `history.current`. From what I can tell it's doing the same thing

2021-01-06 17:48 UTC, carmenfan commented on backend/models/ref.js
> +Ref.findRef = async function(account, model, query, projection) {
As mentioned in the previous comment, this should be removed

2021-01-06 17:48 UTC, carmenfan commented on backend/models/meta.js
> +		const refs = await findRef(account, model, {type: "ref"});
A lot of these queries are not checking current IDs, considering we're passing in branch/revId it's probably worth considering if we actually have a bug here.... 😆 If it's a federation with revisions where we removed/added some sub models, are we still searching through some sub models that are no longer a submodel?

2021-01-07 19:03 UTC, carmenfan requested changes

2021-01-07 19:03 UTC, carmenfan commented on backend/models/meta.js
> +		const subModelRefs = await getRefNodes(account, model);
I think we want to get impose history.current here as well.

I don't think we're interested in getting metadataFields form some submodels that are no longer a submodel

2021-01-08 14:37 UTC, Charence commented
@carmenfan If #2377 for Scene can get merged in, getRefNodes can make use of the function in Scene which takes in branch/revision?

2021-01-11 11:30 UTC, carmenfan commented
> @carmenfan If #2377 for Scene can get merged in, getRefNodes can make use of the function in Scene which takes in branch/revision?

@Charence  merged now

2021-01-12 10:18 UTC, carmenfan approved these changes

2021-01-12 10:18 UTC, merged