ISSUE 2345 - Remove Mongoose from Project
3drepo/3drepo.io pull request #2419
Opened 2021-01-22 14:16 UTC by Charence

This fixes #2345

2021-01-25 12:24 UTC, carmenfan requested changes
@Charence  can you address this here: https://github.com/3drepo/3drepo.io/pull/2407#discussion_r562561582

2021-01-25 12:24 UTC, carmenfan commented on backend/models/project.js
> +	Project.findProjectAndPopulateUsers = async function(teamspace, projectName) {
This needs better naming. The naming is really misleading.

After looking around, this is only used by the endpoint, which looks like it's to show the permissions page on the frontend. So it needs to know all the users within teamspace and whether they have any permissions.

PopulateUsers suggests we're doing a write. This is more like `getAllUsersProjectPermissions`  or something (i'm bad at naming, but hopefully you see the direction i'm trying to go towards)

2021-01-25 12:24 UTC, carmenfan commented on backend/models/project.js
> +		foundProjects.forEach((project) => {
there should be a clean function to do this? so it's inline with every other file?

2021-01-25 12:24 UTC, carmenfan commented on backend/models/project.js
> +		const project = await Project.findOneProject(teamspace, {name: projectName});
can do these 2 queries simultaneously?

2021-01-25 12:24 UTC, carmenfan commented on backend/models/project.js
> +		const project = await Project.findOneProject(teamspace, {name: model});
add projection `{permissions:1 }` since we don't use anything else

2021-01-25 12:24 UTC, carmenfan commented on backend/models/project.js
> +		const projectObj = await Project.findOneProject(teamspace, {name: project});
just do a update?

2021-01-25 12:24 UTC, carmenfan commented on backend/models/project.js
> +		const projectObj = await Project.findOneProject(teamspace, {name: project});
do we check if the user is in the teamspace? (do we have test for this?)

2021-01-25 12:24 UTC, carmenfan commented on backend/models/project.js
> +	Project.setUserAsProjectAdminById = async function(teamspace, project, user) {
I think we should refactor this and 279 to call a private function `setUsersAsProjectByQuery` which both calls with the query, as that's the only difference between them

2021-01-25 12:24 UTC, carmenfan commented on backend/models/user.js
> +	return listProjects(account.account, query).then(projects => {
Looking at the way _addProjects is called, `models` is always undefined. so we're just getting all the projects all the time.

2021-01-25 12:24 UTC, carmenfan commented on backend/models/user.js
> +			// FIXME
remove? (there's more of these in the file)

2021-01-25 12:24 UTC, carmenfan commented on backend/models/user.js
> +				return listProjects(user.user, query, projection).then(projects => {
Move this logic into project. There should be a function in project to get all projects the user has access to. this is very high coupling 😆

2021-01-25 12:24 UTC, carmenfan commented on backend/models/user.js
> +	return listProjects(this.user, { "permissions.user": username }).then(projects => {
there should be a function in project to get projects the user has access to.

2021-02-04 13:10 UTC, Charence commented on backend/models/project.js
> +		await checkInvalidName(name);
It seems like `checkDupName` still needs await, so I've kept that there

2021-02-08 17:30 UTC, merged