ISSUE #2449 - Turn off Cross-Site Requests
3drepo/3drepo.io pull request #2477
Opened 2021-02-17 17:17 UTC by Charence

This fixes #2449

NOTE: DO NOT MERGE! Just testing for now

2021-02-17 17:17 UTC, Charence commented
/azp run

2021-02-17 17:17 UTC, carmenfan commented
@Charence  you can mark this as draft to indicate it's not ready :
![image](https://user-images.githubusercontent.com/11945337/108241740-10e3a000-7144-11eb-961b-9ac658142009.png)

2021-02-17 19:26 UTC, Charence commented
/azp run

2021-02-17 22:57 UTC, Charence commented
/azp run

2021-02-18 09:13 UTC, Charence commented
/azp run

2021-02-18 10:02 UTC, Charence commented
/azp run

2021-02-18 10:25 UTC, Charence commented
/azp run

2021-02-18 10:47 UTC, Charence commented
/azp run

2021-02-18 11:17 UTC, Charence commented
/azp run

2021-02-18 11:33 UTC, Charence commented
/azp run

2021-02-18 11:46 UTC, Charence commented
Note: "Strict" doesn't work with iframe; user is unable to proceed from login page.

2021-02-18 11:48 UTC, Charence commented
/azp run

2021-02-18 12:03 UTC, Charence commented
Note: "Lax" also has same behaviour as "Strict" for iframe.

2021-02-18 16:18 UTC, Charence commented
/azp run

2021-02-18 16:46 UTC, Charence commented
/azp run

2021-02-18 17:01 UTC, Charence commented
/azp run

2021-02-18 17:56 UTC, Charence commented
/azp run

2021-02-18 18:39 UTC, Charence commented
/azp run

2021-02-19 09:27 UTC, Charence commented
/azp run

2021-02-19 10:03 UTC, Charence commented
/azp run

2021-02-19 14:39 UTC, Charence commented
/azp run

2021-02-19 15:09 UTC, Charence commented
/azp run

2021-02-19 15:46 UTC, Charence commented
/azp run

2021-02-19 16:12 UTC, Charence commented
/azp run

2021-02-19 19:40 UTC, Charence commented
/azp run

2021-02-25 11:16 UTC, carmenfan requested changes
Can we also add some tests? I think you can set headers on the agent

https://stackoverflow.com/questions/23725643/with-supertest-can-i-create-an-alternative-request-with-some-headers-set-by-def

2021-02-25 11:16 UTC, carmenfan commented on backend/middlewares/sessionManager.js
> +		req[C.REQ_REPO].logger.logError(`express-session internal error: referer (${req.headers.referer}) and cookie (${config.cookie_domain}) domain mismatch`);
This isn't an error, i don't think we should be logging this way.

2021-02-25 11:16 UTC, carmenfan commented on backend/middlewares/sessionManager.js
> +		(!req.headers.referer && !config.cookie.skipMissingReferer)) {
We can remove skipMissingReferer.

We need to always accept missing referrer or plugins won't work

2021-02-25 11:16 UTC, carmenfan commented on backend/middlewares/sessionManager.js
> +		return;
If we're not going next(), we need to respond to the request here. at the moment if it enters this condition the request never returns.

2021-02-26 14:54 UTC, carmenfan commented
/azp run

2021-03-04 16:48 UTC, Charence commented
@carmenfan Suggested changes for storing referrer applied

2021-03-12 10:47 UTC, carmenfan requested changes

2021-03-12 10:47 UTC, carmenfan commented on backend/middlewares/sessionManager.js
> +		if (req.headers.referer && req.session.user && req.session.user.referer && !req.headers.referer.match(req.session.user.referer)) {
should this check just go here? https://github.com/3drepo/3drepo.io/blob/master/backend/middlewares/checkPermissions.js#L74

2021-03-12 10:47 UTC, carmenfan commented on backend/services/session.js
> +					const refererDomain = req.headers.referer.match(/^(\w)*:\/\/.*?\//);
Not immediately clear why we have to do this?

Probably needs a comment

2021-03-18 10:51 UTC, carmenfan approved these changes

2021-03-18 10:51 UTC, merged