ISSUE #2549 - Fix kanban board styling
3drepo/3drepo.io pull request #2569
Opened 2021-04-21 07:57 UTC by abyszewski

This fixes #2549

#### Description
Fix board height when filters, search are opened

2021-04-21 08:07 UTC, m1chalkubiak requested changes

2021-04-21 08:07 UTC, m1chalkubiak commented on .idea/.gitignore
> +# Default ignored files
?

2021-04-21 08:07 UTC, m1chalkubiak commented on frontend/routes/board/board.component.tsx
> +	FILTERS_COMPONENT_HEIGHT,
Please fix formatting

2021-04-21 08:07 UTC, m1chalkubiak commented on frontend/routes/board/board.styles.ts
> +	height: ${({offset}) => offset ? `calc(100% - ${50 + offset}px)` : 'calc(100% - 50px)'};
Please move those additional styles to separate variables

2021-04-21 08:07 UTC, m1chalkubiak commented on frontend/routes/components/filterPanel/filterPanel.component.tsx
> +	setFiltersOpen: Dispatch<SetStateAction<boolean>>;
Did You check all places were this component is used ?

2021-04-21 08:07 UTC, m1chalkubiak commented on frontend/modules/board/board.constants.ts
> +export const FILTERS_COMPONENT_HEIGHT = 50;
If fix need knowing of element height, we should depend on real values

2021-04-21 14:03 UTC, carmenfan commented
![image](https://user-images.githubusercontent.com/11945337/115566957-a5888c80-a2b2-11eb-8d5b-5d610bea2212.png)


@abyszewski  @m1chalkubiak  can we make sure we're not doing force pushes? It's probably fine for now since no one else is working on this branch at the moment, but It's pretty bad practice 😆

2021-04-21 14:24 UTC, m1chalkubiak commented
Sure, @carmenfan, it's Antek's first task in this project and We still agree on the rules of work here. Of course, also I suggested internally to Antek to no making force pushes.

2021-04-23 12:22 UTC, m1chalkubiak commented
/azp run

2021-04-23 13:49 UTC, carmenfan commented
/azp run

2021-04-23 14:08 UTC, carmenfan commented
@keifgwinn it's struggling to build https://github.com/3drepo/3drepo.io/runs/2420264425

Seems to be related to the change you made yday. Any ideas why/what needs to be done??

2021-04-23 14:48 UTC, keifgwinn commented
/azp run

2021-04-23 14:53 UTC, keifgwinn commented
/azp run

2021-04-23 14:55 UTC, keifgwinn commented
/azp run

2021-04-23 14:56 UTC, keifgwinn commented
/azp run

2021-04-23 14:57 UTC, keifgwinn commented
/azp run

2021-04-23 15:38 UTC, keifgwinn commented
/azp run

2021-04-27 08:50 UTC, BDavydov commented
@mosment3DRepo Looks good to me, does what expected.
Sometimes you get an odd jitter or two, scrolling Up & Down quickly, but it's barely noticeable.

2021-04-30 12:01 UTC, sanmont3drepo commented
I think the approach ussing just css in this branch is simpler:
https://github.com/3drepo/3drepo.io/commits/ISSUE_2549b

2021-04-30 13:58 UTC, m1chalkubiak commented
> I think the approach using only css in this branch is simpler:
> https://github.com/3drepo/3drepo.io/commits/ISSUE_2549b

Hi @sanmont3drepo I can't argue with fact that it is simpler, but it changes diametrically what and how is scrollable on board.
I'm not saying it's not working or looking bad but it's just different from the current implementation.

Can you please build it independently for your team internally and compare it with the current version on staging?

2021-04-30 14:08 UTC, carmenfan commented
@sanmont3drepo  can you make PR for that branch and trigger a build?

2021-04-30 14:45 UTC, carmenfan commented
@m1chalkubiak 

> Can you please build it independently for your team internally and compare it with the current version on staging?

Are there situations where you suspect it may not work as before? whilst we can try to thoroughly test it , it would be good to make sure we cover any suspected case that are likely to break

2021-04-30 14:51 UTC, sanmont3drepo commented
> > I think the approach using only css in this branch is simpler:
> > https://github.com/3drepo/3drepo.io/commits/ISSUE_2549b
> 
> Hi @sanmont3drepo I can't argue with fact that it is simpler, but it changes diametrically what and how is scrollable on board.
> I'm not saying it's not working or looking bad but it's just different from the current implementation.
> 
> Can you please build it independently for your team internally and compare it with the current version on staging?

https://github.com/3drepo/3drepo.io/pull/2592

2021-05-05 12:29 UTC, m1chalkubiak commented
> @m1chalkubiak
> 
> > Can you please build it independently for your team internally and compare it with the current version on staging?
> 
> Are there situations where you suspect it may not work as before? whilst we can try to thoroughly test it , it would be good to make sure we cover any suspected case that are likely to break (i.e. know what we're testing!)

@carmenfan 
I'm attaching screen motion captures, as this probably be the best way to compare those two solutions.

The current way the scroll works inside the kanban board
![CPT2105051334-995x508](https://user-images.githubusercontent.com/24941866/117140271-81967200-adad-11eb-8a9d-ffb5a1c99648.gif)

The way the scroll works with the changes proposed by Santiago:
![CPT2105051415-995x508](https://user-images.githubusercontent.com/24941866/117140415-aee32000-adad-11eb-9169-c0ddaa0bb8c8.gif)

I will repeat it again to make it clear, I am not saying that one solution is good and the other is bad. They are just different, it is up to you to decide which way this board works for you.
Of course, it shows the extreme situation on a low height monitor and with a large number of selected filters only to illustrate what the difference is.

2021-05-05 13:48 UTC, sanmont3drepo commented
> > @m1chalkubiak
> > > Can you please build it independently for your team internally and compare it with the current version on staging?
> > 
> > 
> > Are there situations where you suspect it may not work as before? whilst we can try to thoroughly test it , it would be good to make sure we cover any suspected case that are likely to break (i.e. know what we're testing!)
> 
> @carmenfan
> I'm attaching screen motion captures, as this probably be the best way to compare those two solutions.
> 
> The current way the scroll works inside the kanban board
> ![CPT2105051334-995x508](https://user-images.githubusercontent.com/24941866/117140271-81967200-adad-11eb-8a9d-ffb5a1c99648.gif)
> 
> The way the scroll works with the changes proposed by Santiago:
> ![CPT2105051415-995x508](https://user-images.githubusercontent.com/24941866/117140415-aee32000-adad-11eb-9169-c0ddaa0bb8c8.gif)
> 
> I will repeat it again to make it clear, I am not saying that one solution is good and the other is bad. They are just different, it is up to you to decide which way this board works for you.
> Of course, it shows the extreme situation on a low height monitor and with a large number of selected filters only to illustrate what the difference is.

Hi Michal. I think that you compared 2549b (or 2549) to staging unwillingly. I just copied the behaviour of what you guys did but in css.
This is the same test in 2549
![branch2549](https://user-images.githubusercontent.com/42032433/117151396-f15a2c00-adb0-11eb-8c69-0e83b12f9b70.gif)

2021-05-05 14:16 UTC, m1chalkubiak commented
> 
> Hi Michal. I think that you compared 2549b (or 2549) to staging unwillingly. I just copied the behaviour of what you guys did but in css.
> This is the same test with your code from branch ISSUE_2549
> ![branch2549](https://user-images.githubusercontent.com/42032433/117151396-f15a2c00-adb0-11eb-8c69-0e83b12f9b70.gif)

Ok, I see it now, apologize Santiago for this confusion, there were some missing commits on my local that I didn't pull. Now I see both solutions change this behavior in the same way. I was referring to commit 80ea6aa which was working better (the same way like on staging). 

I think the main question is whether this change is ok for all of You, if so then we should do it according to Your suggestion.

2021-05-07 15:21 UTC, carmenfan commented
closing in favour of #2592

2021-05-07 15:21 UTC, closed without merging