ISSUE #2416 - Update current revision if changed by revision dialog
3drepo/3drepo.io pull request #2613
Opened 2021-05-17 14:28 UTC by m1chalkubiak

This fixes #2416

2021-05-19 16:26 UTC, sanmont3drepo commented
There is still a problem when you navigate back and forth after switching revisions. You can see that the revision changes in the switch button and the loading of the model but the compare card is not getting update.

![versioncompareproblems](https://user-images.githubusercontent.com/42032433/118847734-f7c6c880-b8c5-11eb-8fda-2e8c39af6297.gif)

2021-05-19 16:27 UTC, sanmont3drepo requested changes
There is still a problem when you navigate back and forth after switching revisions. You can see that the revision changes in the switch button and the loading of the model but the compare card is not getting update.

![versioncompareproblems](https://user-images.githubusercontent.com/42032433/118847734-f7c6c880-b8c5-11eb-8fda-2e8c39af6297.gif)

2021-05-25 14:42 UTC, carmenfan commented
@sanmont3drepo  can you take another look?

2021-05-26 08:34 UTC, sanmont3drepo approved these changes

2021-05-26 08:34 UTC, merged