ISSUE #2639 - Updated node version to 14.0.0
3drepo/3drepo.io pull request #2640
Opened 2021-06-07 16:47 UTC by sanmont3drepo

This fixes #2639 

#### Description
- Updated incompatibles packages for 14.0.0
- Min changes in logger

2021-06-08 08:55 UTC, keifgwinn commented
Could we use 14.17.0 instead?

2021-06-08 09:12 UTC, carmenfan commented
> Could we use 14.17.0 instead? There's lots of security fixes in since 14.0 https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V14.md#14.17.0

package.json doesn't specify, meaning it should let you run as long as major version is 14.

![image](https://user-images.githubusercontent.com/11945337/121157908-dc563a00-c841-11eb-8082-90570723375e.png)

2021-06-08 09:34 UTC, keifgwinn commented
> package.json doesn't specify, meaning it should let you run as long as major version is 14.

We are specifying 14.0.0 in travis however for tests, so should bump that up to at least current release on 14.

2021-06-23 10:56 UTC, carmenfan requested changes

2021-06-23 10:56 UTC, carmenfan commented on .travis.yml
> +        - "14.0.0"
should use LTS version

2021-06-23 10:56 UTC, carmenfan commented on .travis.yml
> +        - "14.0.0"
same here

2021-06-23 10:56 UTC, carmenfan commented on backend/logger.js
> +	if (this.req && this.req.method) {
merge the 2 ifs (kind of) so we only test this.req once
```suggestion
	if (this.req) {
	    if (this.req.method) {
	        //...
	    }
	
	}
```

2021-07-01 10:12 UTC, keifgwinn commented
/azp run

2021-07-01 16:05 UTC, carmenfan approved these changes

2021-07-01 16:05 UTC, merged