ISSUE #2584 - Add GTM
3drepo/3drepo.io pull request #2641
Opened 2021-06-08 10:42 UTC by m1chalkubiak

This fixes #2584

2021-06-08 11:42 UTC, m1chalkubiak commented
/azp run

2021-06-08 12:47 UTC, keifgwinn commented
/azp run

2021-06-08 14:08 UTC, keifgwinn commented
I've made the tweaks required to deploy it on https://issue-2584.dev.3drepo.io/dashboard/teamspaces but I don't know if it's working or not.

2021-06-08 15:00 UTC, m1chalkubiak commented
@keifgwinn I see code build with the newest changes, but don't see GTM added, are You sure gtmId is added on the server config for this branch ?

2021-06-08 15:04 UTC, keifgwinn commented
root@issue-2584-98c6dd444-cjh7w:/home/node/3drepo.io/config/chart# printenv | grep GTM
APP_WEB_GTM_TRACK_ID=GTM-5H6W9JP
root@issue-2584-98c6dd444-cjh7w:/home/node/3drepo.io/config/chart# more config.js
<trimmed>
        ga: {
                trackId: process.env.APP_WEB_GA_TRACK_ID,
                refererTrackId: process.env.APP_WEB_GA_REFERER_TRACK_ID,
                refererDomain: process.env.APP_WEB_GA_REFERER_DOMAIN
        },
        gtm: {
                gtmId: process.env.APP_WEB_GTM_TRACK_ID, // "GTM-XXXXXX",
        },
 </trimmed>

2021-06-09 10:22 UTC, carmenfan requested changes

2021-06-09 10:22 UTC, carmenfan commented on frontend/services/analytics.ts
> +		if (!development) {
this should just be else of the previous if condition?

2021-06-09 10:25 UTC, carmenfan commented on frontend/services/clientConfig.ts
>  	public ga;
remove if we no longer use ga?

2021-06-09 12:22 UTC, carmenfan commented
/azp run

2021-06-09 13:35 UTC, m1chalkubiak commented
/azp run

2021-06-09 14:19 UTC, m1chalkubiak commented
It looks like it finally started working properly. @keifgwinn thanks for the help.

@carmenfan regarding the removal of `liveChatLicense` it looks like there is a component (`ReactLiveChat`) on FE that tries to use it. Perhaps this is something we should be looking at.

2021-06-09 14:20 UTC, m1chalkubiak commented
<img width="525" alt="Zrzut ekranu 2021-06-9 o 16 13 03" src="https://user-images.githubusercontent.com/24941866/121372478-9af78480-c93e-11eb-91d1-3186c00221dc.png">

2021-06-09 14:21 UTC, carmenfan commented
> It looks like it finally started working properly. @keifgwinn thanks for the help.
> 
> @carmenfan regarding the removal of `liveChatLicense` it looks like there is a component (`ReactLiveChat`) on FE that tries to use it. Perhaps this is something we should be looking at.



Can we get rid of the component? We haven't been using liveChat for the past 6 months now 😆  we moved over to intercom.

2021-06-09 17:01 UTC, carmenfan approved these changes

2021-06-09 17:01 UTC, carmenfan commented
Ben verified that the tag is working.

2021-06-09 17:01 UTC, merged