Issue 2754 - Favourites endpoint
3drepo/3drepo.io pull request #2772
Opened 2021-09-06 12:10 UTC by ChristosTsiotsias

This fixes #2754 

#### Description
Favourites endpoints implemented along with the tests and documentation

#### Test cases
- One or more containers should be added to favourites list
- One or more federations should be added to favourites list
- One or more containers should be removed from favourites list
- One or more federations should be removed from favourites list
- Only users with adequate permissions on the models should be able to change the favourites list

2021-09-13 10:42 UTC, carmenfan requested changes

2021-09-13 10:42 UTC, carmenfan commented on backend/src/v5/routes/teamspaces/projects/containers/containers.js
> +     *                 type: array
![image](https://user-images.githubusercontent.com/11945337/133067839-6d741ae0-6f48-426c-938e-b580cabf9476.png)

schema isn't complete here. you should define what the members of array should be (i.e. strings)

![image](https://user-images.githubusercontent.com/11945337/133067866-c084f10b-68cf-4212-9fb0-9ea6ee443739.png)

Also define an example so the doc reader knows what to put in

2021-09-13 10:42 UTC, carmenfan commented on backend/src/v5/routes/teamspaces/projects/containers/containers.js
> +	 *         content:
remove content, we don't need to send a response body if there's nothing to send.

2021-09-13 10:42 UTC, carmenfan commented on backend/src/v5/routes/teamspaces/projects/containers/containers.js
> +	 * /teamspaces/{teamspace}/projects/{project}/containers/favourites:
similar comments here

2021-09-13 10:42 UTC, carmenfan commented on backend/src/v5/routes/teamspaces/projects/federations/federations.js
> +
similar comments here

2021-09-13 10:42 UTC, carmenfan commented on backend/tests/v5/e2e/routes/teamspaces/projects/containers/containers.test.js
> +	testAppendFavourites();
missing remove favourites  tests?

2021-09-13 10:42 UTC, carmenfan commented on backend/tests/v5/unit/middleware/permissions/teamspaces.test.js
> +/**
again merge conflict error - this file should no longer exist

2021-09-13 10:42 UTC, carmenfan commented on backend/tests/v5/unit/models/users.test.js
> +			const newFavourtiesData = favouritesData;
this test is meaningless - you are literally testing if the same object equals to the same object.

The only output you need to test is that it doesn't fail. so you don't need these 3 lines

2021-09-13 10:42 UTC, carmenfan commented on backend/tests/v5/unit/models/users.test.js
> +			const newFavourtiesData = favouritesData;
same for the next 2 tests

2021-09-13 10:42 UTC, carmenfan commented on backend/tests/v5/unit/models/users.test.js
> +			expect(favouritesData).toEqual(newFavourtiesData);
missing tests:
1. starredModels is undefined (this should append as normal and don't throw an error)
2. user doesn't exist (this should throw error)

2021-09-13 10:42 UTC, carmenfan commented on backend/tests/v5/unit/models/users.test.js
> +		});
missing tests:
1. user doesn't exist
2. teamspace doesn't have an entry
3. starredModels is undefined

2021-09-13 10:42 UTC, carmenfan commented on backend/tests/v5/unit/processors/teamspaces/projects/containers/containers.test.js
> +let user1Favourites = [1];
use a different dataset if this needs to change, so you don't contaminate across tests

2021-09-13 10:42 UTC, carmenfan commented on backend/tests/v5/unit/processors/teamspaces/projects/containers/containers.test.js
> +			expect(user1Favourites).toEqual([1]);
again you're not really testing anything within the codebase, you're essentially testing the mockImplementation you defined in this file.

test these round trip logic in the e2e tests, where you're dealing with real data. The whole point of unit tests are to test that the precondition and postcondition matches.

so in this case, appendFavourites should just work if you put in valid data, so the test you should be testing is:

1. favourites should update fine if the user has access to all the models
2. should throw an error if any if the models you cannot add to to the favourites
3. deal with edge cases - what if the list is empty?
4. what if the functions this function call throws an error -> do we deal with them appropriately?

2021-09-13 10:42 UTC, carmenfan commented on backend/tests/v5/unit/processors/teamspaces/projects/containers/containers.test.js
> +		test('user favourites should stay the same if one or more containers are not already in', async () => {
similar sentiment here

2021-09-13 10:42 UTC, carmenfan commented on backend/tests/v5/unit/processors/teamspaces/projects/federations/federations.test.js
> +/**
double license header here

2021-09-13 10:42 UTC, carmenfan commented on backend/tests/v5/unit/processors/teamspaces/projects/federations/federations.test.js
> +/**
again, similar comments to the containers tests

2021-09-13 10:42 UTC, carmenfan commented on backend/tests/v5/e2e/routes/teamspaces/projects/containers/containers.test.js
> +			const res = await agent.get(route).expect(templates.notLoggedIn.status);
you're not testing your route?

this is a `HTTP get`, not a `HTTP patch` operation

2021-09-15 10:45 UTC, ChristosTsiotsias commented on backend/src/v5/routes/teamspaces/projects/containers/containers.js
> +		respond(req, res, templates.ok, { favourites });
For some reason if I don't pass a body to the respond method I never get a response in postman, so it seems that body has to be at least an empty object. I can either pass { } or have the param to have a default value of { }.

2021-09-15 10:57 UTC, carmenfan commented on backend/src/v5/routes/teamspaces/projects/containers/containers.js
> +		respond(req, res, templates.ok, { favourites });
you mean it hangs or it returns with 200 just no body?

2021-09-15 11:38 UTC, carmenfan commented on backend/src/v5/routes/teamspaces/projects/containers/containers.js
> +		respond(req, res, templates.ok, { favourites });
this probably points to a bug in responder, i'll take a look.

2021-09-15 11:45 UTC, carmenfan commented on backend/src/v5/routes/teamspaces/projects/containers/containers.js
> +		respond(req, res, templates.ok, { favourites });
@ChristosTsiotsias  just commited a fix, does it work?

2021-09-15 12:33 UTC, ChristosTsiotsias commented on backend/src/v5/routes/teamspaces/projects/containers/containers.js
> +		respond(req, res, templates.ok, { favourites });
yes seems to work now !

2021-09-15 13:38 UTC, ChristosTsiotsias commented on backend/src/v5/processors/teamspaces/projects/containers/containers.js
> +	const containerIDs = accessibleContainers.map((a) => a._id);
so for example something like that ?

```
{
    1: "0b680c90-dd07-11eb-92d6-8fe463212623",
    2: " "0b6a5680-dd07-11eb-92d6-8fe4632126231"
}
```

2021-09-15 13:52 UTC, carmenfan commented on backend/src/v5/processors/teamspaces/projects/containers/containers.js
> +	const containerIDs = accessibleContainers.map((a) => a._id);
@ChristosTsiotsias  you probably want the id to be the key? more like
````js
{"0b680c90-dd07-11eb-92d6-8fe463212623": true, //... }
````

So at line 75 you just need to do `objectName[i]` to know if it exists

2021-09-15 22:30 UTC, Charence commented on .vs/3drepo.io/config/applicationhost.config
> +<?xml version="1.0" encoding="UTF-8"?>
This looks like your Visual Studio config file?

2021-09-17 13:46 UTC, carmenfan submitted a review, later dismissed

2021-09-17 16:12 UTC, carmenfan approved these changes

2021-09-17 16:12 UTC, merged