ISSUE 2708 - Revamping - Container revision details
3drepo/3drepo.io pull request #2840
Opened 2021-10-21 13:56 UTC by m1chalkubiak

This fixes #2708

2021-10-21 14:02 UTC, carmenfan commented
/azp run

2021-11-02 14:57 UTC, m1chalkubiak commented
@sanmont3drepo I moved the information about the revisions to a separate redux store, this has simplified the logic. Please check if you see anything else that You think would be worth changing.

2021-11-02 15:00 UTC, m1chalkubiak commented
@george-hadfield Can you direct me where I can find guidelines or designs for how you would like to views should behave on smaller resolutions?

2021-11-02 16:42 UTC, george-hadfield commented
> @george-hadfield Can you direct me where I can find guidelines or designs for how you would like to views should behave on smaller resolutions?

This will be address early next week when I return from holiday - but possibly before if I have time.

2021-11-03 17:08 UTC, sanmont3drepo requested changes

2021-11-04 10:18 UTC, m1chalkubiak commented on frontend/test/revisions/revisions.redux.spec.ts
> +import { revisionsMockFactory } from '@/v5/store/revisions/revisions.fixtures';
sure, done.

2021-11-08 10:35 UTC, m1chalkubiak commented
/azp run

2021-11-08 16:30 UTC, george-hadfield approved these changes
Everything is fine from my perspective apart from the responsive at smaller screen sizes which I will be providing tomorrow.

2021-11-08 17:45 UTC, merged