Issue 2770 - v5 endpoint to upload a new revision to container
3drepo/3drepo.io pull request #2842
Opened 2021-10-22 17:06 UTC by carmenfan

This fixes #2770

#### Description
- created new v5 events: `MODEL_IMPORT_UPDATE`, `MODEL_IMPORT_FINISHED`
  - hook v4 `chatEvent` to listen into these new v5 chat events
- created an `eventListener` which listens to `QUEUE_TASK_UPDATE` and `QUEUE_TASK_COMPLETE` and trigger actions appropriately
- v4 backend no longer listens to callback queue - this is done by v5.
- endpoint, middleware checks and processor functions to upload a new revision
- logic to calculate quota
- v5 queue service

#### Test cases
- The user should be able to upload a new revision
- appropriate error messages should be shown if it failed

2021-11-01 17:24 UTC, sanmont3drepo requested changes

2021-11-01 17:27 UTC, carmenfan commented on backend/src/v4/models/chatEvent.js
> +			notes.map((note) => upsertedNotification(null, note));
I copied this from some other place in v4... which was a map and I didn't give it a second thought. 😆 

but yes, agree it can be a foreach

2021-11-01 17:30 UTC, carmenfan commented on backend/src/v5/services/eventsListener/eventsListener.js
> +/**
yes, components are designed to be feature categorised. So in the future the thought is that we'd have things like `projectEventListener`, `issuesEventListener` etc

This is essentially like an index/manager file where it initialise everything when prompted. if you like.

2021-11-01 17:33 UTC, carmenfan commented on backend/src/v5/middleware/dataConverter/inputs/teamspaces/projects/models/commons/revisions.js
> +Revisions.validateNewRevisionData = validateMany([singleFileUpload('file', fileFilter), validateRevisionUpload]);
a bit of both I think

`singleFileUpload` is more of a utility function that produces a multer processor with the given filename and fileFilter. The fileFilter is incorporated into the resulting function to check extension, quota etc.

So it does both pre-processing and validate. If you can think of a better name to say preprocess + validate, i'm up for changing 😆

2021-11-02 11:45 UTC, sanmont3drepo approved these changes

2021-11-02 11:45 UTC, merged