ISSUE #2785 - Federations page
3drepo/3drepo.io pull request #2850
Opened 2021-11-05 14:39 UTC by EmilTheSadCat

This fixes #2785

2021-11-05 14:39 UTC, EmilTheSadCat commented
/azp run

2021-11-09 10:01 UTC, carmenfan commented
@EmilTheSadCat there's now a conflict. can you take a look? 

Though it might be better to fix the conflicts on https://github.com/3drepo/3drepo.io/pull/2831 first so we can merge that in , just in case there's more!

2021-11-10 15:31 UTC, george-hadfield commented
### Close search icon not in correct place
Icon needs more padding to the right
 
### Pictures & Links
![image](https://user-images.githubusercontent.com/78047794/141142547-21c3f859-bd3b-4e2e-b362-fbd85b5bf7f1.png)

2021-11-10 15:34 UTC, george-hadfield commented
### Move 'New Federation' button (large one) to inside the 'All Federations' list
It would be better if the behaviour of this large button was that it doesn't show if the 'All Federations' list is closed. It's purpose is for those users that are at the bottom of a very long Federations list. If it is closed, then there are buttons available at the top of the screen. Could this also be applied to the Containers section too?
 
### Pictures & Links
 
![image](https://user-images.githubusercontent.com/78047794/141143053-a59e3956-32ac-4a39-a486-c607fccd057a.png)

2021-11-10 15:36 UTC, george-hadfield requested changes
Left two small issues. Other than that, everything seems good!

2021-11-10 17:19 UTC, george-hadfield commented
### Empty search on favourites and All Federations displays incorrect text information
Currently it filters out to say you don't have any favourites or any Federations if there are no results to display.

It should display "We couldn't find a match for **“Search term”.** Please try another search." 

![image](https://user-images.githubusercontent.com/78047794/141161419-9cd82746-db36-452f-81ae-f4e57b79d6a2.png)

2021-11-12 18:44 UTC, sanmont3drepo commented
I've changed the base of the PR to staging due to ISSUE #2796  already been merged in. So there's some conlicts that must be solved.

2021-11-15 13:20 UTC, EmilTheSadCat commented
/azp run

2021-11-15 13:28 UTC, EmilTheSadCat commented
@sanmont3drepo Conflicts resolved.

@george-hadfield I've fixed the issues you've mentioned above. It's ready for another review.

2021-11-15 14:05 UTC, george-hadfield commented
@EmilTheSadCat just check and everything is working fine now. Thank you!

2021-11-22 16:18 UTC, sanmont3drepo requested changes

2021-11-22 16:18 UTC, sanmont3drepo commented on frontend/src/v5/ui/routes/dashboard/projects/federations/federationsList/federationsList.component.tsx
> +									<SkeletonListItem delay={index / 10} key={federation._id} />
I think we could have this inside of fedeationListItem, as it is it responsability to represent a ui item of a particular federation, including if it is fully loaded. Same goes with containers. If you think this doesnt seem like a good idea, let me know.

2021-11-23 14:13 UTC, carmenfan commented
@m1chalkubiak can you take a look at the changes here before you move onto the upload file dialog?

It also has a bit of conflicts with staging now

2021-11-23 15:03 UTC, m1chalkubiak commented
> @m1chalkubiak can you take a look at the changes here before you move onto the upload file dialog?
> 
> It also has a bit of conflicts with staging now

Sure @carmenfan I will handle it.

2021-11-23 15:48 UTC, m1chalkubiak commented on frontend/src/v5/ui/components/dashboard/dashboardList/dashboardSkeletonList/dashboardSkeletonList.component.tsx
> +							key: itemComponent.props.name,
I've fixed this. In fact, there were two issues here, one was the value of key which You absolutely had right, but also the key should be placed for direct children of rendered element list which, in this case, is the Fragment element.

2021-11-23 16:11 UTC, m1chalkubiak commented
I am still working on resolving conflicts because there are quite a lot of them, but I can already see that when this is finished I will have to improve the translations in all the newly created components in this PR because they used `lingui`. I will have to review them and correct it by one by one.

2021-11-24 11:01 UTC, sanmont3drepo commented
> I am still working on resolving conflicts because there are quite a lot of them, but I can already see that when this is finished I will have to improve the translations in all the newly created components in this PR because they used `lingui`. I will have to review them and correct it by one by one.

Is pretty straight forward to do so. just use `<FormattedMessage  />` instead of  `<Trans />` and `defaultMessage='..'` instead of `message='..'`` 

For rich text you can see an example here:
https://github.com/3drepo/3drepo.io/blob/e61ac076d49feb5d9793d8058f2c0596e54f437e/frontend/src/v5/ui/routes/dashboard/projects/containers/containersList/emptySearchResults/emptySearchResults.component.tsx#L28-L36

2021-11-24 11:23 UTC, sanmont3drepo commented
> > I am still working on resolving conflicts because there are quite a lot of them, but I can already see that when this is finished I will have to improve the translations in all the newly created components in this PR because they used `lingui`. I will have to review them and correct it by one by one.
> 
> Is pretty straight forward to do so. just use `<FormattedMessage />` instead of `<Trans />` and `defaultMessage='..'` instead of `message='..'``
> 
> For rich text you can see an example here:
> 
> https://github.com/3drepo/3drepo.io/blob/e61ac076d49feb5d9793d8058f2c0596e54f437e/frontend/src/v5/ui/routes/dashboard/projects/containers/containersList/emptySearchResults/emptySearchResults.component.tsx#L28-L36

For sagas or parts of the code  that doesnt have react we should use `formatMessage` from 'services/intl'
look at:

https://github.com/3drepo/3drepo.io/blob/e61ac076d49feb5d9793d8058f2c0596e54f437e/frontend/src/v5/store/projects/projects.sagas.ts#L21-L30

2021-11-24 12:25 UTC, m1chalkubiak commented
> > I am still working on resolving conflicts because there are quite a lot of them, but I can already see that when this is finished I will have to improve the translations in all the newly created components in this PR because they used `lingui`. I will have to review them and correct it by one by one.
> 
> Is pretty straight forward to do so. just use `<FormattedMessage />` instead of `<Trans />` and `defaultMessage='..'` instead of `message='..'``
> 
> For rich text you can see an example here:
> 
> https://github.com/3drepo/3drepo.io/blob/e61ac076d49feb5d9793d8058f2c0596e54f437e/frontend/src/v5/ui/routes/dashboard/projects/containers/containersList/emptySearchResults/emptySearchResults.component.tsx#L28-L36

@sanmont3drepo I did not say that it will be complicated, but only time-consuming, and as You know, I don't have much left. And I would like to devote as much as possible to things that will bring some value to the project.

Anyway, it is done and it seems to me that everything is working fine. I also figured out what was the issue with the `TextOverflow` component I corrected it here and I will add it also at https://github.com/3drepo/3drepo.io/pull/2852

2021-11-24 17:07 UTC, sanmont3drepo commented
/azp run

2021-11-25 16:28 UTC, sanmont3drepo approved these changes

2021-11-26 10:01 UTC, carmenfan commented
@george-hadfield  can you take another look on this one?

2021-11-30 14:07 UTC, Charence commented
@3drepo/product-team Please check this

2021-11-30 14:14 UTC, keifgwinn commented
/azp run

2021-12-01 15:39 UTC, carmenfan commented
/azp run

2021-12-02 17:21 UTC, carmenfan commented
@george-hadfield  the link should work again now

2021-12-06 10:09 UTC, carmenfan commented
@sanmont3drepo From the last design meeting, It's been concluded that they don't need categories in Federations so there has been a change on what is shown on the page 
![image](https://user-images.githubusercontent.com/11945337/144827545-3d11d799-da4b-45c2-8f42-e089372737e5.png)

The code is now where the category used to be, and the description is added below the model name

2021-12-07 17:43 UTC, sanmont3drepo commented
/azp run

2021-12-09 10:05 UTC, sanmont3drepo commented
/azp run

2021-12-09 14:18 UTC, george-hadfield commented
### Remove hover state from Federation and Container items
Currently a shadow and scale when a user hovers the item row, however, after seeing this implemented, it's too much movement. I'd like to remove the shadow and scale on hover if possible.
 
### Pictures & Links

![image](https://user-images.githubusercontent.com/78047794/145413021-702ab86f-7abb-4fea-8948-23322f79a7bc.png)

2021-12-09 14:22 UTC, george-hadfield commented
### Responsive: Content needs margin left and right at smaller breakpoints. 
Please refer to the containers responsive: https://www.figma.com/file/djgxvRKOaMMyutswn5yywU/Teamspace-(live)?node-id=3274%3A46976

### Pictures & Links

Build
![image](https://user-images.githubusercontent.com/78047794/145413358-3aca64c0-b1a7-4a1e-be48-07c8c2f890cb.png)

Design
![image](https://user-images.githubusercontent.com/78047794/145413786-16961787-bb59-4a31-a0a5-2dcfb7002558.png)

2021-12-09 14:25 UTC, george-hadfield commented
### Responsive: Columns should scale the same as containers
Please refer to the Containers responsive design for guidance https://www.figma.com/file/djgxvRKOaMMyutswn5yywU/Teamspace-(live)?node-id=3274%3A46976

### Pictures & Links 

Build
![image](https://user-images.githubusercontent.com/78047794/145414350-43d21301-3496-49e7-8f7e-a9c7ab2433f9.png)

2021-12-09 14:27 UTC, george-hadfield commented
### Main nav needs to use the updated V2 style

### Pictures and links

Build
![image](https://user-images.githubusercontent.com/78047794/145414604-1ae90e01-8a67-457b-a1e2-c2cf84af780c.png)

Design
![image](https://user-images.githubusercontent.com/78047794/145414745-e906b4a1-fd2c-4c66-8b4a-f2f61bffd48e.png)

2021-12-09 17:38 UTC, sanmont3drepo commented
> ### Main nav needs to use the updated V2 style
> ### Pictures and links
> Build ![image](https://user-images.githubusercontent.com/78047794/145414604-1ae90e01-8a67-457b-a1e2-c2cf84af780c.png)
> 
> Design ![image](https://user-images.githubusercontent.com/78047794/145414745-e906b4a1-fd2c-4c66-8b4a-f2f61bffd48e.png)

This will be addressed in https://github.com/3drepo/3drepo.io/pull/2852

2021-12-09 17:39 UTC, sanmont3drepo commented
> ### Responsive: Content needs margin left and right at smaller breakpoints.
> Please refer to the containers responsive: https://www.figma.com/file/djgxvRKOaMMyutswn5yywU/Teamspace-(live)?node-id=3274%3A46976
> 
> ### Pictures & Links
> Build ![image](https://user-images.githubusercontent.com/78047794/145413358-3aca64c0-b1a7-4a1e-be48-07c8c2f890cb.png)
> 
> Design ![image](https://user-images.githubusercontent.com/78047794/145413786-16961787-bb59-4a31-a0a5-2dcfb7002558.png)

I believe this needs to be addressed in https://github.com/3drepo/3drepo.io/pull/2852  (it has all the new code regarding responsiveness)

2021-12-09 17:46 UTC, sanmont3drepo commented
> ### Remove hover state from Federation and Container items
> Currently a shadow and scale when a user hovers the item row, however, after seeing this implemented, it's too much movement. I'd like to remove the shadow and scale on hover if possible.
> 
> ### Pictures & Links
> ![image](https://user-images.githubusercontent.com/78047794/145413021-702ab86f-7abb-4fea-8948-23322f79a7bc.png)

Will be addressed in https://github.com/3drepo/3drepo.io/issues/2903

2021-12-10 11:01 UTC, george-hadfield approved these changes
Approved based on Carmens comments in Teams

2021-12-10 11:33 UTC, sanmont3drepo approved these changes

2021-12-10 11:48 UTC, merged