ISSUE #2868 - Import Animations bug
3drepo/3drepo.io pull request #2896
Opened 2021-12-08 13:56 UTC by ChristosTsiotsias

This fixes #2868 
#### Description
Bug fix added so that importAnimations is not always true when uploading new revisions

#### Test cases
Upload a new revision into a model sending an SMP file
In the request body (or from the UI) set the import animations option to false
Animations should not be uploaded

2021-12-08 15:10 UTC, carmenfan commented
@ChristosTsiotsias  
This is not quite right, if importAnimations is unset, it needs to evaluate to true, so it should only evaluate to false if it's specifically set that way.


Thinking about it, instead of fixing this, can you look into removing the v4 code, and get the v4 route to call v5 functions instead? I did something similar for group import/export as you can see [here](https://github.com/3drepo/3drepo.io/blob/staging/backend/src/v4/routes/group.js#L487) It's just calling functions imported from v5.

This will then automatically fix this, and also makes your next task easier (as you won't have to alter 2 endpoints.

2021-12-08 15:13 UTC, ChristosTsiotsias commented
> @ChristosTsiotsias This is not quite right, if importAnimations is unset, it needs to evaluate to true, so it should only evaluate to false if it's specifically set that way.
> 
> Thinking about it, instead of fixing this, can you look into removing the v4 code, and get the v4 route to call v5 functions instead? I did something similar for group import/export as you can see [here](https://github.com/3drepo/3drepo.io/blob/staging/backend/src/v4/routes/group.js#L487) It's just calling functions imported from v5.
> 
> This will then automatically fix this, and also makes your next task easier (as you won't have to alter 2 endpoints.

Ah okay I thought the default value was false. Sure I will try to do it the way you say

2021-12-13 17:36 UTC, carmenfan requested changes

2021-12-13 17:36 UTC, carmenfan commented on backend/src/v4/routes/model.js
> +router.post("/:model/upload", middlewares.chechPermsAndFormatV5NewRevisionsData, validateNewRevisionData, uploadModel);
Let's keep them separate 
```suggestion
router.post("/:model/upload", middlewares.hasUploadAccessToModel, middlewares.formatV5NewRevisionsData, validateNewRevisionData, uploadModel);
```

2021-12-13 17:36 UTC, carmenfan commented on backend/src/v5/middleware/dataConverter/inputs/teamspaces/projects/models/commons/revisions.js
> +		const isTagValid = await isValidTag(req.params.teamspace, req.params.container, req.body.tag);
Can we do that as part of the test in L70?

I.e. line 70 should look something like this:

````js
  tag: YupHelper.types.strings.code.required().test("tag-not-in-use", "Revision name is already used by an existing revision", async () => { /* the tag test here*/})
````

2021-12-13 17:36 UTC, carmenfan commented on backend/src/v5/models/revisions.js
> +Revisions.isValidTag = async (teamspace, model, tag) => {
Naming of the function is a bit weird, what we're testing here is if tag is already in use. so maybe it's better to call it `tagInUse` or something

2022-01-04 09:49 UTC, merged