Issue 2997
3drepo/3drepo.io pull request #3060
Opened 2022-02-21 18:57 UTC by ChristosTsiotsias

This fixes #2997

#### Description
Endpoint to download original files from a revision
Swagger doc, unit and e2e tests are included

#### Test cases
The user should be able to download the original file of a revision in binary form.
Swagger documentation should be present.

2022-02-23 11:30 UTC, carmenfan requested changes

2022-02-23 11:30 UTC, carmenfan commented on backend/tests/v5/e2e/routes/teamspaces/projects/containers/revisions.test.js
> +			|| !rev.void ? { ...rev, timestamp: rev.timestamp.getTime(), rFile: undefined } : []));
rFile is an internal data and it should never be exposed to the outside world, even as an undefined - check what the code is doing if you're seeing this escaping to the outside world?

2022-02-23 11:30 UTC, carmenfan commented on backend/tests/v5/e2e/routes/teamspaces/projects/containers/revisions.test.js
> +		test('should fail if revision has file but no ref', async () => {
check permission level too

Ensure only collaborator+ can get the file

2022-02-23 11:30 UTC, carmenfan commented on backend/tests/v5/e2e/routes/teamspaces/projects/containers/revisions.test.js
> +			await agent.get(`${route(teamspace, project.id, modelWithRev._id, validRefTypeRevision._id)}?key=${users.tsAdmin.apiKey}`).expect(templates.ok.status);
Should also be checking the content of the file is what you're expecting.

2022-02-23 11:30 UTC, carmenfan commented on backend/tests/v5/e2e/routes/teamspaces/projects/containers/revisions.test.js
> +		ServiceHelper.db.createRevisionRef(teamspace, modelWithRev._id, `${validRefTypeRevision._id}P2006823-BDP-XX-A-Stanmore-Envelope_optimized_ifc`),
let createRevision do this if there's a file ref, just pass data with it to store

2022-02-23 11:30 UTC, carmenfan commented on backend/tests/v5/helper/services.js
> +	let refInfo = await ExternalServices.storeFile(teamspace, `${modelId}.history.ref`, data);
We need to make sure we clean the folder after the tests or we end up with clutter, or files that shouldn't exist to start existing.

the fileshare is set here https://github.com/3drepo/3drepo.io/blob/master/config/testV5/config.js#L82

So as part of the tear down (the bit that is called in [`afterAll` in jest](https://jestjs.io/docs/setup-teardown#one-time-setup)), you will probabyl want a function to remove all contents within that folder.

2022-02-23 11:30 UTC, carmenfan commented on backend/tests/v5/helper/services.js
> +		rFile: hasFile ? [`${_id}P2006823-BDP-XX-A-Stanmore-Envelope_optimized_ifc`] : undefined,
should only has this entry if it has the file - we shouldn't be storing `rFile: undefined` anywhere.
```suggestion
		...(hasFile ? {rFile: [`${_id}P2006823-BDP-XX-A-Stanmore-Envelope_optimized_ifc`]} : {})
```

2022-02-23 11:30 UTC, carmenfan commented on backend/tests/v5/helper/services.js
> +		rFile: hasFile ? [`${_id}P2006823-BDP-XX-A-Stanmore-Envelope_optimized_ifc`] : undefined,
why do we need to hardcode in `P2006823-BDP-XX-A-Stanmore-Envelope_optimized_ifc` ?

2022-02-23 11:30 UTC, carmenfan commented on backend/tests/v5/helper/services.js
> +	_id: `${revisionId}P2006823-BDP-XX-A-Stanmore-Envelope_optimized_ifc`,
hardcoded model name here too

2022-02-23 11:30 UTC, carmenfan commented on backend/tests/v5/unit/models/fileRefs.test.js
> +			const filename = 'b74ba13b-71db-4fcc-9ff8-7f640aa3dec2P2006823-BDP-XX-A-Stanmore-Envelope_optimized_ifc';
too ad-hoc, just use generateUUIDString() and generateRandomString() to make up this name.

2022-02-23 11:30 UTC, carmenfan commented on backend/tests/v5/unit/models/fileRefs.test.js
> +			const filename = 'b74ba13b-71db-4fcc-9ff8-7f640aa3dec2P2006823-BDP-XX-A-Stanmore-Envelope';
same here

2022-02-23 11:30 UTC, carmenfan commented on backend/tests/v5/unit/models/fileRefs.test.js
> +			const revision = { rFile: [] };
also add a case for if rFile is not defined

2022-02-23 19:43 UTC, ChristosTsiotsias commented on backend/src/v5/processors/teamspaces/projects/models/containers.js
> +	return downloadFiles(teamspace, container, revision);
do you reckon I should add another method in fileRef model called getRevisionByTag or should I expose findOneRevisionByQuery and call that with a query from the processor ?

2022-02-24 10:09 UTC, carmenfan commented on backend/src/v5/processors/teamspaces/projects/models/containers.js
> +	return downloadFiles(teamspace, container, revision);
you mean revision model? 

I think you should just have a getRevisionByIdOrTag. In general all our revision queries are based on that

2022-03-01 17:17 UTC, carmenfan approved these changes

2022-03-01 17:59 UTC, carmenfan approved these changes

2022-03-01 17:59 UTC, merged