ISSUE #3081 - V5 Login Screen
3drepo/3drepo.io pull request #3119
Opened 2022-03-25 11:29 UTC by The-Daniel

This fixes #3081 

#### Description
- Adds login screen for v5
- If you are in the v5 part of the app and authenticated you get redirected to /v5/login
- If you try to navigate to /v5/login and you are authenticated you will get redirected to /v5/dashboard
- Saga testing for login

#### Test cases
- Log in
- Log out
- Log in with incorrect credentials. Observe the error message.
- When logged in attempt to navigate to /v5/login. You will be redirected to dashboard.
- When logged out attempt to navigate to another part of the app (e.g. v5/dashboard) you will be redirected to the login screen.
- Log out and try the v4 login. This should be unaffected.
- Login too many times with correct username but incorrect password. Observe the account lockout message.

#### Notes
- The SVG background is subject to change
- The links currently point to the v4 URLs. The release notes currently links to a dead link as awaiting the location for that.
- The input labels are currently in all caps as this will change when the control changes in ISSUE #[3084](https://github.com/3drepo/3drepo.io/issues/3084)
- The profile fetching logic during authentication is missing as this requires ISSUE #3049. All this currently means is that your profile image is missing in the top right.

2022-03-25 11:31 UTC, The-Daniel commented
/azp run

2022-03-25 11:39 UTC, carmenfan commented
> Pull request contains merge conflicts.

@The-Daniel Just incase you missed the message, you need to merge staging in and resolve the conflicts before the deployment will run 😄

2022-03-25 11:40 UTC, The-Daniel commented
Ha, yes. Fixing the conflicts as we speak

2022-03-25 14:58 UTC, The-Daniel commented
/azp run

2022-03-28 22:17 UTC, sanmont3drepo requested changes

2022-03-29 13:32 UTC, george-hadfield commented
Looks great! 

There has been an issue added though to change all field labels to use the body font and Sentence case instead of uppercase (https://github.com/3drepo/3drepo.io/issues/3084#issuecomment-1061771440).

2022-03-29 15:27 UTC, sanmont3drepo approved these changes

2022-03-29 15:48 UTC, merged