Issue 3114 - Saving federations settings with an already set view throws an error
3drepo/3drepo.io pull request #3128
Opened 2022-04-04 15:09 UTC by Amantini1997

This fixes #3114

#### Description
- Updating a federation with a selected defaultView does not trigger errors anymore

2022-04-04 15:28 UTC, carmenfan requested changes

2022-04-04 15:28 UTC, carmenfan commented on backend/src/v5/processors/teamspaces/projects/models/federations.js
> +	return {
output formats are done here https://github.com/3drepo/3drepo.io/blob/master/backend/src/v5/middleware/dataConverter/outputs/teamspaces/projects/models/commons/modelSettings.js#L23

2022-04-04 17:17 UTC, carmenfan commented
@ChristosTsiotsias  can you take over this one and make sure we have a check in place in the tests to check if the default view UUID has been converted?

2022-04-04 17:38 UTC, ChristosTsiotsias commented
> @ChristosTsiotsias can you take over this one and make sure we have a check in place in the tests to check if the default view UUID has been converted?

sure

2022-04-06 21:52 UTC, carmenfan approved these changes

2022-04-06 21:52 UTC, merged