Issue 3139 - Utility script suite
3drepo/3drepo.io pull request #3212
Opened 2022-05-09 13:58 UTC by carmenfan

This fixes #3139

#### Description
- Modified the way scripts are triggered
  -  it now runs from an index file instead of just calling the file directly
  - Standardised every script file in terms of how to take in operands and how to run
  - use Yargs to manage parameters
  - added new scripts: 
    - identifyZombieFiles - removes any files in fileshare that is not referenced by a `ref` entry
    - findDataUsageInAllTeamspaces - calculate quota and storage size used per teamspace
    - removeTeamspaceData - remove all data and license holders from the teamspace (essentially a reset, but without reinstating the toy project
    - updateAddOns - manage add ons given to a teamspace
    - updateLicense - manage licenses given to a teamspace

#### Tests
scripts should work as intended

2022-05-12 14:27 UTC, ChristosTsiotsias requested changes

2022-05-12 14:45 UTC, carmenfan commented on backend/src/v5/models/teamspaces.js
> +	if (Object.keys(action).length) {
yes, but we would be making the assumption that every single function call comes from something that went through the middleware (which is ingeneral a fair assumption if everything is functioning correctly)

this is just a simple safeguard to just not bother the mongo db with a query that will error out. Considering it's just an if statement (unlike permission checks) on a simple check it's probably a price worth paying.

2022-05-12 14:46 UTC, carmenfan commented on backend/src/scripts/utility/teamspaces/removeTeamspaceData.js
> +		const opsProms = [
again, done deliberate to avoid bombarding the database with a lot of write operations

2022-05-12 14:48 UTC, carmenfan commented on backend/src/scripts/utility/teamspaces/findDataUsageInAllTeamspaces.js
> +/**
actually it's probably using a very small amount of data (remember the units is GB, so 5e-5 is about 500KB)

It is probably using a small amount of data for the purpose of indexing etc

2022-05-16 09:55 UTC, ChristosTsiotsias commented on backend/src/scripts/utility/teamspaces/findDataUsageInAllTeamspaces.js
> +/**
are we fine with this ?

2022-05-16 09:56 UTC, carmenfan commented on backend/src/scripts/utility/teamspaces/findDataUsageInAllTeamspaces.js
> +/**
you are using data storage, I don't see any issue here.

The number only looks small because it's in GiB.

2022-05-16 10:38 UTC, ChristosTsiotsias approved these changes

2022-05-16 13:20 UTC, carmenfan commented
tagging this with `wait on merge` incase Keif find any bugs running this on a prod clone

2022-05-20 11:42 UTC, carmenfan commented
@ChristosTsiotsias  I added another script to completely remove a user from the db, can you take another look here?

2022-05-23 11:36 UTC, keifgwinn commented
/azp run

2022-05-23 15:41 UTC, ChristosTsiotsias commented
Looks good, only thing is it doesnt remove the user role from system.roles

2022-05-24 08:59 UTC, keifgwinn commented
/azp run

2022-05-24 11:07 UTC, carmenfan commented
@ChristosTsiotsias  added remove role logic (good spot!)

Also realised we're not removing favourites from other users if they favourited some models within that teamspace, so added that too

Ready for another look

2022-05-24 12:02 UTC, ChristosTsiotsias reviewed
Looks good, only thing I would do differently is I'd probably have only 2 methods, one for removing all teamspace/user data and DBs and one for removing all references of it in other DBs

2022-05-25 10:21 UTC, carmenfan commented
another change requested by @keifgwinn - teamspace removal script should not fail if the teamspace is not found - should just skip.

2022-05-31 10:08 UTC, keifgwinn commented
/azp run

2022-06-01 09:31 UTC, keifgwinn commented
/azp run

2022-06-01 09:39 UTC, keifgwinn commented
/azp run

2022-06-01 09:45 UTC, keifgwinn commented
/azp run

2022-06-10 17:21 UTC, keifgwinn commented
/azp run

2022-06-14 13:37 UTC, merged