ISSUE #3225 - Viewer facelift - BIM Card
3drepo/3drepo.io pull request #3241
Opened 2022-05-12 12:53 UTC by The-Daniel

This fixes #3225

#### Description
- Adds styling to the BIM card in the v5 viewer

#### Test cases
- Open the BIM viewer.
- Click different segments
- Favourite/Unfavourite items

2022-05-12 14:37 UTC, The-Daniel commented
/azp run

2022-05-12 16:17 UTC, george-hadfield commented
Waiting to get access to a model with BIM data

2022-05-13 10:15 UTC, sanmont3drepo commented
Make the dotted border span the full width of the card-allowing for the side margins.

![image](https://user-images.githubusercontent.com/42032433/168263081-77c56193-c2f0-4590-aa56-81a65e6257ba.png)

2022-05-13 10:18 UTC, sanmont3drepo commented
The grey should be #F7F8FA
![image](https://user-images.githubusercontent.com/42032433/168263451-4fa9c7ae-6054-4c31-ae3f-ba16c757d0be.png)

2022-05-13 13:19 UTC, Amantini1997 commented
> Make the dotted border span the full width of the card-allowing for the side margins.
> 
> ![image](https://user-images.githubusercontent.com/42032433/168263081-77c56193-c2f0-4590-aa56-81a65e6257ba.png)

I reckon this is fixed in the base branch, you just need to do a pull

2022-05-13 13:19 UTC, Amantini1997 requested changes

2022-05-13 13:19 UTC, Amantini1997 commented on frontend/src/v5/ui/v4Adapter/overrides/bim.overrides.ts
> + *  Copyright (C) 2022 3D Repo Ltd
copyright year

2022-05-13 13:22 UTC, george-hadfield approved these changes

2022-05-13 13:22 UTC, merged