ISSUE #2805 - Having non existing users in the db does not block you from updating permissions
3drepo/3drepo.io pull request #3260
Opened 2022-05-17 10:33 UTC by ChristosTsiotsias

This fixes #2805

#### Description
When updating model permissions, only the permissions changed are validated. Thus, when there are permissions that include users that no longer exist / have access to the TS no errors are being thrown.

#### Test cases
In a model that has permissions with non existing user, update a permission.

2022-05-17 10:35 UTC, ChristosTsiotsias commented
I have copied some functionality from changePermissions to updatePermissions so there are some duplicate lines. The other alternative I thought and have saved is to change the changePermissions method to only accept permissions to be updated but all places that call it need to be adjusted.

2022-05-19 09:41 UTC, carmenfan requested changes

2022-05-19 09:41 UTC, carmenfan commented on backend/src/v4/models/modelSetting.js
> +			db.updateOne(account, MODELS_COLL, { _id: model }, action);
if we have n permissions, we're doing n updates to the single document.  don't think this is a good idea


Also the fact that you could be overwriting the whole array with $set at L452 means you might end up in a weird state where some $push/pull gets overwritten.

You are probably better off doing a single $set at the end of the loop at this rate.

2022-05-19 09:41 UTC, carmenfan commented on backend/src/v4/routes/model.js
> -router.post("/models/permissions", middlewares.hasEditPermissionsAccessToMulitpleModels, updateMultiplePermissions);
does this make sense? If i'm reading you correctly, you're making this POST request do the same thing as the PATCH request.

Which shouldn't be the case? POST should overwrite the array where as PATCH should make changes to it?

2022-05-20 16:39 UTC, carmenfan requested changes

2022-05-20 16:39 UTC, carmenfan commented on backend/src/v4/models/modelSetting.js
> +	permissions.forEach(permission => {
instead of using a `forEach` where every iteration we doing a `push` to an array of promise, we should use a map.

2022-05-20 16:39 UTC, carmenfan commented on backend/src/v4/models/modelSetting.js
> +		promises.push(teamspaceMemberCheck(permission.user, dbUser.user).then(() => {
use async/await syntax instead of .then 

```suggestion
		promises.push(teamspaceMemberCheck(permission.user, dbUser.user).then(() => {
```

2022-05-23 13:03 UTC, carmenfan approved these changes

2022-05-23 13:03 UTC, merged