Issue 3220 - Authenticated routes and redirection refactored
3drepo/3drepo.io pull request #3273
Opened 2022-05-18 17:43 UTC by sanmont3drepo

This fixes #3220 

#### Description
- Added a new `<AuthenticatedRoute />` component that redirect to login if the user is not authenticated and sets the returnURL
- Now after login the user gets redirected to returnURL

2022-05-20 09:24 UTC, sanmont3drepo commented on frontend/src/v5/store/auth/auth.selectors.ts
> +const selectAuthDomain = (state): IAuthState => state.auth2;
It doesnt matter, because, after this one all the selectors get the right type.

2022-05-20 10:50 UTC, sanmont3drepo commented on frontend/src/v5/ui/routes/dashboard/index.tsx
> +				<AuthenticatedRoute exact path={`${path}/dashboard/`}>
I think that might be a different issue. I didnt change any of the routes just how privacy is being enforced.

2022-05-24 09:08 UTC, The-Daniel approved these changes

2022-05-24 16:24 UTC, Amantini1997 requested changes

2022-05-25 10:54 UTC, Amantini1997 approved these changes

2022-05-25 11:41 UTC, Amantini1997 approved these changes

2022-05-25 11:41 UTC, merged