ISSUE #3216 - You can upload files to containers that are being processed
3drepo/3drepo.io pull request #3278
Opened 2022-05-19 14:24 UTC by The-Daniel

This fixes #3216 

#### Description
- Disables/hides upload revision buttons in the containers dashboard if a container has a revision still being processed
- Disables container option in the uploads modal if the container has a revision still being processed

#### Test cases
- Upload a revision to a container
- Try to upload a new revision to this container through the containers dashboard or upload revision modal

2022-05-19 16:59 UTC, sanmont3drepo commented
/azp run

2022-05-24 11:15 UTC, george-hadfield commented
I'm not sure if I'm doing this incorrectly or not, but I was able to upload two of the same files as separate revisions to the same container.

2022-05-24 11:15 UTC, george-hadfield commented
<img width="1396" alt="image" src="https://user-images.githubusercontent.com/78047794/170022303-3bfd977e-0245-4fc2-915c-f256d5bcfaf2.png">

Which then displays as no revisions/files after uploading

2022-06-01 14:14 UTC, sanmont3drepo requested changes

2022-06-01 14:14 UTC, sanmont3drepo commented on frontend/src/v5/ui/routes/dashboard/projects/containers/uploadFileForm/uploadList/uploadListItem/uploadListItem.component.tsx
>  				}}
Can we put this function outside the jsx code?

2022-06-01 14:25 UTC, george-hadfield submitted a review, later dismissed

2022-06-07 11:08 UTC, sanmont3drepo approved these changes

2022-06-07 11:40 UTC, merged