Issue 3223 - Ability to filter medatata
3drepo/3drepo.io pull request #3279
Opened 2022-05-20 08:10 UTC by ChristosTsiotsias

This fixes #3223

#### Description
Ability to filter returned metadata based on their keys has been added.

#### Test cases
Make a metadata request and pass the key filters in the query. Only the metadata objects that include those keys should be returned and only these keys and their values should be displayed.

2022-05-20 11:38 UTC, carmenfan requested changes

2022-05-20 11:38 UTC, carmenfan commented on backend/src/v4/models/scene.js
> +	if (fieldNames.length) {
I think it's better to assume the user may not pass in `[]` if they don't want to filter. 

```suggestion
	if (fieldNames?.length) {
```

Or you do `fieldNames=[]` on L78

2022-05-20 14:53 UTC, carmenfan commented
/azp run

2022-05-20 14:53 UTC, carmenfan approved these changes

2022-05-20 14:54 UTC, carmenfan commented
@mosment3DRepo  ready for QA

2022-05-23 16:45 UTC, mosment3DRepo commented
## Filter not working on Metadata by Rules endpoint

As well as the Get All Metadata endpoint the filter was intended to work on the https://3drepo.github.io/3drepo.io/#api-Meta-queryMetadataByRules endpoint

2022-05-23 16:53 UTC, mosment3DRepo requested changes
see list

2022-05-23 17:15 UTC, carmenfan commented
> ## Illegal characters in Query String
> The following model contains a metadata key which include a comma ("hello,world") when I run the following query I get no responses, unclear if there is any way to quote out the commas to avoid this happening
> 
> https://issue-3223.dev.3drepo.io/api/mosment3ddev/b60e7190-205d-11ec-a7d1-f183b9e6b73a/revision/master/head/meta/all.json?filter=hello,world

@mosment3DRepo  it still wouldn't work as Christos would have to do some more work to support it, but this should be passed in with the comma escaped, i.e.

> https://issue-3223.dev.3drepo.io/api/mosment3ddev/b60e7190-205d-11ec-a7d1-f183b9e6b73a/revision/master/head/meta/all.json?filter=hello%2Cworld

@ChristosTsiotsias  we'd have to run a pass to[ un-escape any characters](https://attacomsian.com/blog/nodejs-encode-decode-url) after splitting them into a string array

2022-05-31 13:16 UTC, carmenfan commented
/azp run

2022-06-01 08:41 UTC, carmenfan requested changes

2022-06-01 16:38 UTC, carmenfan commented
Looks fine
@miadibe  @mosment3DRepo Christos has rewritten the query for metadata by rules slightly - we may want to run a few tests through that to make sure the results are still the same (with and without filter logic)

2022-06-06 13:45 UTC, miadibe commented
- [ ] [Illegal Characters in query string](https://github.com/3drepo/3drepo.io/pull/3279#issuecomment-1134910277)
@mosment3DRepo to double check
- [ ] [Filter not working on Metadata by Rules endpoint](https://github.com/3drepo/3drepo.io/pull/3279#issuecomment-1134905754)
Tested and confirm it's working as expected 
- [ ] [Filter not applied to federations ](https://github.com/3drepo/3drepo.io/pull/3279#issuecomment-1134904683)
Tested and confirm is working as expected

2022-06-13 16:15 UTC, mosment3DRepo approved these changes
Tested issues raised in last review.

Tested all features from scratch and compared results to query on All Meta json

2022-06-14 10:51 UTC, merged