Issue 3312 - Additional real time events
3drepo/3drepo.io pull request #3366
Opened 2022-06-22 13:07 UTC by ChristosTsiotsias

This fixes #3312 

#### Description

The following real time events have been added:

New Revision (Container)
New Revision (Federation)
Revision Updated (Container)
Delete Container
Delete Federation
New Container
New Federation

Documentation for each event has been added

#### Test cases

A real time event should be triggered upon each action
The events documentation should be updated to include all new events

2022-06-22 13:52 UTC, carmenfan requested changes
Missing code to allow a user to join a project room, as it stands it's impossible for anyone to subscribe to a project event.

https://github.com/3drepo/3drepo.io/blob/195c67e839d17873827b926cf4d02beca42d7f26/backend/src/v5/services/chat/socketsManager.js#L40

There should also be e2e tests for all those chat events you've created (if you've done them you'd realise there's no way to join a project room!), see here for examples: https://github.com/3drepo/3drepo.io/tree/195c67e839d17873827b926cf4d02beca42d7f26/backend/tests/v5/e2e/services/chat/modelEvents

2022-06-22 13:52 UTC, carmenfan commented on backend/src/v5/models/modelSettings.js
> -
not fond of how we're publishing the model related events here apart from this one.

Can do we a findOneAndDelete instead so you can figure out if it's a federation and trigger the event here (assuming this is the reason why you moved it out)

2022-06-22 13:52 UTC, carmenfan commented on backend/src/v5/services/eventsListener/components/modelEvents.js
> +		const { tag, author, timestamp } = await getRevisionByIdOrTag(teamspace, model, corId,
Not the best place i don't think.

We might be processing a failed model import, in which case you're still attempting to trigger a new revision event here.

I think its' best if `newRevisionProcessed ` trigger a` NEW_REVISION` event upon model processing succeeded, and we catch it to create the chat message, it also knows whether it's a container so you don't have to do `getModelById`

2022-06-22 13:52 UTC, carmenfan commented on backend/src/v5/services/eventsListener/components/projectEvents.js
> +const modelAdded = async ({ teamspace, project, model, data, isFederation }) => {
wrong place

This is a model event.

(even though in the chat service, it's broadcasted in the project room)

There's a difference between the event managers within the backend and the chat service events, they're 2 different things

2022-06-22 13:52 UTC, carmenfan commented on backend/src/v5/services/eventsManager/eventsManager.constants.js
> +	'MODEL_IMPORT_FINISHED', 'REVISION_UPDATED',
Revision update isn't part of import, just put it under revisions

2022-06-27 15:10 UTC, carmenfan commented on backend/tests/v5/e2e/services/chat/modelEvents/modelUploads.test.js
> +const revisionUpdateTest = () => {
as discussed this should go into modeRevisions file separately

2022-06-27 15:11 UTC, carmenfan commented on backend/tests/v5/e2e/services/chat/modelEvents/modelUploads.test.js
> +const revisionAddedTest = () => {
as discussed, you shouldn't need an additional test for this? `queueFinishedTest` essentially is the same situation

2022-06-27 15:12 UTC, carmenfan commented on backend/tests/v5/unit/models/modelSettings.test.js
> +	describe('Add model', () => {
redundant, you already created a `Add model` test group

2022-06-27 15:13 UTC, carmenfan commented on backend/tests/v5/unit/models/modelSettings.test.js
> +			expect(fn).toHaveBeenCalledWith(teamspace, 'settings', { _id: model }, { federate: 1 });
should add a line to ensure `EventsManager.publish` has not been called

2022-06-27 15:18 UTC, carmenfan commented on backend/tests/v5/unit/services/eventsListener/eventsListener.test.js
> +		test(`Should trigger queueStatusUpdate if there is a ${events.QUEUED_TASK_UPDATE}`, async () => {
```suggestion
		test(`Should trigger updateModelStatusif there is a ${events.QUEUED_TASK_UPDATE}`, async () => {
```

2022-06-27 15:19 UTC, carmenfan commented on backend/tests/v5/unit/services/eventsListener/eventsListener.test.js
> +		test(`Should trigger queueTasksCompleted if there is a ${events.QUEUED_TASK_COMPLETED} (federation)`, async () => {
same here

2022-06-27 15:24 UTC, carmenfan commented on backend/tests/v5/unit/services/eventsListener/eventsListener.test.js
> +		test(`Should trigger modelAdded if there is a ${events.NEW_MODEL} (federation)`, async () => {
better description

2022-06-29 10:09 UTC, ChristosTsiotsias commented on backend/tests/v5/unit/services/eventsListener/eventsListener.test.js
> +		test(`Should fail gracefully on error if there is a ${events.REVISION_UPDATED}`, async () => {
Isnt the modelSettingsUpdated unlikely to error as well then ? Both are just calling createModelMessage

![image](https://user-images.githubusercontent.com/71635617/176411440-dc7be22b-a02f-4c3a-bcb4-9e062accb928.png)

2022-06-29 10:10 UTC, carmenfan commented on backend/tests/v5/unit/services/eventsListener/eventsListener.test.js
> +		test(`Should fail gracefully on error if there is a ${events.REVISION_UPDATED}`, async () => {
yep that's true. it also shouldn't be wrapped and error handling should be done on the other side

2022-06-29 10:15 UTC, carmenfan commented on backend/tests/v5/unit/services/eventsListener/eventsListener.test.js
> +		test(`Should fail gracefully on error if there is a ${events.REVISION_UPDATED}`, async () => {
yes, let's do that

2022-07-05 11:10 UTC, carmenfan approved these changes

2022-07-05 11:32 UTC, merged