Issue 3318 - Viewer facelift - Safetibase Treatments card
3drepo/3drepo.io pull request #3370
Opened 2022-06-23 10:20 UTC by Amantini1997

This fixes #3318

#### Description
- Fixed styling in the main tab
- Partly fixed suggested-treatment modal styling (mockup is missing)

2022-06-23 10:21 UTC, Amantini1997 commented
/azp run

2022-06-23 16:27 UTC, The-Daniel requested changes

2022-06-23 17:37 UTC, Amantini1997 commented on frontend/src/v5/ui/v4Adapter/overrides/cards/safetiBase/treatments.overrides.ts
> +					height: 23px;
yes, you are right. It was meant to be min-height instead. I fixed it

2022-06-24 09:15 UTC, The-Daniel approved these changes

2022-06-30 16:08 UTC, george-hadfield commented
@Amantini1997 @carmenfan can we change the case of UNSET to Title case? Seems a bit shouty..

<img width="224" alt="image" src="https://user-images.githubusercontent.com/78047794/176725822-a8f82e02-8937-4894-aebe-a7f443ae7440.png">

2022-07-04 10:43 UTC, carmenfan commented
> > @Amantini1997 @carmenfan can we change the case of UNSET to Title case? Seems a bit shouty..
> > <img alt="image" width="224" src="https://user-images.githubusercontent.com/78047794/176725822-a8f82e02-8937-4894-aebe-a7f443ae7440.png">
> 
> If @carmenfan is ok, I will proceed to fix that

@mosment3DRepo

2022-07-04 16:14 UTC, mosment3DRepo commented
> > > @Amantini1997 @carmenfan can we change the case of UNSET to Title case? Seems a bit shouty..
> > > <img alt="image" width="224" src="https://user-images.githubusercontent.com/78047794/176725822-a8f82e02-8937-4894-aebe-a7f443ae7440.png">
> > 
> > 
> > If @carmenfan is ok, I will proceed to fix that
> 
> @mosment3DRepo

Agreed to having it proper case. Can't find any evidence of why it was all caps in the first place

2022-07-05 13:00 UTC, george-hadfield commented on frontend/src/v5/ui/v4Adapter/dialogs/suggestedTreatmentsDialog.overrides.ts
> +				color: #C1C8D5;
Which part of the design is using #C1C8D5?

2022-07-05 14:25 UTC, Amantini1997 commented
/azp run

2022-07-05 18:40 UTC, Amantini1997 commented on frontend/src/v5/ui/v4Adapter/dialogs/suggestedTreatmentsDialog.overrides.ts
> +				color: #C1C8D5;
@george-hadfield several components are, for instance, the dropdown border as well as the chevron icon

2022-07-06 13:34 UTC, george-hadfield commented on frontend/src/v5/ui/v4Adapter/dialogs/suggestedTreatmentsDialog.overrides.ts
> +				color: #C1C8D5;
@Amantini1997 apologies - can you make sure it matches the same colours as the other components.

2022-07-14 07:13 UTC, george-hadfield approved these changes

2022-07-15 08:22 UTC, Amantini1997 commented on frontend/src/v5/ui/v4Adapter/dialogs/suggestedTreatmentsDialog.overrides.ts
> +				color: #C1C8D5;
> Move "this field is required" text for Safetibase title to the right
> 
> <img alt="image" width="409" src="https://user-images.githubusercontent.com/78047794/177589912-93045724-e9c5-4596-8892-62c64b4ee566.png">

@george-hadfield That same layout is used for `Issues` and `Groups` Cards as well. 
![image](https://user-images.githubusercontent.com/43547703/179183674-b6c01461-6358-450e-9b89-584f05df2609.png)
Should I change them as well?

2022-07-15 08:23 UTC, Amantini1997 commented
> Move "this field is required" text for Safetibase title to the right
> 
> <img alt="image" width="409" src="https://user-images.githubusercontent.com/78047794/177589912-93045724-e9c5-4596-8892-62c64b4ee566.png">

@george-hadfield That same layout is used in `Issues` and `Groups` Cards as well. 
![image](https://user-images.githubusercontent.com/43547703/179183674-b6c01461-6358-450e-9b89-584f05df2609.png)
Should I change them as well?

2022-07-15 09:41 UTC, Amantini1997 commented
/azp run

2022-07-18 12:31 UTC, george-hadfield commented
> > Move "this field is required" text for Safetibase title to the right
> > <img alt="image" width="409" src="https://user-images.githubusercontent.com/78047794/177589912-93045724-e9c5-4596-8892-62c64b4ee566.png">
> 
> @george-hadfield That same layout is used in `Issues` and `Groups` Cards as well. ![image](https://user-images.githubusercontent.com/43547703/179183674-b6c01461-6358-450e-9b89-584f05df2609.png) Should I change them as well?

Yes please

2022-07-19 08:50 UTC, sanmont3drepo approved these changes

2022-07-19 09:38 UTC, The-Daniel approved these changes

2022-07-19 09:39 UTC, merged