ISSUE #3504 - Revert viewer navbar opacity
3drepo/3drepo.io pull request #3507
Opened 2022-08-08 14:28 UTC by The-Daniel

This fixes #3504 

#### Description
- Navbar is now fully opaque
- Viewer canvas does not extand behind navbar
- Exit focus mode button is now clickable (it turns out this wasn't a result of the change to the navbar and must have existed beforehand #3457)

#### Test cases
- Open the viewer
- Open windows
- Turn on the memory settings
- Open focus mode

2022-08-10 16:29 UTC, sanmont3drepo requested changes

2022-08-10 16:29 UTC, sanmont3drepo commented on frontend/src/v5/ui/components/shared/appBar/appBar.styles.ts
> -`;
This is how its looking in this pr
<img width="968" alt="image" src="https://user-images.githubusercontent.com/42032433/183962415-0721a5b8-4f96-4bb6-91b3-c24a6a61f7e5.png">

2022-08-10 16:29 UTC, sanmont3drepo commented on frontend/src/v5/ui/components/legal/LegalLayout/legalAppBar/legalAppBar.component.tsx
> +	<MuiAppBar position="static">
I think this creates the printing bug

2022-08-10 16:29 UTC, sanmont3drepo commented on frontend/src/v5/ui/components/shared/appBar/appBar.component.tsx
> +		<MuiAppBar position="static">
check out printing

2022-08-10 16:29 UTC, sanmont3drepo commented on frontend/src/v5/ui/components/dashboard/dashboardViewerLayout/dashboardViewerLayout.component.tsx
>  import { ThemeProvider } from 'styled-components';
I think you can delete this one

2022-08-10 16:32 UTC, The-Daniel commented on frontend/src/v5/ui/components/shared/appBar/appBar.styles.ts
> -`;
Ah yeah...

2022-08-11 10:42 UTC, The-Daniel commented on frontend/src/v5/ui/components/dashboard/dashboardViewerLayout/dashboardViewerLayout.component.tsx
>  import { ThemeProvider } from 'styled-components';
deleted

2022-08-11 10:42 UTC, The-Daniel commented on frontend/src/v5/ui/components/legal/LegalLayout/legalAppBar/legalAppBar.component.tsx
> +	<MuiAppBar position="static">
fixed

2022-08-11 14:29 UTC, sanmont3drepo approved these changes

2022-08-11 14:54 UTC, merged