ISSUE #3494 - Add project store tests
3drepo/3drepo.io pull request #3530
Opened 2022-08-16 11:51 UTC by Amantini1997

This fixes #3494

#### Description
Rewritten project tests to remove redux unit tests in favour of integration tests

2022-08-17 14:30 UTC, sanmont3drepo requested changes

2022-08-17 14:30 UTC, sanmont3drepo commented on frontend/test/projects/projects.store.spec.ts
> +);
Maybe make this a helper function for all arrays that have objects with `{_id}` , like `containsId(arr, id)` and re use it in containers.

2022-08-18 09:30 UTC, sanmont3drepo approved these changes

2022-08-18 09:30 UTC, sanmont3drepo approved these changes

2022-08-18 11:22 UTC, sanmont3drepo approved these changes

2022-08-23 09:12 UTC, sanmont3drepo approved these changes

2022-08-23 09:17 UTC, The-Daniel approved these changes

2022-08-23 09:40 UTC, merged