ISSUE #3489 - Rewrite Redux and Selector tests:
3drepo/3drepo.io pull request #3539
Opened 2022-08-17 16:47 UTC by The-Daniel

This fixes #3489 

#### Description
- Add store test file which test both redux reducers and selectors
- Fix broken updateFederationSuccess reducer

2022-08-17 17:19 UTC, Amantini1997 commented on frontend/test/federations/federations.store.spec.ts
> +		expect(viewsFromState).toBe(mockViews);
According to the jest docs: `Use .toBe to compare primitive values or to check referential identity`, The tests still pass, but I think it's better to use `toEqual` which does a deep comparison when it comes to objects

2022-08-18 08:18 UTC, Amantini1997 requested changes

2022-08-18 08:18 UTC, Amantini1997 commented on frontend/test/federations/federations.store.spec.ts
> +		expect(viewsFromState).toBe(mockViews);
According to the jest docs: `Use .toBe to compare primitive values or to check referential identity`, The tests still pass, but I think it's better to use `toEqual` which does a deep comparison when it comes to objects

2022-08-18 08:47 UTC, Amantini1997 commented on frontend/test/federations/federations.store.spec.ts
> +		const federations = selectFederations(getState());
Just to let you know, https://github.com/3drepo/3drepo.io/pull/3532#discussion_r948155194
in this PR Santiago mentioned to test this kind of selector before populating the store. I may be worth it to add him to review this PR to see if he wants to request this change here too

2022-08-25 13:07 UTC, sanmont3drepo approved these changes

2022-08-25 14:25 UTC, merged