Issue 3466 - ProfilePasswordTab.component.tsx
3drepo/3drepo.io pull request #3542
Opened 2022-08-19 09:06 UTC by Amantini1997

This fixes #3466 

#### Description
Tabs are now unmounted and re-mounted on tab switch (previously they were just being hidden);
To achieve this, most of the logic of the single tabs was moved in the parent component (the `EditProfileModal`) and the `FormProvider` from react-hook-form was used to have the single tabs form-data persist on tab switch

The `UnhandledError` component supports an initial error (optional), and takes in a setter method (optional again) to set the error in the parent component to make it persistent.

2022-08-19 10:25 UTC, Amantini1997 commented
/azp run

2022-08-23 09:25 UTC, The-Daniel commented
![image](https://user-images.githubusercontent.com/62481250/186122551-6c52d684-85fd-442a-b6cf-fdf37bffb867.png)
Change password no longer works. The submit button isn't enabled

2022-08-23 09:28 UTC, The-Daniel commented
There's a weird double scroll effect when you successfully update your profile and the success message appears. Also the scrollbar takes up the entire height of the modal which isn't useful, but hopefully fixing the other problem will fix this

2022-08-23 10:02 UTC, sanmont3drepo requested changes

2022-08-23 15:35 UTC, Amantini1997 commented
> There's a weird double scroll effect when you successfully update your profile and the success message appears. Also the scrollbar takes up the entire height of the modal which isn't useful, but hopefully fixing the other problem will fix this

To separate that concern form the rest of the logic of this PR, this will be fixed as part of this issue https://github.com/3drepo/3drepo.io/issues/3570

2022-08-23 16:16 UTC, sanmont3drepo requested changes

2022-08-23 16:16 UTC, sanmont3drepo commented on frontend/src/v5/ui/routes/dashboard/projects/projectsList/createProjectModal/createProjectModal.component.tsx
> +} from '@controls/errorMessage/unhandledErrorInterceptor/unhandledErrorInterceptor.component';
```suggestion
import { UnhandledErrorInterceptor } from '@controls/errorMessage/unhandledErrorInterceptor/unhandledErrorInterceptor.component';
```

2022-08-23 16:51 UTC, sanmont3drepo approved these changes

2022-08-24 09:32 UTC, The-Daniel approved these changes

2022-08-24 16:24 UTC, sanmont3drepo approved these changes

2022-08-24 16:25 UTC, merged