Issue 3694 - move all login records into a single collection
3drepo/3drepo.io pull request #3714
Opened 2022-10-27 11:58 UTC by carmenfan

This fixes #3694

#### Description
- Login records are now stalled in `internal.loginRecords`
  - this collection stores all users login records, so the records now contain a property `user`
- Failed login attempts are now also recorded
- `lastLoginAt` is now removed from user's `customData`, we deduce this on the fly by looking at the latest login record instead
- Whether an account is locked is no longer stored as a flag - we deduce this on the fly by looking at the latest login record instead
- There is a migration script to migration all existing records to the new place
- Added a `initialiseSystem()` function which will ensure this collection is indexed at launch

#### Test cases
- logins should work as before
- a record should be stored if the user attempted to login and succeeded
- a record should be stored if the user attempted to login and failed
- Migration script should move all existing records over and delete the old collections

2022-11-03 19:08 UTC, ChristosTsiotsias requested changes

2022-11-08 13:35 UTC, carmenfan commented on backend/src/v4/handler/db.js
> +	Handler.createIndex = async (database, colName, indexDef, { runInBackground } = {}) => {
we could, but I wanted to keep it as a {} for options (what i want to do for things like find too going forward for things like limits, sort etc)

this is so you don't have to put load of `undefine`s inbetween the option you're trying to set.

2022-11-08 13:38 UTC, carmenfan commented on backend/src/v5/models/loginRecords.js
> +LoginRecords.saveLoginRecord = async (user, sessionId, ipAddress, userAgent, referer) => {
I'm just gonna rename it.

Merging it isn't ideal as one takes a session Id and the other doesn't

2022-11-08 13:45 UTC, carmenfan commented on backend/tests/v5/unit/models/loginRecords.test.js
> +	const callFunction = (user, id, ip, userAgent, ref) => (testFailed
the function calls in the if statement should be using `user` instead of `username`. fixed.

2022-11-09 10:48 UTC, merged