Issue 3627 - New ticket UI
3drepo/3drepo.io pull request #3731
Opened 2022-11-02 16:23 UTC by Amantini1997

This fixes #3627 

#### Description
Added dropdown menu to create a new ticket from template
Added button to cancel new ticket creation
Done some code cleaning for the the ActionMenu component

2022-11-03 12:45 UTC, Amantini1997 commented on frontend/src/v5/ui/routes/viewer/tickets/ticketsList/ticketsList.component.tsx
> +					<TemplateName
The filter chips in the ticket list card had a broken styling, so I just copied the previous style from the original branch and re-applied it here

2022-11-03 12:46 UTC, Amantini1997 commented on frontend/src/v5/ui/controls/actionMenu/actionMenu.component.tsx
> +	const MenuChildren = Children.toArray(children).map((child) => applyCloseMenuToActionMenuItems(child, handleClose));
Yes, that's exactly it

2022-11-03 14:31 UTC, The-Daniel commented on frontend/src/v5/ui/routes/viewer/tickets/ticketsList/ticketsList.component.tsx
> +					<TemplateName
The only broken styling I can see if the border colour and perhaps some spacing issues. It's probably best to keep the FilterChip component as this is what it was made for it just hasn't been reviewed by George yet

2022-11-04 11:24 UTC, Amantini1997 commented on frontend/src/v5/ui/routes/viewer/tickets/ticketsList/ticketsList.component.tsx
> +					<TemplateName
Ahhhhhh, my bad!

2022-11-04 11:40 UTC, sanmont3drepo requested changes

2022-11-04 11:40 UTC, sanmont3drepo commented on frontend/src/v5/ui/routes/viewer/tickets/ticketsList/ticketsListCard.component.tsx
> +const NewTicketMenu = () => {
Can you put this one in a separte file?

2022-11-04 12:09 UTC, merged