ISSUE #3779 - Fix Storybook components
3drepo/3drepo.io pull request #3785
Opened 2022-11-24 11:42 UTC by Amantini1997

This fixes #3779

#### Description
cleaned up stories

2022-11-24 14:41 UTC, The-Daniel requested changes

2022-11-24 14:41 UTC, The-Daniel commented on frontend/stories/buttons/Button.stories.tsx
> -Primary.args = {
Any reason the 'outlined' examples have been removed?
Also you've removed the 'label' and 'label-outlined' variants from the options, so once you change the variant of one of these you can't change back

2022-11-24 14:41 UTC, The-Daniel commented on frontend/stories/outputs/SuccessMessage.stories.tsx
>  			description: 'The text or component to display',
Should this include 'component'?

2022-11-28 10:27 UTC, The-Daniel approved these changes

2022-11-28 12:06 UTC, sanmont3drepo requested changes
There are some icons that doesnt show. I think is because the extension of these are `.svg` instead of `.svg.tsx`, nevertheless I think they should show up in the list:

<img width="815" alt="image" src="https://user-images.githubusercontent.com/42032433/204266420-b1ecf1ed-784a-4767-bacb-046b34cd7cd6.png">

2022-11-28 12:17 UTC, sanmont3drepo commented
> There are some icons that doesnt show. I think is because the extension of these are `.svg` instead of `.svg.tsx`, nevertheless I think they should show up in the list:
> 
> <img alt="image" width="815" src="https://user-images.githubusercontent.com/42032433/204266420-b1ecf1ed-784a-4767-bacb-046b34cd7cd6.png">

Ok, re tested it in my computer and it worked 🤷

2022-11-28 14:53 UTC, The-Daniel approved these changes

2022-11-28 15:26 UTC, merged