Issue 3808 4.28 release candidate
3drepo/3drepo.io pull request #3817
Opened 2022-12-08 11:07 UTC by carmenfan

This fixes #3808

#### Description
- Addresses all bugs recorded on the bug list

#### Test cases
- Bugs listed on the bug list should now be resolved
- All 4.28 features should function as expected

2022-12-08 11:07 UTC, carmenfan commented
/azp run

2022-12-08 11:46 UTC, carmenfan commented
/azp run

2022-12-08 13:15 UTC, sanmont3drepo requested changes

2022-12-08 13:15 UTC, sanmont3drepo commented on frontend/src/v4/modules/risks/risks.sagas.ts
>  		toggleMeasurementListeners(false);
Im worried about the listeners not being turned off here

2022-12-08 14:06 UTC, The-Daniel commented on frontend/src/v4/modules/measurements/measurements.sagas.ts
>  		toggleMeasurementListeners(false);
Good point. I don't think I saw that

2022-12-08 14:24 UTC, The-Daniel commented on frontend/src/v4/services/viewer/viewer.tsx
> +		if (!mode) {
I've readded it

2022-12-08 14:25 UTC, The-Daniel commented
/azp run

2022-12-08 15:38 UTC, miadibe commented
### Bug 1. Measurement Card activate/deactivate features

###Description 
Clicking on any measurement button (locate point, point to point, laser, min distance, surface area, custom surface area) activates the feature but does not deactivate it on second click

### Current behaviour 
Click once to activate the feature. Click again and button remains orange. 
![bug1](https://user-images.githubusercontent.com/56918163/206488903-03f9bedd-9557-46b7-8672-eabe0a2fe2ff.gif)

### Expected Behaviour
Click once to activate the feature (orange). Click again to deactivate it (grey). 
![expected1](https://user-images.githubusercontent.com/56918163/206489427-17d87b78-12c0-466c-bb50-7a17432cda92.gif)

2022-12-08 15:49 UTC, miadibe commented
### Bug 2. Measurement Card:  Min distance is not working as expected

###Description 
- Distance measurement shows that it is being calculated for the correct object selections (highlighted) but is actually not recorded or shown in the UI
- What happens instead is a multi-selection on single click highlighting every selected object

### Current behaviour
![bug2](https://user-images.githubusercontent.com/56918163/206493198-4fe6182d-bd2b-4668-8946-a17d1f5f5a02.gif)

### Expected behaviour
![expected2](https://user-images.githubusercontent.com/56918163/206492931-d6b92079-957d-4dd5-a70a-f62ec2894773.gif)

2022-12-08 16:07 UTC, mosment3DRepo commented
### Viewpoint should update screenshot 

**Current Behaviour**
When I created a new viewpoint it does not create a screenshot, so it needs to be added separately

https://user-images.githubusercontent.com/62879582/206498327-2d77c696-ea7f-4cec-a087-208c32f54d5d.mp4

**Expected Behaviour**
As with V4, when we create a viewpoint we should take a screenshot of the Unity window and attach it as the image.

When the viewpoint is updated it should ask if you also want to update the image, as per V4

2022-12-08 17:11 UTC, Amantini1997 commented
### In properties, delete Viewpoint should delete viewpoint

**Current Behaviour**
In any custom tickets, in the properties section (so not other modules), clicking "edit viewpoint > delete viewpoint" does not delete the viewpoint

**Expected Behaviour**
In any custom tickets, in the properties section (so not other modules), clicking "edit viewpoint > delete viewpoint" should delete the viewpoint

2022-12-08 17:11 UTC, sanmont3drepo commented
Updating a viewpoint screenshot doesnt work on the first try.
Repro steps: 
- Navigate to a federation in v5
- Open a issue with a viewpoint 
- Click on 'update viewpoint'
- Click on 'yes' after being asked if you want to create a new screenshot

What happens:
- The screenshot modal fails to appear
What should happen:
- The screenshot modal should appear

<img width="745" alt="image" src="https://user-images.githubusercontent.com/42032433/206518109-ee5493b7-b156-44d9-99ad-f0da2cf72ce6.png">

After failing if you try again the modal will appear.

2022-12-09 14:36 UTC, Amantini1997 submitted a review, later dismissed

2022-12-09 14:48 UTC, carmenfan commented
/azp run

2022-12-09 14:51 UTC, The-Daniel submitted a review, later dismissed

2022-12-09 15:10 UTC, sanmont3drepo approved these changes

2022-12-09 19:47 UTC, carmenfan commented
/azp run

2022-12-12 14:35 UTC, george-hadfield commented
### Notifications number is positioned incorrectly

Build
<img width="175" alt="image" src="https://user-images.githubusercontent.com/78047794/207070783-afcca8ab-a40a-4e8b-984a-b759633e7d6a.png">

Design
<img width="400" alt="image" src="https://user-images.githubusercontent.com/78047794/207072241-be5fb625-d990-473f-88ba-c359007b0859.png">

2022-12-12 15:51 UTC, george-hadfield commented
### Column title has dropped down in user permissions and project permissions

<img width="670" alt="image" src="https://user-images.githubusercontent.com/78047794/207090813-101d375c-2836-4df9-8b7f-1aded24dc573.png">

2022-12-12 15:57 UTC, george-hadfield commented
### Swap custom tickets icon with filled version

Existing
<img width="94" alt="image" src="https://user-images.githubusercontent.com/78047794/207092037-3732d736-1cb5-4764-a9a3-efcb9e02889a.png">

Updated
<img width="206" alt="image" src="https://user-images.githubusercontent.com/78047794/207092142-d02bed30-8e60-4d5e-a0be-c90dacbfb7ae.png">

Updated icon available here https://www.figma.com/file/3FjNEOdQbcHwzquVZxUqMl/3D-Repo?node-id=2011%3A15811&t=Z07108aC1WrBtM7R-1

2022-12-12 16:03 UTC, george-hadfield commented
### Arrows on custom ticket detail are way too big

Build
<img width="397" alt="image" src="https://user-images.githubusercontent.com/78047794/207093640-b3432de3-3372-4aed-b5ed-2fa67aa2554b.png">

Design
<img width="469" alt="image" src="https://user-images.githubusercontent.com/78047794/207093756-6fb0ac61-41a3-425d-934f-256f6a648d4a.png">

2022-12-12 16:05 UTC, george-hadfield commented
### Ticket shouldn't load with title field in focused state

Build
<img width="399" alt="image" src="https://user-images.githubusercontent.com/78047794/207094078-1839eb96-9af4-45ad-8aeb-039dc14edddd.png">

2022-12-12 16:05 UTC, george-hadfield commented
### Missing Safetibase icon inside Safetibase cards

<img width="403" alt="image" src="https://user-images.githubusercontent.com/78047794/207094368-c9537f8c-4f63-4d8b-9fb1-31fd34e83f1c.png">

2022-12-12 16:08 UTC, george-hadfield commented
### Gaps between action buttons at the top of cards

<img width="155" alt="image" src="https://user-images.githubusercontent.com/78047794/207094646-13e43fdc-48e7-4449-bbd5-7a1c032bf36e.png">
 
Buttons should align to the right with a gap of 5px

2022-12-12 16:23 UTC, george-hadfield commented
### Instant clash tab on compare tab should be on a single line

Build
<img width="391" alt="image" src="https://user-images.githubusercontent.com/78047794/207098452-cf97d39f-4672-47f1-8086-5972bba9d166.png">

2022-12-12 17:07 UTC, sanmont3drepo commented
> ### Notifications number is positioned incorrectly
> Build <img alt="image" width="175" src="https://user-images.githubusercontent.com/78047794/207070783-afcca8ab-a40a-4e8b-984a-b759633e7d6a.png">
> 
> Design <img alt="image" width="400" src="https://user-images.githubusercontent.com/78047794/207072241-be5fb625-d990-473f-88ba-c359007b0859.png">

This one will be fixed in https://github.com/3drepo/3drepo.io/pull/3783

2022-12-12 17:18 UTC, sanmont3drepo commented
> ### Ticket shouldn't load with title field in focused state
> Build <img alt="image" width="399" src="https://user-images.githubusercontent.com/78047794/207094078-1839eb96-9af4-45ad-8aeb-039dc14edddd.png">

Are you sure about this one? I might be wrong think we changed it by yours or Matt's request (@Amantini1997 ?)

2022-12-13 13:20 UTC, carmenfan commented
/azp run

2022-12-13 15:27 UTC, merged