ISSUE #3822 - UI fixes
3drepo/3drepo.io pull request #3840
Opened 2023-01-03 14:36 UTC by The-Daniel

This fixes #3822 

#### Description
- Fix size and position of chevrons when cycling between ticket details
- Add missing safetibase icon in safetibase card
- If a card action (buttons in top right of viewer card) is missing then there is no empty space
- Instant clash tab on compare tab is single line
- Changed hex value for BASE_LIGHTEST to match figma theme
- All custom ticket properties have the same border colour
- Tweak input styles to match figma more closely
- Error modal has a max-width
- Hovering over additional assignees circle lists ALL of the assignees, not just the overflow
- Reduced back arrow size in custom tickets
- when creating a new ticket the padding in the save ticket button is equal
- Added a space after each comma in the assignees input

#### Test cases
Ensure other inputs in the viewer do not have messed up styling

2023-01-03 15:19 UTC, The-Daniel commented
/azp run

2023-01-03 17:45 UTC, Amantini1997 commented
I'm not sure about this, but should the `0` be displayed?
![image](https://user-images.githubusercontent.com/43547703/210412196-5df1e050-d4fa-42e2-9631-c16ac0c4d938.png)

2023-01-03 18:22 UTC, The-Daniel commented
> I'm not sure about this, but should the `0` be displayed? ![image](https://user-images.githubusercontent.com/43547703/210412196-5df1e050-d4fa-42e2-9631-c16ac0c4d938.png)

Fixed with merge

2023-01-03 18:23 UTC, The-Daniel commented
/azp run

2023-01-05 15:25 UTC, sanmont3drepo submitted a review, later dismissed

2023-01-09 15:35 UTC, george-hadfield commented
"If a card action (buttons in top right of viewer card) is missing then there is no empty space"

Not sure if this is exactly what you meant but there's an unwanted empty space inside a safetibase risk as shown in screenshot here.. 

<img width="553" alt="image" src="https://user-images.githubusercontent.com/78047794/211346181-8d0efc5f-afdf-44d1-bab2-62b0a660a422.png">

2023-01-09 15:40 UTC, george-hadfield commented
"Reduced back arrow size in custom tickets"

Size is fine but the alignment is off. Can the arrow please be positioned in the same position as the custom ticket icon one tier up. As when you flick between the list and the ticket detail, there's a noticeable gap to the left of the arrow. Please ensure text moves to the left with the arrow.

<img width="456" alt="image" src="https://user-images.githubusercontent.com/78047794/211347266-7589b84d-e4fa-452c-a821-3dfa771b49bf.png">

2023-01-09 15:44 UTC, george-hadfield commented
### Padding or margin is too big on assignees tooltip

Please can make these values the same for assignees tooltip and new ticket options

If you click 'New ticket' you will see the correct spacing as shown below
<img width="227" alt="image" src="https://user-images.githubusercontent.com/78047794/211348162-ec9aaf2d-74d9-43c7-898b-d862e07dfc6f.png">

Compare that to the assignees tooltip and you'll notice the excessive left spacing shown below
<img width="308" alt="image" src="https://user-images.githubusercontent.com/78047794/211348312-776d408b-7f58-43e0-a946-5ba8f469c5a4.png">

2023-01-09 15:47 UTC, george-hadfield commented
### Remove background hover state on custom ticket list

<img width="457" alt="image" src="https://user-images.githubusercontent.com/78047794/211348725-71aabdc8-e5ce-4a26-8358-cc674b164d83.png">

Please keep the pointer on hover though and the underline when hovering the title. This request is just for the backgrond.

2023-01-09 15:47 UTC, george-hadfield requested changes
A few small tweaks

2023-01-09 16:52 UTC, The-Daniel commented
/azp run

2023-01-09 17:12 UTC, The-Daniel commented
@george-hadfield I've noticed that selected buttons in the bottom toolbar use a color from the V4 palette.
![image](https://user-images.githubusercontent.com/62481250/211366660-2859c509-d8ed-41da-bb5b-ad3391f7605b.png)
Would you like me to change this to something like FAVOURITE_MAIN?

2023-01-10 17:21 UTC, george-hadfield commented
> @george-hadfield I've noticed that selected buttons in the bottom toolbar use a color from the V4 palette. ![image](https://user-images.githubusercontent.com/62481250/211366660-2859c509-d8ed-41da-bb5b-ad3391f7605b.png) Would you like me to change this to something like FAVOURITE_MAIN?

Please use primary.main instead

2023-01-11 12:56 UTC, george-hadfield requested changes
A few small tweaks then all good!

2023-01-11 13:10 UTC, george-hadfield submitted a review, later dismissed

2023-01-11 16:27 UTC, Amantini1997 requested changes

2023-01-11 16:27 UTC, Amantini1997 commented on frontend/src/v5/ui/v4Adapter/overrides/cards/compare.overrides.ts
> +		white-space: nowrap;
I think might as well be added to the general theme

2023-01-11 16:27 UTC, Amantini1997 commented on frontend/src/v5/ui/v4Adapter/overrides/cards/safetiBase/safetiBase.overrides.ts
> +			border: 1px solid ${({ theme }) => theme.palette.base.lightest};
Same comment as above 
![image](https://user-images.githubusercontent.com/43547703/211856334-670a2070-254c-427a-9398-4c740f76914d.png)

2023-01-11 16:27 UTC, Amantini1997 commented on frontend/src/v5/ui/v4Adapter/overrides/cards/issues/properties.overrides.ts
> +				border: 1px solid ${({ theme }) => theme.palette.base.lightest};
This one also override the border-color when the dropdown is selected 
![image](https://user-images.githubusercontent.com/43547703/211856259-b6decb8f-3202-44b6-bbcd-c8f902418229.png)

2023-01-12 10:52 UTC, The-Daniel commented
/azp run

2023-01-12 15:56 UTC, Amantini1997 approved these changes

2023-01-18 20:15 UTC, sanmont3drepo approved these changes

2023-01-18 20:33 UTC, merged