Issue 3757 - V5 Kanban Board
3drepo/3drepo.io pull request #3844
Opened 2023-01-04 15:59 UTC by Amantini1997

This fixes #3757 

#### Description
Import Kanban board in v5 and re-style it

#### Test cases
- Create new Issue/Risk
- Edit Issue/Risk (double click on the card)
- Open model in viewer from kanban board card
- Open model in viewer from edit modal

2023-01-05 13:53 UTC, Amantini1997 commented
/azp run

2023-01-05 15:05 UTC, sanmont3drepo commented
The clone button doesnt look good:

<img width="356" alt="image" src="https://user-images.githubusercontent.com/42032433/210811566-e50a899e-0a42-4aac-95b4-83f78034599d.png">

2023-01-05 17:14 UTC, The-Daniel requested changes

2023-01-05 17:25 UTC, sanmont3drepo commented
/azp run

2023-01-05 17:41 UTC, Amantini1997 commented on frontend/src/v5/ui/routes/dashboard/projects/board/board.styles.ts
> +export const Container = styled.div`
I see your point, but I think in this case it is fine. With the viewer, we are not importing the components, rather we are creating a common wrapper that re-styles all of them. here, we are not in the viewer though and the component is specifically re-imported with some props passed to it.

I would prefer to keep the styling next to tbh, but let's also see what's @sanmont3drepo 's opinion about this

2023-01-05 17:45 UTC, The-Daniel commented on frontend/src/v5/ui/routes/dashboard/projects/board/board.styles.ts
> +export const Container = styled.div`
https://github.com/3drepo/3drepo.io/pull/3797#discussion_r1047458255
This is what he said when I did the same

2023-01-05 19:55 UTC, sanmont3drepo commented
> The clone button doesnt look good:
> 
> <img alt="image" width="356" src="https://user-images.githubusercontent.com/42032433/210811566-e50a899e-0a42-4aac-95b4-83f78034599d.png">

The  changes created additional scroillbars:

<img width="335" alt="image" src="https://user-images.githubusercontent.com/42032433/210868486-68493870-8bf8-4e7f-9420-b667199b50a5.png">

Maybe we could just change 'clone issue'  to clone

2023-01-06 10:39 UTC, Amantini1997 commented
/azp run

2023-01-06 17:11 UTC, The-Daniel commented
Should the issues and risks buttons in container/federations lists take you to the relevant board now?
![image](https://user-images.githubusercontent.com/62481250/211061934-5482ec57-f7dc-4f63-b387-dbe02bd299d6.png)
Also is this what the tasks tab was supposed to be, and do we need to remove that now? I don't see it in the figma mockup
![image](https://user-images.githubusercontent.com/62481250/211062547-fc793874-b3b9-45fc-8097-deb9f44d7617.png)

2023-01-06 17:17 UTC, mosment3DRepo commented
> Should the issues and risks buttons in container/federations lists take you to the relevant board now? ![image](https://user-images.githubusercontent.com/62481250/211061934-5482ec57-f7dc-4f63-b387-dbe02bd299d6.png) Also is this what the tasks tab was supposed to be, and do we need to remove that now? I don't see it in the figma mockup ![image](https://user-images.githubusercontent.com/62481250/211062547-fc793874-b3b9-45fc-8097-deb9f44d7617.png)

Agreed, but I think that should be a separate issue as it's not release limiting for this bit

2023-01-06 17:20 UTC, Amantini1997 commented
> Should the issues and risks buttons in container/federations lists take you to the relevant board now? ![image](https://user-images.githubusercontent.com/62481250/211061934-5482ec57-f7dc-4f63-b387-dbe02bd299d6.png) Also is this what the tasks tab was supposed to be, and do we need to remove that now? I don't see it in the figma mockup ![image](https://user-images.githubusercontent.com/62481250/211062547-fc793874-b3b9-45fc-8097-deb9f44d7617.png)

@mosment3DRepo Is the `Issues and risks` tab supposed to replace the `Tasks` one?

2023-01-06 17:34 UTC, The-Daniel commented
On creating a new issue the scrollbar is in the wrong layer. This means you can scroll the header and footer out of view
![image](https://user-images.githubusercontent.com/62481250/211065816-5af8409f-1743-42a4-a6fa-d92f7c095f42.png)

2023-01-06 17:38 UTC, carmenfan commented
> @mosment3DRepo Is the `Issues and risks` tab supposed to replace the `Tasks` one?

Tasks should be renamed to tickets and reserved for custom tickets in the future i think... I think we should minimise the linkage to the issue & risks kanban board so when we tear it out it isn't too intertwined.. would prefer it to be only accessible through the `X Risks` and `X Issues` button and the hamburger button only...

Ultimately it's @mosment3DRepo's call

2023-01-09 15:52 UTC, The-Daniel commented
> On creating a new issue the scrollbar is in the wrong layer. This means you can scroll the header and footer out of view ![image](https://user-images.githubusercontent.com/62481250/211065816-5af8409f-1743-42a4-a6fa-d92f7c095f42.png)

This issue still seems to exist

2023-01-10 14:24 UTC, george-hadfield commented
### Move empty text to centre of board (vertically) and change styling

Change typography to H2 and colour to base.main

<img width="1782" alt="image" src="https://user-images.githubusercontent.com/78047794/211576709-4ef405c4-1dd4-4bde-b34b-155005e12355.png">

2023-01-10 14:25 UTC, george-hadfield commented
### Make single selects disabled until Fed or Con is selected

Ensure disabled styling is applied

<img width="406" alt="image" src="https://user-images.githubusercontent.com/78047794/211576899-f6fb42ff-4f22-4b27-854c-94f585e668b4.png">

2023-01-10 14:26 UTC, george-hadfield commented
### Change circle button to primary button with icon

If this is possible it would be great to implement

Build
<img width="458" alt="image" src="https://user-images.githubusercontent.com/78047794/211577060-379fbc34-6076-4550-9d61-a6f3decdd12a.png">

Design
<img width="239" alt="image" src="https://user-images.githubusercontent.com/78047794/211577149-17195b58-6cd6-40e2-845e-80aa9c7d761c.png">

2023-01-10 14:35 UTC, george-hadfield commented
### Update single select styling for Fed/Con selection

Build
<img width="465" alt="image" src="https://user-images.githubusercontent.com/78047794/211579416-2bbfd5be-8cff-4d6d-8f3b-135748585727.png">

Design
https://www.figma.com/file/3FjNEOdQbcHwzquVZxUqMl/3D-Repo?node-id=2386%3A15321&t=7zr6gSmpmEaLdPGr-1
<img width="337" alt="image" src="https://user-images.githubusercontent.com/78047794/211579490-7a067d9a-7f7d-4344-b4d7-60d70d5d440a.png">

2023-01-10 14:38 UTC, george-hadfield commented
### Ensure border colour for issues/risk cards in list match the border colour for Feds and Containers
Correct border colour: rgb(224, 229, 240) (not sure which this is in palette)

Build
<img width="435" alt="image" src="https://user-images.githubusercontent.com/78047794/211580184-5a897d05-36a7-4bb8-b281-24f1bb533939.png">

2023-01-10 14:40 UTC, george-hadfield commented
### Add a few more pixels to the spacing around the column headers

Build
<img width="1746" alt="image" src="https://user-images.githubusercontent.com/78047794/211580588-be1118cc-3126-4e50-8862-4fc9665f8218.png">

Design
<img width="1509" alt="image" src="https://user-images.githubusercontent.com/78047794/211580642-1a15cc00-d458-448c-a832-982946ace46e.png">

2023-01-10 14:40 UTC, george-hadfield commented
### Increase space between each column to 15px

Build
<img width="1720" alt="image" src="https://user-images.githubusercontent.com/78047794/211580794-d94b3d74-289a-43c0-af22-f72a232450d1.png">

Design
<img width="1508" alt="image" src="https://user-images.githubusercontent.com/78047794/211580857-206daf3f-619e-4641-bbe5-e5d56440bf73.png">

2023-01-10 14:43 UTC, george-hadfield commented
### View on modal icon disappears on hover
I would remove the icon completely and just rely on users clicking the issue to open the modal

Build
<img width="481" alt="image" src="https://user-images.githubusercontent.com/78047794/211581423-1125de85-cb43-4074-b7cb-4f763fe9e44c.png">

2023-01-10 14:44 UTC, george-hadfield commented
### If a column has 0 issues, make the styling of '0 Issues' disabled

Build
<img width="432" alt="image" src="https://user-images.githubusercontent.com/78047794/211581759-75004117-1f86-4dd3-82e0-26337dc41ff8.png">

2023-01-10 14:46 UTC, george-hadfield commented
### Make the modal have a minimum height
Use the height of properties as the minimum

<img width="907" alt="image" src="https://user-images.githubusercontent.com/78047794/211582146-68460545-1d9e-4f7e-a8ce-f1c9a5e61125.png">

2023-01-10 14:57 UTC, george-hadfield commented
### Reduce spacing between single select and empty comments box

<img width="438" alt="image" src="https://user-images.githubusercontent.com/78047794/211584928-1b7e68c6-4ffb-4592-accb-f47769df51b0.png">

2023-01-10 15:00 UTC, george-hadfield commented
### Increase internal column spacing to 13px

Build
<img width="432" alt="image" src="https://user-images.githubusercontent.com/78047794/211585794-3283b112-4f8a-48df-9413-89990db7bf51.png">


Design
<img width="480" alt="image" src="https://user-images.githubusercontent.com/78047794/211585747-74b69ade-d4ad-4170-acfc-823f74ddfb44.png">

2023-01-10 15:04 UTC, george-hadfield commented
### Add droppable state to columns
 Use teal focus used on inputs

<img width="562" alt="image" src="https://user-images.githubusercontent.com/78047794/211586571-a751db2c-d996-42f0-ae8c-9e04a8fedd60.png">

2023-01-10 15:04 UTC, george-hadfield requested changes
Comments left

2023-01-11 12:04 UTC, Amantini1997 commented
/azp run

2023-01-11 12:26 UTC, Amantini1997 commented
> ### Add droppable state to columns
> Use teal focus used on inputs
> 
> <img alt="image" width="562" src="https://user-images.githubusercontent.com/78047794/211586571-a751db2c-d996-42f0-ae8c-9e04a8fedd60.png">

The library we use to create a kanban board (`react-trello`) claims to allow this kind of customisation, but unfortunately it doesn't seem to work. I looked for conversations about it on forum threads, but there is not much

2023-01-11 12:46 UTC, george-hadfield commented
### Remove white border form new issue button

<img width="174" alt="image" src="https://user-images.githubusercontent.com/78047794/211809774-9603220d-6203-4a52-92f8-9d5d17312576.png">

2023-01-11 12:47 UTC, george-hadfield commented
### Ensure disable single selects use the correct v5 disabled styling

Build
<img width="361" alt="image" src="https://user-images.githubusercontent.com/78047794/211809883-745788ff-f1bc-47e6-86d0-fdb08532dca5.png">

Design (https://www.figma.com/file/3FjNEOdQbcHwzquVZxUqMl/3D-Repo?node-id=1597%3A14377&t=fJVAy2IEYbLsCSa4-1)
<img width="523" alt="image" src="https://user-images.githubusercontent.com/78047794/211809988-423e887f-b07a-403c-975c-67ba63e8f84b.png">

2023-01-11 12:51 UTC, george-hadfield commented
### Reduce padding for titles in Fed and Con select menu
Change bottom padding from 17px to 8px as shown in the screenshot below. This should be applied to both Federations and Containers titles.

<img width="460" alt="image" src="https://user-images.githubusercontent.com/78047794/211810842-becc65dd-a683-4b49-91ac-cfb7fe5f2f3c.png">

2023-01-11 12:53 UTC, george-hadfield commented
### Remove background colour from Fed and Con selection menu
also remove top spacing (currently the white area above the blue background)

Build
<img width="508" alt="image" src="https://user-images.githubusercontent.com/78047794/211811189-9460785f-0b58-4139-a1f4-5a252b675fc2.png">

Design
<img width="440" alt="image" src="https://user-images.githubusercontent.com/78047794/211811270-adb069e7-9a5e-4852-8098-623c1edebb55.png">

2023-01-11 12:54 UTC, george-hadfield commented
### Add 5px top-padding to column titles
Currently 0 padding set on this element. Please replicate what's shown in the screenshot below

<img width="529" alt="image" src="https://user-images.githubusercontent.com/78047794/211811505-5527571d-c206-40fc-98ac-e808cdb0b4ef.png">

2023-01-12 12:02 UTC, Amantini1997 commented
/azp run

2023-01-13 11:50 UTC, The-Daniel requested changes

2023-01-13 11:50 UTC, The-Daniel commented on frontend/src/v5/ui/v4Adapter/dialogs/boardDialogs.overrides.ts
> +				/* margin-top: 0; */
This can be deleted

2023-01-13 15:29 UTC, george-hadfield commented
### Change padding-bottom to 15px on column headers

<img width="445" alt="image" src="https://user-images.githubusercontent.com/78047794/212357177-ecf38e73-7e84-47c8-a479-bbcd0ef06246.png">

2023-01-13 15:31 UTC, george-hadfield requested changes
One final change

2023-01-16 09:25 UTC, Amantini1997 commented
/azp run

2023-01-17 15:52 UTC, The-Daniel submitted a review, later dismissed

2023-01-18 20:55 UTC, sanmont3drepo requested changes

2023-01-18 20:55 UTC, sanmont3drepo commented on frontend/src/v5/ui/v4Adapter/components/conditionalV5OrViewerScrollArea.component.tsx
> +export const ConditionalV5OrViewerScrollArea = forwardRef(({ children, ...props }: ScrollbarProps, ref: any) => {
I dont get why renaming this one :/

2023-01-19 19:23 UTC, sanmont3drepo approved these changes

2023-01-24 19:52 UTC, sanmont3drepo approved these changes

2023-01-24 20:26 UTC, sanmont3drepo commented
/azp run

2023-01-25 10:20 UTC, The-Daniel approved these changes

2023-01-25 11:26 UTC, george-hadfield approved these changes

2023-01-25 11:50 UTC, merged