Issue 3829 - merged general container/federation endpoints
3drepo/3drepo.io pull request #3848
Opened 2023-01-05 18:08 UTC by carmenfan

This fixes #3829

#### Description
- merged general container/federation functions
- fixed some bugs identified

#### Test cases
- functions should work as before
- swagger should make sense

2023-01-13 03:56 UTC, ChristosTsiotsias requested changes

2023-01-13 03:56 UTC, ChristosTsiotsias commented on backend/tests/v5/unit/middleware/dataConverter/outputs/teamspaces/projects/models/commons/modelSettings.test.js
> +				expect(respondFn.mock.calls.length).toBe(nextIdx + 1);
you could use toHaveBeenCalledTimes

2023-01-13 03:56 UTC, ChristosTsiotsias commented on backend/tests/v5/unit/middleware/dataConverter/outputs/teamspaces/projects/models/commons/modelSettings.test.js
> +				expect(respondFn.mock.calls[nextIdx][2]).toEqual(templates.ok);
you could use toHaveBeenCalledWith

2023-01-13 03:56 UTC, ChristosTsiotsias commented on backend/tests/v5/e2e/routes/teamspaces/projects/models/common/general.test.js
> +					expect(res.body.code).toEqual(expectedOutput.code);
we could also check that the model is indeed added to the favourites

2023-01-13 03:56 UTC, ChristosTsiotsias commented on backend/tests/v5/e2e/routes/teamspaces/projects/models/common/general.test.js
> +					url += `${firstParam ? '?' : '&'}key=${key}`;
firstParam will always be true so maybe we can simplify that

2023-01-13 03:56 UTC, ChristosTsiotsias commented on backend/tests/v5/e2e/routes/teamspaces/projects/models/common/general.test.js
> +					expect(res.body.code).toEqual(expectedOutput.code);
we could verify that the models are no longer favourites

2023-01-13 03:56 UTC, ChristosTsiotsias commented on backend/tests/v5/e2e/routes/teamspaces/projects/models/common/general.test.js
> +describe('E2E routes/teamspaces/projects/federations', () => {
the name should be updated

2023-01-18 10:57 UTC, carmenfan commented on backend/src/v5/middleware/dataConverter/inputs/teamspaces/projects/models/containers.js
> +		const query = { $or: [{ 'subModels.model': container }, { subModels: container }] };
yes, @charence is addressing it in #3845 and he should be removing these workarounds there 😋

2023-01-18 10:59 UTC, carmenfan commented on backend/src/v5/middleware/dataConverter/outputs/teamspaces/projects/models/commons/modelSettings.js
> +		if (outputData.lastUpdated) outputData.lastUpdated = outputData.lastUpdated.getTime();
we could, but this literally does the same thing other than it wouldn't stick an `undefined` on a field that doesn't exist, which I personally don't really like

Why do you prefer the other way?

2023-01-19 11:46 UTC, ChristosTsiotsias approved these changes

2023-01-20 12:11 UTC, merged