Issue 3827
3drepo/3drepo.io pull request #3853
Opened 2023-01-06 16:44 UTC by Amantini1997

This fixes #3827 

#### Description
Fixed text overflow in a few places
P.S. look how cool the breadcrumbs behaves like now!!

2023-01-09 12:09 UTC, The-Daniel requested changes

2023-01-09 12:09 UTC, The-Daniel commented on frontend/src/v5/ui/v4Adapter/overrides/cards/compare.overrides.ts
> +		text-overflow: ellipsis;
I think this needs a `white-space: nowrap;`
![image](https://user-images.githubusercontent.com/62481250/211303756-60108f17-0011-4d93-add6-397604f6d3f5.png)

2023-01-09 12:12 UTC, The-Daniel commented
![image](https://user-images.githubusercontent.com/62481250/211304860-daf40f72-42a9-41e5-8a6f-824caa16cdbb.png)
It's possible to make the author name wrap onto multiple lines and flow outside its containers

2023-01-09 14:32 UTC, Amantini1997 commented
> ![image](https://user-images.githubusercontent.com/62481250/211307176-5a9a05c6-dc18-4806-ad8b-c5b7a0cc4b2d.png) Latest revision in the uploads model destination autocomplete might need truncation

> ![image](https://user-images.githubusercontent.com/62481250/211305425-764b241d-9516-4c62-8c74-f7a4ba8306f4.png)
Ticket names don't truncate

I added both of these to the main issue list

2023-01-09 14:53 UTC, Amantini1997 commented on frontend/src/v5/ui/components/dashboard/dashboardList/dashboardListItem/components/dashboardListItemRow/dashboardListItemRow.styles.ts
> +			border: solid 2px red;
Ah yes, indeed

2023-01-09 15:15 UTC, Amantini1997 commented on frontend/src/v5/ui/routes/viewer/groups/groupItem/groupItem.styles.ts
> +	min-width: 30px;
@mosment3DRepo

2023-01-09 16:00 UTC, Amantini1997 commented on frontend/src/v5/ui/components/dashboard/dashboardList/dashboardListItem/components/dashboardListItemTitle/dashboardListItemTitle.styles.ts
> +		max-width: 100%;
Let's wait to see what @sanmont3drepo says

2023-01-11 16:22 UTC, The-Daniel requested changes

2023-01-11 16:22 UTC, The-Daniel commented on frontend/src/v5/ui/routes/dashboard/projects/containers/uploadFileForm/uploadList/uploadListItem/components/uploadListItemTitle/uploadListItemTitle.styles.ts
>  	}
![image](https://user-images.githubusercontent.com/62481250/211859638-aa2c43b1-ca64-48ab-9a7f-126d29c48e2e.png)
The latest revision is still not truncated (In the destination input of the upload file modal)

2023-01-12 17:08 UTC, The-Daniel submitted a review, later dismissed

2023-01-17 13:37 UTC, sanmont3drepo commented on frontend/src/v5/ui/components/dashboard/dashboardList/dashboardListItem/components/dashboardListItemTitle/dashboardListItemTitle.styles.ts
> +		max-width: 100%;
> I remember it being discussed whether text overflow css should be moved to the theme. Or perhaps we should be making use of the TextOverflow control?

Lets keep it for now this way.

2023-01-17 19:29 UTC, sanmont3drepo commented
In the viewer the breadcrumbs are missing the ellipsis
<img width="948" alt="image" src="https://user-images.githubusercontent.com/42032433/212994228-40ac19df-c171-4e75-bfe1-559b14cd71e4.png">

2023-01-18 14:47 UTC, sanmont3drepo approved these changes

2023-01-18 14:59 UTC, sanmont3drepo approved these changes

2023-01-18 15:36 UTC, merged