Issue 3063 - Too many modal when trying to access inaccessible model
3drepo/3drepo.io pull request #3873
Opened 2023-01-16 09:55 UTC by Amantini1997

This fixes #3063

#### Description
When the URL contains wrong segments (like a wrong teamspace/project/resource id) or the user is trying to access a teamspace they do not have access to, such a user is going to be redirected:
- teamspace id is wrong (or not accessible) -> the user will be redirected to the dashboard;
- project id is wrong -> the user will be redirected to the teamspace page;
- resource id is wrong -> the user will be redirected to the project page.

#### Test cases
Access a model in the viewer and try to change the URL segment once for each of the following:
- teamspace;
- project;
- federation/container;
You should get redirected as described above

Then try the same in the dashboard (excluding the federation/container as that bit will not be in the URL)

2023-01-16 09:55 UTC, Amantini1997 commented
/azp run

2023-01-16 11:40 UTC, The-Daniel requested changes

2023-01-16 11:40 UTC, The-Daniel commented on frontend/src/v5/store/dialogs/dialogs.redux.ts
> +	// avoid opening 2+ redirect modals
This causes a crash when a modal doesn't contain an error. For instance the confirm delete, upload files, and revision still processing info modals.

2023-01-17 09:36 UTC, Amantini1997 commented
/azp run

2023-01-17 13:38 UTC, mosment3DRepo approved these changes

2023-01-17 15:45 UTC, The-Daniel approved these changes

2023-01-23 19:06 UTC, sanmont3drepo commented
/azp run

2023-01-25 18:35 UTC, sanmont3drepo approved these changes

2023-01-25 18:36 UTC, merged