ISSUE #3802 - multiline helper-text doesn't overlap input
3drepo/3drepo.io pull request #3875
Opened 2023-01-16 10:39 UTC by Amantini1997

This fixes #3802

#### Description
The error helper text used to overlap with the input it spanned over multiple lines. This PR fixes that

#### Test cases
Open container/federation settings and type `$` inside `code`

2023-01-16 11:50 UTC, The-Daniel requested changes

2023-01-16 11:50 UTC, The-Daniel commented on frontend/src/v5/ui/themes/theme.ts
> +					top: 55,
This causes in large inputs, such as custom tickets description boxes, pins, viewpoints, and images
![image](https://user-images.githubusercontent.com/62481250/212671143-cc11a74e-9845-4ea3-9b39-9e531ab96ca3.png)

2023-01-17 10:36 UTC, Amantini1997 commented
/azp run

2023-01-17 15:32 UTC, The-Daniel approved these changes

2023-01-18 14:11 UTC, sanmont3drepo approved these changes

2023-01-18 14:25 UTC, merged