Issue 3860 - Create a v5 version of mongo handler
3drepo/3drepo.io pull request #3890
Opened 2023-01-18 10:41 UTC by carmenfan

This fixes #3860

#### Description
- v5 db handler no longer relies on v4 db  handler
- added driver tests for all functionality
- no longer expose `runCommand`

#### Test cases
all v5 functionality should function as before

2023-01-19 16:37 UTC, ChristosTsiotsias requested changes

2023-01-19 16:37 UTC, ChristosTsiotsias commented on backend/tests/v5/drivers/handler/db.test.js
> +		test('Should return empty array if collection doesn\'t exist', async () => {
return undefined*

2023-01-19 16:37 UTC, ChristosTsiotsias commented on backend/tests/v5/drivers/handler/db.test.js
> +		test('Should return empty array if database doesn\'t exist', async () => {
return undefined*

2023-01-20 11:30 UTC, carmenfan commented on backend/tests/v5/unit/models/roles.test.js
> +			const fn = jest.spyOn(db, 'dropRole').mockImplementation(() => { });
I don't disagree, I didn't write the tests (these are old tests before we knew better) I just changed the function name 😆

2023-01-24 13:16 UTC, ChristosTsiotsias approved these changes

2023-01-24 13:48 UTC, merged