Issue 3914 - SSO improvements
3drepo/3drepo.io pull request #3927
Opened 2023-01-30 15:43 UTC by carmenfan

This fixes #3914

#### Description
- All `*-post` routes (routes that are called by MS authenticator) are now a `HTTP POST` route so data can be stored within a body
- CSRF token is now enforced in the MS authenticator workflow to ensure it's the same session making it
- State is now hashed into a string so it's not obvious what the data is from the URL

#### Test cases
- the workflow should function like before

2023-02-01 13:49 UTC, ChristosTsiotsias requested changes

2023-02-01 13:49 UTC, ChristosTsiotsias commented on backend/tests/v5/e2e/routes/sso/aad/aad.test.js
> +		test(`1234should redirect with ${errorCodes.EMAIL_EXISTS} if email is taken by another user`, async () => {
same

2023-02-01 15:08 UTC, carmenfan commented on backend/tests/v5/e2e/routes/sso/aad/aad.test.js
> +		test('1234should redirect and add error to the query if email already exists', async () => {
haha yup I added it so I can just run that test without copy and pasting a load of stuff 😆

2023-02-07 13:43 UTC, ChristosTsiotsias approved these changes

2023-02-07 13:50 UTC, merged