ISSUE 3850 - Move notifications to internal DB
3drepo/3drepo.io pull request #3938
Opened 2023-02-02 13:35 UTC by Charence

This fixes #3850 

#### Description
- Migration script to move existing notifications
- Create indices
- Backend updated to read/write notifications from notifications DB

#### Test cases
- Should work as before

2023-02-06 15:14 UTC, carmenfan requested changes
I don't know where it needs to be, but you need something to convert the `Date` back to timestamp when we send it out as a response to an endpoint

2023-02-07 14:55 UTC, Charence commented on backend/src/scripts/migrations/5.2/moveNotificationsToInternal.js
> +		updateOne: {
I did this as I ran the script multiple times during testing. I can change it `insertMany` if we're only going to run it once.

2023-02-07 14:58 UTC, Charence commented on backend/src/v4/models/notification.js
> +		// TODO this exists in v5
After discussion last time, I'll remove this comment as we'll handle notifications backend v5 migration separately.

2023-02-07 15:04 UTC, carmenfan commented on backend/src/scripts/migrations/5.2/moveNotificationsToInternal.js
> +		updateOne: {
if you do a collection at a time, then you just have to do an insert many and drop collection

so in theory, you shouldn't run into index problems, furthermore, if you do, we shouldn't be doing an update, we should just ignore it (as it means it has been migrated)

2023-02-09 12:32 UTC, carmenfan requested changes

2023-02-09 12:32 UTC, carmenfan commented on backend/src/scripts/migrations/5.2/moveNotificationsToInternal.js
> +	const updatedNotifications = (await find(NOTIFICATIONS_DB, user, {})).map((entry) => ({
Probably better to do this
```suggestion
	const updatedNotifications = (await find(NOTIFICATIONS_DB, user, {})).map(({timestamp, ...entry}) => ({
```

2023-02-09 12:32 UTC, carmenfan commented on backend/src/v4/models/notification.js
> +		Object.assign(notification, {timestamp: new Date(notification.timestamp).getTime(), modelName: name, federation: federate, project: (modelToProject[notification.teamSpace] ?? {})[notification.model
I think you can just do this? Unless i'm missing something there shouldn't be a situation where the timestamp is not a Date object?

```suggestion
		Object.assign(notification, {timestamp: notification.timestamp.getTime(), modelName: name, federation: federate, project: (modelToProject[notification.teamSpace] ?? {})[notification.modelId]});
```

2023-02-13 10:42 UTC, carmenfan approved these changes

2023-02-13 10:42 UTC, merged