Issue 3923 memory leak fixes
3drepo/3drepo.io pull request #3945
Opened 2023-02-06 10:54 UTC by carmenfan

This fixes #3929

#### Description
- ensure all services are cleaned up after test so `--forceExit` is no longer necessary on all tests
  - make v4 queue and db handler use v5's connection
  - make an async version of creating express app
- some fixes on tests due to the change above
- wipe data on database after every e2e test group

#### Test cases
tests should still pass as before
Memory seems to stablise 
![image](https://user-images.githubusercontent.com/11945337/216953305-fbe1c109-ed3a-42f5-890e-3c7d3de38ef3.png)

2023-02-22 16:09 UTC, ChristosTsiotsias requested changes

2023-02-24 13:07 UTC, carmenfan commented on backend/tests/v5/unit/models/loginRecords.test.js
> +			expect(DBHandler.deleteMany).toHaveBeenCalledTimes(1);
same as above

2023-02-24 13:07 UTC, carmenfan commented on backend/tests/v5/unit/models/loginRecords.test.js
> -			const fn = jest.spyOn(db, 'findOne').mockResolvedValueOnce(undefined);
same

2023-02-24 13:07 UTC, carmenfan commented on backend/tests/v5/unit/models/modelSettings.test.js
> -			const fn = jest.spyOn(db, 'insertOne');
ditto 😆

2023-02-24 13:08 UTC, carmenfan commented on backend/tests/v5/unit/utils/quota.test.js
> +	DBHandler.findOne.mockImplementation((ts, col, { _id }) => {
This is serving every single tests within the group 
![image](https://user-images.githubusercontent.com/11945337/221186438-7d99e532-c00f-4a9d-ad47-85b05768cd75.png)

2023-02-24 20:58 UTC, ChristosTsiotsias approved these changes

2023-03-01 15:18 UTC, merged