Issue 3904 - Signup with SSO
3drepo/3drepo.io pull request #4016
Opened 2023-02-27 14:00 UTC by sanmont3drepo

This fixes #3904 

#### Description
- Supports SSO signup with Microsoft
- Some design changes in the singup pages (logo on the left in login pages)

#### Test cases
- Try signing up with sso and  a already existing username
- Try signing up with sso and a already existing email
- Try signing up with sso with a non existing username/email

2023-02-27 15:15 UTC, sanmont3drepo commented
/azp run

2023-02-28 12:50 UTC, Amantini1997 requested changes

2023-02-28 12:50 UTC, Amantini1997 commented on frontend/src/v5/ui/routes/userSignup/userSignupSidebar/userSignupSidebar.component.tsx
> +				defaultMessage="Sign up with microsoft"
I think Microsoft should be capitlised

2023-02-28 12:55 UTC, Amantini1997 commented
When I try to signup, if I am already logged in with an SSO, I get logged in to that signed in user and I don't get the chance to sign up

2023-02-28 13:07 UTC, sanmont3drepo commented
> When I try to signup, if I am already logged in with an SSO (userSSO), I get logged in as userSSO and I don't get the chance to sign up. I am not sure what is the expected process here, but I don't seem to see this ![image](https://user-images.githubusercontent.com/43547703/221860175-247a6f6a-c761-4e18-b7db-e8cb72a59533.png)

This is when you already have a account with 3drepo (same email) but is not SSO.

2023-02-28 14:19 UTC, carmenfan commented
> > When I try to signup, if I am already logged in with an SSO (userSSO), I get logged in as userSSO and I don't get the chance to sign up. I am not sure what is the expected process here, but I don't seem to see this ![image](https://user-images.githubusercontent.com/43547703/221860175-247a6f6a-c761-4e18-b7db-e8cb72a59533.png)
> 
> This is when you already have a account with 3drepo (same email) but is not SSO. Maybe it should do the same with an existing username right now it says that the username has already been taken).
> 
> What do you think @carmenfan ?

yes agree

2023-02-28 16:24 UTC, sanmont3drepo commented on frontend/src/v5/ui/routes/userSignup/userSignupSidebar/userSignupSidebar.styles.ts
> +export const NewSticker = styled.div`
TBH is not, the border radius changes, the border width changes, the padding changes. If I use the chip in the end would be the same, wont be able to reuse any of the styles.
Also this label is supossed to be removed in the in the following deploy after the next.

2023-02-28 17:01 UTC, sanmont3drepo commented on frontend/src/v5/ui/routes/login/loginSSO.component.tsx
> +	if (!searchParams.get('loginPost')) {
That creates a lint error
<img width="650" alt="image" src="https://user-images.githubusercontent.com/42032433/221924517-af5a633d-4be0-44c4-b749-c094991496cc.png">

2023-03-01 09:21 UTC, george-hadfield commented
### Can the error message be displayed?
After trying to signup using SSO and providing an existing username, there is no error message, just the Username text and icon turns red.

<img width="541" alt="image" src="https://user-images.githubusercontent.com/78047794/222096654-d9146b82-57ae-4b46-bf54-4308eb015413.png">

2023-03-01 09:30 UTC, george-hadfield commented
### The width of the box is different to design
Also the spacing between the elements if off. Worth checking against the design again

<img width="785" alt="image" src="https://user-images.githubusercontent.com/78047794/222098880-8f0ac533-6d05-4600-9dd9-47add52fe29b.png">

2023-03-01 09:36 UTC, george-hadfield commented
### Incorrect font colour and weight

Currently using base.main but should be secondary.main. The font is one weight too heavy also

<img width="338" alt="image" src="https://user-images.githubusercontent.com/78047794/222100444-070cc9e3-c4f1-431e-8678-6b57038ceac2.png">

2023-03-01 09:43 UTC, george-hadfield commented
### Next step button incorrectly positioned

<img width="186" alt="image" src="https://user-images.githubusercontent.com/78047794/222102121-575de6a3-8c0a-4660-94d9-9fba6a63ce49.png">


The margin should be bigger below the button not above

2023-03-01 09:44 UTC, george-hadfield commented
### Change font weight of accordion headers to 400 (currently 600)

<img width="549" alt="image" src="https://user-images.githubusercontent.com/78047794/222102450-bfd809d8-a44c-4592-94ea-d0d8f4817ce3.png">

2023-03-01 09:54 UTC, george-hadfield commented
### Can't sign up using SSO

[screen-capture (5).webm](https://user-images.githubusercontent.com/78047794/222104956-8ce6c02b-8f73-489b-9817-05984523df47.webm)

2023-03-01 09:55 UTC, george-hadfield requested changes
Some initial changes before I can review again

2023-03-01 11:29 UTC, sanmont3drepo commented on frontend/src/v5/ui/routes/userSignup/userSignupSidebar/userSignupSidebar.styles.ts
> +	${({ theme }) => theme.typography.h1};
The problem is that you cant be consistent with that. I mean, we have "variants" that are not supported by Typography. In any case would make a Typography or similar component and add all variants. Maybe in this case would change the component style to div, as having it as Typography adds nothing.

2023-03-01 12:01 UTC, sanmont3drepo commented
> ### Can the error message be displayed?
> After trying to signup using SSO and providing an existing username, there is no error message, just the Username text and icon turns red.
> 
> <img alt="image" width="541" src="https://user-images.githubusercontent.com/78047794/222096654-d9146b82-57ae-4b46-bf54-4308eb015413.png">

This was discussed here; to keep consistency
https://github.com/3drepo/3drepo.io/pull/4016#issuecomment-1448262535

2023-03-01 12:26 UTC, sanmont3drepo commented
> ### Change font weight of accordion headers to 400 (currently 600)
> <img alt="image" width="549" src="https://user-images.githubusercontent.com/78047794/222102450-bfd809d8-a44c-4592-94ea-d0d8f4817ce3.png">

Are you sure? in figma says 500

2023-03-01 16:23 UTC, sanmont3drepo commented
/azp run

2023-03-01 16:24 UTC, sanmont3drepo commented
/azp run

2023-03-01 17:34 UTC, Amantini1997 commented
Previously, it was possible to move across the completed steps by clicking on the step title, now it seems only the first step is reachable this way 

https://user-images.githubusercontent.com/43547703/222217654-7d5d20be-b446-4274-988d-2896e27f8084.mp4

2023-03-01 17:39 UTC, Amantini1997 commented
When you already have an account signed up, you get this 
![image](https://user-images.githubusercontent.com/43547703/222218435-fe70f414-a75a-4aaf-a0d7-947e45923c57.png)

Should I not get to that page right after clicking this button (as opposed to first fill in the form and then trying to sign up)?
![image](https://user-images.githubusercontent.com/43547703/222218642-4985b8f0-2196-4bda-bf1d-b7a7c63b163f.png)

2023-03-01 17:42 UTC, Amantini1997 commented
(in incognito mode)
I tried to create an account using an already existing username and I still get redirected to the Microsoft sso page. Should I not be intercepted before reaching that far and get the error about the username already existing?

2023-03-02 09:29 UTC, sanmont3drepo commented
> When you already have an account signed up, you get this ![image](https://user-images.githubusercontent.com/43547703/222218435-fe70f414-a75a-4aaf-a0d7-947e45923c57.png)
> 
> Should I not get to that page right after clicking this button (as opposed to first fill in the form and then trying to sign up)? ![image](https://user-images.githubusercontent.com/43547703/222218642-4985b8f0-2196-4bda-bf1d-b7a7c63b163f.png)

Nope, you need to go through the SSO process to get that one, you cant know first hand, it depends on the email and username that you filled in

2023-03-02 09:31 UTC, sanmont3drepo commented
> (in incognito mode) I tried to create an account using an already existing username and I still get redirected to the Microsoft sso page. Should I not be intercepted before reaching that far and get the error about the username already existing?

That is discussed here
https://github.com/3drepo/3drepo.io/pull/4016#issuecomment-1448262535

2023-03-02 10:55 UTC, Amantini1997 approved these changes

2023-03-02 12:21 UTC, carmenfan commented
/azp run

2023-03-07 16:21 UTC, george-hadfield commented
### Change body margin-botton to 15px

Currently set at 5px this needs to be 15px.

<img width="975" alt="image" src="https://user-images.githubusercontent.com/78047794/223483847-3cff946c-6272-48a5-aa45-f687191136e4.png">

2023-03-07 16:24 UTC, george-hadfield requested changes
2 changes

2023-03-08 10:31 UTC, sanmont3drepo commented
/azp run

2023-03-09 11:12 UTC, Amantini1997 approved these changes

2023-03-09 12:45 UTC, george-hadfield approved these changes

2023-03-09 12:53 UTC, merged