Issue 3879 - Refactor Button.component.tsx
3drepo/3drepo.io pull request #4023
Opened 2023-02-28 17:48 UTC by Amantini1997

This fixes #3879

#### Description
The `Label` variant was extracted and is an independent button.
The style (which was redundant as already defined in the theme) has been remove.

#### Test cases
Go around the UI both in V4 and V5

2023-03-03 15:10 UTC, sanmont3drepo requested changes

2023-03-07 12:54 UTC, Amantini1997 commented on frontend/src/v5/ui/v4Adapter/overrides/invitationsList.overrides.ts
> +import { secondaryButtonStyling } from '../resuableOverrides.styles';
The file itself is still being used, but the bit (`secondaryButtonStyling`) that was moved into `re-usable overrides` can be deleted

2023-03-07 14:35 UTC, The-Daniel approved these changes

2023-03-07 14:35 UTC, The-Daniel commented on frontend/src/v5/ui/v4Adapter/resuableOverrides.styles.ts
> +export const primaryButtonStyling = css`
Just a thought. Do you think it's worth using these in the V4 overrides where we've 'hacked' in a button? e.g. userList.overrides FloatingButton. 

I'm thinking it's probably not worth it as these are temporary patches before the realV5 components are added, and ultimately it only clears up a few lines

2023-03-08 11:55 UTC, sanmont3drepo approved these changes

2023-03-08 15:33 UTC, sanmont3drepo approved these changes

2023-03-08 15:44 UTC, The-Daniel approved these changes

2023-03-09 10:05 UTC, merged