ISSUE #4123 - UI Tweaks and Issues
3drepo/3drepo.io pull request #4151
Opened 2023-04-03 12:50 UTC by The-Daniel

This fixes #4123 

#### Description
- Changed the border radius of several lists
- Change the border radius of the bottom bar in the viewer
- The notification button now just shows a colour dot when you have an unread notification. It no longer shows the number of notifications
- Removed the large buttons that appear at the bottom of the dashboard lists and jobs list

2023-04-04 09:41 UTC, Amantini1997 requested changes

2023-04-04 09:41 UTC, Amantini1997 commented on frontend/src/v4/routes/jobs/jobs.component.tsx
>  	name: 'Job name',
At line 165, you can get rid of `openNewJobForm`. That was introduced for the bottom button and only used by that

2023-04-04 10:15 UTC, The-Daniel commented
/azp run

2023-04-04 12:54 UTC, Amantini1997 approved these changes

2023-04-04 13:40 UTC, george-hadfield commented
### Add 5px border radius to Teamspace images

<img width="340" alt="image" src="https://user-images.githubusercontent.com/78047794/229811175-c05f5050-6651-4eed-998e-8c456ba0e1e4.png">

2023-04-06 13:58 UTC, The-Daniel commented
/azp run

2023-04-11 08:32 UTC, george-hadfield commented
### Add underline to 'Add new Teamspace'

<img width="344" alt="image" src="https://user-images.githubusercontent.com/78047794/231102980-9313848d-ef7e-4f48-be68-5ea5054056eb.png">

2023-04-11 08:34 UTC, george-hadfield commented
### Change number on accordion titles to be inside a circle
Change this containers also. Please add this functionality to project selection.

<img width="186" alt="image" src="https://user-images.githubusercontent.com/78047794/231103305-43caf075-9b93-4b35-b07d-a306a322919a.png">

Link to design: https://www.figma.com/file/3FjNEOdQbcHwzquVZxUqMl/3D-Repo?node-id=3433%3A32163&t=1RzH7W1GKqCgiDhk-1

2023-04-11 08:37 UTC, Amantini1997 commented
I think we should also remove the border in user/project permissions
![image](https://user-images.githubusercontent.com/43547703/231102986-64f0c8cb-9ea8-496f-8fb5-2fb2c1fd470d.png)

2023-04-11 08:37 UTC, george-hadfield commented
### Change border-radius on logo container on Project Selection screen 

Change to 25px

<img width="324" alt="image" src="https://user-images.githubusercontent.com/78047794/231104274-31f6d332-853a-4784-9f57-56fe2444ab86.png">

2023-04-11 08:39 UTC, george-hadfield commented
### Update font size below Teamspace title on Project selection screen
Please change to 12px body

<img width="381" alt="image" src="https://user-images.githubusercontent.com/78047794/231104780-1f037ddc-ca57-4398-bef4-46d50a18b745.png">

2023-04-11 08:43 UTC, Amantini1997 commented
The border-radius missed the colour picker modal 
![image](https://user-images.githubusercontent.com/43547703/231105617-a039ecf3-b84a-433d-a9ee-60e31d4d1e8e.png)

2023-04-11 08:45 UTC, george-hadfield commented
### Set minimum width for Teamspace menu to 200px

Make the same for Federations and Containers

<img width="349" alt="image" src="https://user-images.githubusercontent.com/78047794/231106020-ff396e43-7d96-4bfa-ab69-67e3a3130c44.png">

2023-04-11 08:46 UTC, george-hadfield commented
### Change accordion buttons to rounded squares rather than circles

<img width="328" alt="image" src="https://user-images.githubusercontent.com/78047794/231106345-1e20c9cd-d66c-4fd6-98ad-bd81d9795f44.png">

Link to design: https://www.figma.com/file/3FjNEOdQbcHwzquVZxUqMl/3D-Repo?node-id=3433%3A32163&t=1RzH7W1GKqCgiDhk-1

2023-04-11 08:49 UTC, george-hadfield requested changes
Quite a few comments and change

2023-04-11 08:55 UTC, george-hadfield commented
### Make sure all the padding around the dashed empty states in the viewer are consistent

<img width="434" alt="image" src="https://user-images.githubusercontent.com/78047794/231108440-ef7b4acd-cc5b-4ece-a4cd-801cf7ffee64.png">

The custom tickets one is correct. The ones I can see are incorrect are:

- Issues
- Safetibase
- Views
- Tree
- Compare
- Sequences
- Measurements

2023-04-11 09:00 UTC, george-hadfield commented
### Update bottom-toolbar to attached design

<img width="625" alt="image" src="https://user-images.githubusercontent.com/78047794/231110075-9711dfee-77e8-44ad-83fb-15edf60bd83e.png">

2023-04-11 09:10 UTC, george-hadfield commented
### Ensure all button padding is correct

Incorrect example
<img width="127" alt="image" src="https://user-images.githubusercontent.com/78047794/231112745-c6cc183e-eeee-4c37-9da0-bbcffa0288aa.png">

Correct padding
https://www.figma.com/file/3FjNEOdQbcHwzquVZxUqMl/3D-Repo?node-id=3223%3A36635&t=1RzH7W1GKqCgiDhk-1

2023-04-11 09:43 UTC, Amantini1997 requested changes

2023-04-11 09:43 UTC, Amantini1997 commented on frontend/src/v5/ui/components/shared/linkCard/teamspaceCard/teamspacePlaceholderCard/teamspacePlaceholderCard.styles.ts
> +export const DisableHoverState = styled.div`
If inside the `LinkCard` component you pass the `className` prop to the `CardListItem` component, you can get rid of `DisableHoverState`

2023-04-11 09:57 UTC, Amantini1997 commented
I think you need to fix the storybook component for the link card ![image](https://user-images.githubusercontent.com/43547703/231120997-195abf16-bff1-465a-9fa0-1054acf188bc.png)

2023-04-12 10:52 UTC, The-Daniel commented
/azp run

2023-04-12 14:25 UTC, george-hadfield commented
> ### Add underline to 'Add new Teamspace'
> <img alt="image" width="344" src="https://user-images.githubusercontent.com/78047794/231102980-9313848d-ef7e-4f48-be68-5ea5054056eb.png">

Underline not showing

2023-04-12 14:26 UTC, george-hadfield commented
> ### Change border-radius on logo container on Project Selection screen
> Change to 25px
> 
> <img alt="image" width="324" src="https://user-images.githubusercontent.com/78047794/231104274-31f6d332-853a-4784-9f57-56fe2444ab86.png">

Border radius still 10px

2023-04-12 14:36 UTC, The-Daniel commented
/azp run

2023-04-12 15:39 UTC, The-Daniel commented
![image](https://user-images.githubusercontent.com/62481250/231508730-3a437ab6-bc85-401b-8d83-b94760579c00.png)
![image](https://user-images.githubusercontent.com/62481250/231508909-bbf999cc-5a01-46be-9364-2c93a27989b5.png)

I've noticed the search selects in custom tickets take on the new search styling. What should it do @george-hadfield ?

2023-04-13 07:55 UTC, Amantini1997 commented
I have only just noticed this: the notification sidebar gets the new border-radius
![image](https://user-images.githubusercontent.com/43547703/231692204-e6c06011-d2ce-4175-bee0-9a312c586643.png)

2023-04-13 07:59 UTC, Amantini1997 commented
The dropdown paper inside another paper does not get the styling 
![image](https://user-images.githubusercontent.com/43547703/231693123-7e271f2e-3c27-4e53-98ed-8fb2e3428769.png)

2023-04-13 08:13 UTC, Amantini1997 commented
project permissions/user permissions tabs content is similar to the containers/federations list. Should they also get the outer border removed? 
![image](https://user-images.githubusercontent.com/43547703/231696301-7f53b8c8-cd77-4299-b296-13dc985da864.png)


> (The same goes for Jobs and Users, but the background around it is white, so I am just leaving this a note and not asking for changes )
![image](https://user-images.githubusercontent.com/43547703/231696673-77bbea23-6d1a-4c4a-b5f3-a88c7c3c1ee8.png)

2023-04-13 08:19 UTC, Amantini1997 commented
On hovering the items of the user menu, you can see that the border-radius is different from the button's 
![image](https://user-images.githubusercontent.com/43547703/231698436-7ab004e3-2443-4de1-aa7c-938d52675397.png)

Should they look alike?

2023-04-13 14:21 UTC, george-hadfield commented
**I've noticed the search selects in custom tickets take on the new search styling. What should it do @george-hadfield ?**

It should NOT have the new styling. Can you please revert back to old styling?

2023-04-13 14:22 UTC, george-hadfield commented
> On hovering the items of the user menu, you can see that the border-radius is different from the button's ![image](https://user-images.githubusercontent.com/43547703/231698436-7ab004e3-2443-4de1-aa7c-938d52675397.png)
> 
> Should they look alike?

Yes please update

2023-04-13 14:23 UTC, george-hadfield requested changes
A few changes

2023-04-13 14:34 UTC, george-hadfield commented
### Increase height of viewer inputs

Increase to 30px - currently 26px

2023-04-13 14:40 UTC, george-hadfield commented
### Primary.main stroke and glow is now missing from the focused state of inputs
Can this please be restored?

<img width="551" alt="image" src="https://user-images.githubusercontent.com/78047794/231795236-ee2b6668-bbae-485a-ade8-d1824c2b359f.png">

2023-04-13 14:56 UTC, The-Daniel commented
> ### Primary.main stroke and glow is now missing from the focused state of inputs
> Can this please be restored?
> 
> <img alt="image" width="551" src="https://user-images.githubusercontent.com/78047794/231795236-ee2b6668-bbae-485a-ade8-d1824c2b359f.png">

Do you mean on the search inputs? It looks okay on normal text inputs

2023-04-19 15:58 UTC, The-Daniel commented
/azp run

2023-04-19 16:18 UTC, carmenfan commented
@george-hadfield  @The-Daniel we should close this off asap - any new requests should go into the anew issue.

We need to focus on feature work for 5.4

2023-04-19 16:19 UTC, george-hadfield submitted a review, later dismissed

2023-04-24 10:49 UTC, Amantini1997 commented
Something happened to the breadcrumbs elements which are no longer aligned

**Staging:**
![image](https://user-images.githubusercontent.com/43547703/233975154-c4b0ea17-5113-48b6-9a3a-70ba096ab05f.png)

**Current branch:**
![image](https://user-images.githubusercontent.com/43547703/233975210-38b96702-e3e4-4ace-b54d-54bed8b08cd6.png)

2023-04-24 12:35 UTC, Amantini1997 commented
Should these 2 have the same border-radius? (top is 10 and bottom is 8)
> Feel free to move this to the next issue
![image](https://user-images.githubusercontent.com/43547703/233976701-1d058262-6f95-4aa4-9393-f1c7baf30445.png)

2023-04-24 12:38 UTC, Amantini1997 requested changes

2023-04-24 12:38 UTC, Amantini1997 commented on frontend/src/v4/routes/components/foldableMenu/foldableMenu.style.ts
> +	border-radius: ${isV5() ? '8px' : '0 2px 2px 0'};
Could you override this directly in v5 within `src\v5\ui\v4Adapter\dialogs\v4DialogsOverrides.styles.ts`?

2023-04-25 09:54 UTC, The-Daniel commented
/azp run

2023-04-27 09:23 UTC, Amantini1997 requested changes

2023-04-27 09:23 UTC, Amantini1997 commented on frontend/src/v4/routes/components/filterPanel/components/childMenu/childMenu.styles.ts
> +	/* border-radius: ${isV5() ? '8px' : '0 2px 2px 0'}; */
I think this is a left over

2023-04-27 13:11 UTC, keifgwinn commented
/azp run

2023-04-28 08:10 UTC, keifgwinn commented
/azp run

2023-04-28 13:33 UTC, carmenfan commented
/azp run

2023-05-02 10:45 UTC, Amantini1997 requested changes

2023-05-02 10:45 UTC, Amantini1997 commented on frontend/src/v4/routes/components/filterPanel/components/childMenu/childMenu.styles.ts
> +import { isV5 } from '@/v4/helpers/isV5';
I think this is a leftover

2023-05-02 10:45 UTC, Amantini1997 commented on frontend/src/v4/routes/components/foldableMenu/foldableMenu.style.ts
> +import { isV5 } from '@/v4/helpers/isV5';
leftover?

2023-05-02 10:45 UTC, Amantini1997 commented on frontend/src/v5/ui/components/shared/sso/microsoftButton.component.tsx
> -	border-radius: 0;
Removing the border-radius here means the MS button has rounded corners. I am not sure we should do this, did George specifically asked for this?

2023-05-02 10:45 UTC, Amantini1997 commented on frontend/src/v5/ui/controls/breadcrumbs/breadcrumbs.styles.ts
> +			height: 31px;
This fixes all the segments that are white, but no the highlighted one (the rightmost one) which still is a bit uplifted
![image](https://user-images.githubusercontent.com/43547703/235645956-64d436e9-d7a2-476f-8e12-daa14ecd80cb.png)

2023-05-03 16:30 UTC, Amantini1997 approved these changes

2023-05-04 09:27 UTC, The-Daniel commented
/azp run

2023-05-04 13:56 UTC, george-hadfield approved these changes

2023-05-05 14:31 UTC, merged