Issue 3814 - Use native CSS code to style scrollbar in chrome
3drepo/3drepo.io pull request #4157
Opened 2023-04-05 09:02 UTC by Amantini1997

This fixes #3814

#### Description
The library `react-custom-scrollbars` has been completely replace by native CSS code to style the scrollbars in V5

#### Test cases
Go around and test the different components that may user a scrollbar

2023-04-11 10:05 UTC, The-Daniel requested changes

2023-04-11 10:05 UTC, The-Daniel commented on frontend/src/v5/ui/v4Adapter/v4Overrides.styles.ts
GIS has a new border and you are able to scroll horizontally
![image](https://user-images.githubusercontent.com/62481250/231126962-e93a678c-c0b5-44b4-b207-b932a77b8765.png)

2023-04-11 10:25 UTC, The-Daniel commented on frontend/src/v5/ui/components/shared/revisionDetails/revisionDetails.styles.ts
![image](https://user-images.githubusercontent.com/62481250/231132663-13cffd0d-1236-48bc-ac12-aeb82c05c6dd.png)
The revisions list no longer has a scroll bar so the styling gets very weird and squished when the list gets long

2023-04-14 10:40 UTC, sanmont3drepo approved these changes

2023-04-14 10:41 UTC, merged