ISSUE #4102 - Make project name validation case insensitive
3drepo/3drepo.io pull request #4164
Opened 2023-04-06 09:05 UTC by Amantini1997

This fixes #4102

#### Description
Project name validation is now case insesitive

#### Test cases
Try to create (or edit) a project using the same name as an existing one, but with different casing

#### NOTES:
This issue requires a fix on the backend too, as such, it can't be tested correctly until that

2023-04-06 14:20 UTC, The-Daniel requested changes

2023-04-06 14:20 UTC, The-Daniel commented on frontend/src/v5/validation/shared/validators.ts
> +export const trimmedLowercaseString = trimmedString.transform((value) => value.toLocaleLowerCase());
This means that project names are now all lowercase. Is this what we want?

2023-04-06 14:20 UTC, The-Daniel commented on frontend/src/v5/validation/shared/validators.ts
> +export const trimmedLowercaseString = trimmedString.transform((value) => value.toLocaleLowerCase());
This change also means that the project settings behaves strangely.
If you change the name to be the same but with a different case then you get a success message although nothing actually changes
![image](https://user-images.githubusercontent.com/62481250/230405465-493e3f8e-b1f9-4a6a-9a89-94a2c0ca8861.png)
(image shows trying to rename 'all cap' -> 'ALL CAP'. The project name continues being 'all cap')

2023-04-26 10:07 UTC, The-Daniel approved these changes

2023-04-27 09:43 UTC, The-Daniel submitted a review, later dismissed

2023-04-27 10:37 UTC, sanmont3drepo requested changes

2023-04-27 10:37 UTC, sanmont3drepo commented on frontend/src/v5/ui/routes/dashboard/projects/projectsList/createProjectModal/createProjectModal.component.tsx
> +			setExistingNames((currentValue) => [...currentValue, getValues('projectName').toLocaleLowerCase()]);
This is not necessary, the comparison is already changing the case projectSchemes

2023-04-27 10:37 UTC, sanmont3drepo commented on frontend/src/v5/ui/routes/dashboard/projects/settingsModal/settingsModal.component.tsx
> +	const nameWasChanged = () => watch('name')?.trim() !== containerOrFederation.name;
nameWaschanged is not necessary.

2023-05-02 10:53 UTC, sanmont3drepo approved these changes

2023-05-02 13:09 UTC, merged