Issue 4153 - Color picker
3drepo/3drepo.io pull request #4204
Opened 2023-05-02 15:14 UTC by Amantini1997

This fixes #4153

#### Description
Added the color picker as a storybook component

#### Test cases
Navigate to the storybook section and play around with colours, opacity and the colour picker

2023-05-02 15:14 UTC, Amantini1997 commented
/azp run

2023-05-03 11:41 UTC, Amantini1997 commented
/azp run

2023-05-04 14:25 UTC, Amantini1997 commented on frontend/src/v5/ui/controls/inputs/colorPicker/colorPickerPalette/colorPickerPalette.styles.ts
I fixed both, but for the leading 0(s) problem I resorted to a slight hack, i.e. I converted the value to a string before passing it to the NumberField.
Due to a bug in React where the numbers "004" and "4" are the same, the component does not update correctly.

I wonder though, is it fine to have this hack?

2023-05-04 14:28 UTC, Amantini1997 commented
/azp run

2023-05-10 13:25 UTC, The-Daniel submitted a review, later dismissed

2023-05-11 11:59 UTC, sanmont3drepo commented
There is an inconsistency when selecting the colour. When I click out the of the display menu the input becomes unselected.
But when I click on the x it still selected. Both actions changes the colour

![selected](https://github.com/3drepo/3drepo.io/assets/42032433/4a05d0eb-27b8-4067-a2be-3a6e3b7464d7)

2023-05-11 13:45 UTC, sanmont3drepo commented
Changing the colours in storybook doesnt work or Im doing something wrong?
<img width="544" alt="image" src="https://github.com/3drepo/3drepo.io/assets/42032433/d44cc9f1-a02f-42ac-8123-0b806354800b">

2023-05-11 13:45 UTC, sanmont3drepo commented
Changing the colours in storybook doesnt work or Im doing something wrong?
<img width="544" alt="image" src="https://github.com/3drepo/3drepo.io/assets/42032433/d44cc9f1-a02f-42ac-8123-0b806354800b">

2023-05-11 14:07 UTC, sanmont3drepo requested changes

2023-05-11 14:07 UTC, sanmont3drepo commented on frontend/src/v5/ui/components/viewer/cards/tickets/pinDetails/pinDetails.component.tsx
> +		<CustomInput required={required} selected={editMode} error={error} disabled={disabled}>
Change this name to inputcontainer

2023-05-15 08:12 UTC, Amantini1997 commented
> Changing the colours in storybook doesnt work or Im doing something wrong? <img alt="image" width="544" src="https://user-images.githubusercontent.com/42032433/237688470-d44cc9f1-a02f-42ac-8123-0b806354800b.png">

It should be fixed now. In case it still seems to not be working, hit the **storybook refresh** button after changing the args
![image](https://github.com/3drepo/3drepo.io/assets/43547703/89e540e8-9526-48ac-9f7f-c902792cc4b7)

2023-05-18 14:08 UTC, sanmont3drepo approved these changes

2023-05-18 14:08 UTC, merged