Issue 4155 - Custom tickets:Groups smart groups filters control
3drepo/3drepo.io pull request #4217
Opened 2023-05-10 10:08 UTC by Amantini1997

This fixes #4155 

#### Description
Added the smart filter control.
The different options result in different layouts

#### Test cases
Navigate to the custom tickets list and click "add filters".
Test the different "operation" options

2023-05-11 15:20 UTC, sanmont3drepo commented
In the old control we highlight the matches:

<img width="353" alt="image" src="https://github.com/3drepo/3drepo.io/assets/42032433/8681754c-a7d7-4125-ac75-437ea804bdce">

This is this version:
<img width="364" alt="image" src="https://github.com/3drepo/3drepo.io/assets/42032433/9366f1d4-fd1f-4b5e-9ac5-8a9c03f0e69c">

2023-05-11 15:35 UTC, sanmont3drepo commented
In here should say "create filter" or "update filter" depending the case if its a new filter or altering an existing one

<img width="403" alt="image" src="https://github.com/3drepo/3drepo.io/assets/42032433/6441dcf4-3100-40e9-95f1-c8c6c2834b8c">

2023-05-11 15:37 UTC, sanmont3drepo commented
Is missing the filters list and the edit functionality

<img width="362" alt="image" src="https://github.com/3drepo/3drepo.io/assets/42032433/67629fc4-e17e-4aff-bb59-26b7b6aca630">

2023-05-17 13:52 UTC, sanmont3drepo requested changes

2023-05-17 13:52 UTC, sanmont3drepo commented on frontend/src/v5/ui/routes/viewer/tickets/ticketsList/ticketsList.component.tsx
> +			<GroupFiltersWithTriggerButton />
Can you rename this to `<GroupRules />` ?
Treat this as an Input, add `value` , 'onChange' props
That way when we use it in the group form is just another input that changes the rules of the group

2023-05-17 13:52 UTC, sanmont3drepo commented on frontend/src/v5/ui/routes/viewer/tickets/ticketsForm/ticketGroups/groups/groupFilters/groupFilters.component.tsx
> +		<FormProvider {...formData}>
dont use a form provider at this point, treat it as a regular input thing

2023-05-17 13:53 UTC, sanmont3drepo commented
Change the naming of the files in general from `filter` to `rule`

2023-05-17 14:03 UTC, sanmont3drepo requested changes

2023-05-17 14:03 UTC, sanmont3drepo commented on frontend/src/v5/ui/routes/viewer/tickets/ticketsList/ticketsList.component.tsx
> +			<GroupFiltersWithTriggerButton />
```
const handleOnChange = (value) => {
      group.rules = value;
}

<GroupRules  value={group.rules}  onChange={handleOnChange} />
```

2023-05-18 13:05 UTC, The-Daniel requested changes

2023-05-18 13:05 UTC, The-Daniel commented on frontend/src/v5/ui/routes/viewer/tickets/ticketsForm/ticketGroups/groups/groupFiltersForm/groupFiltersForm.component.tsx
The is an inconsistency in that when the Field select is open
![image](https://github.com/3drepo/3drepo.io/assets/62481250/e0964859-e11a-449d-985e-391db2b9f969)
and you click outside of the filters action menu, the action menu closes.
But if the Operations select is open and you click outside the action menu the select closes but the action menu remains open. I'm not sure if this is just because the Field select menu is empty, but I'd still expect it to act the same and not close the action menu

2023-05-23 08:25 UTC, Amantini1997 commented on frontend/src/v5/ui/routes/viewer/tickets/ticketsForm/ticketGroups/groups/groupFiltersForm/groupFiltersForm.component.tsx
I think this is the intended behaviour as the `Field` is not a select menu but an autocomplete. So this means that the options list should not prevent clicks or interactions outside of itself as the user should still be able to type in (or clear) the value. 
The same also happens with the uploadFile destination input, if you click outside the modal while the options list is open, you close the modal. I am not sure whether this should be fixed to be honest, @sanmont3drepo what do you think?

2023-05-26 09:52 UTC, The-Daniel commented on frontend/src/v5/ui/routes/viewer/tickets/ticketsForm/ticketGroups/groups/groupRulesForm/groupRulesForm.component.tsx
> +	rule?: IRule;
![image](https://github.com/3drepo/3drepo.io/assets/62481250/95bcccb3-1781-4453-9516-51f82d179f9d)

2023-05-30 09:13 UTC, Amantini1997 commented on frontend/src/v5/ui/controls/actionMenu/actionMenu.component.tsx
> +			onOpen?.();
I have done a pull rebase and I ended up having both without noticing

2023-05-30 10:01 UTC, Amantini1997 commented on frontend/src/v5/ui/routes/viewer/tickets/ticketsForm/ticketGroups/groups/groupRulesForm/ruleOperationSelect/ruleOperationSelect.component.tsx
> +		{/* Field */}
What do you mean by filter?

2023-05-31 13:48 UTC, The-Daniel approved these changes

2023-06-09 14:32 UTC, The-Daniel approved these changes

2023-06-12 14:26 UTC, sanmont3drepo approved these changes

2023-06-12 14:26 UTC, merged