ISSUE #4234 - Fix oneOf and manyOf crashing app for values of riskCategories and jobsAndUsers
3drepo/3drepo.io pull request #4247
Opened 2023-05-30 12:44 UTC by The-Daniel

This fixes #4234 

#### Description
- Stopped the app crashing when custom properties of a oneOf or manyOf type have the value riskCategories or jobsAndUsers
- jobsAndUsers custom properties now get the new assignees selects
- Fixed a bug where multi selects weren't showing their value

#### Test cases
- Use a template with these custom values (an example template is offered below)
- Change the values of all the different selects

<details><summary>Ticket template with all selects</summary>
<p>

```{
  "modules": [
    {
      "name": "Required selects",
      "deprecated": false,
      "properties": [
        {
      "type": "oneOf",
      "values": "jobsAndUsers",
      "name": "User/Job OneOf",
"required": true
    },
    {
      "type": "manyOf",
      "values": "jobsAndUsers",
      "name": "User/Job ManyOf",
"required": true
    },
    {
      "type": "oneOf",
      "values": "riskCategories",
      "name": "Risky OneOf",
"required": true
    },
    {
      "type": "manyOf",
      "values": "riskCategories",
      "name": "Risky ManyOf",
"required": true
    },
    {
      "type": "oneOf",
      "values": [
        "Space is the Place",
        "Discipline 33",
        "Rocket Number 9"
      ],
      "name": "Normal OneOf",
"required": true
    },
    {
      "type": "manyOf",
      "values": [
        "Space is the Place",
        "Discipline 33",
        "Rocket Number 9"
      ],
      "name": "Normal ManyOf",
"required": true
    }
       ]
    }
],
  "properties": [
    {
      "type": "oneOf",
      "values": "jobsAndUsers",
      "name": "User/Job OneOf"
    },
    {
      "type": "manyOf",
      "values": "jobsAndUsers",
      "name": "User/Job ManyOf"
    },
    {
      "type": "oneOf",
      "values": "riskCategories",
      "name": "Risky OneOf"
    },
    {
      "type": "manyOf",
      "values": "riskCategories",
      "name": "Risky ManyOf"
    },
    {
      "type": "oneOf",
      "values": [
        "Space is the Place",
        "Discipline 33",
        "Rocket Number 9"
      ],
      "name": "Normal OneOf"
    },
    {
      "type": "manyOf",
      "values": [
        "Space is the Place",
        "Discipline 33",
        "Rocket Number 9"
      ],
      "name": "Normal ManyOf"
    }
  ],
  "config": {
    "issueProperties": true
  },
  "code": "SEL",
  "name": "Selects"
}```

</p>
</details>

2023-05-30 15:50 UTC, Amantini1997 commented
This is a single select, but all the options have the checkbox, is this correct? 
![image](https://github.com/3drepo/3drepo.io/assets/43547703/61baeb11-1546-4c64-af54-97227a25badd)

2023-05-30 16:44 UTC, Amantini1997 requested changes

2023-05-30 16:44 UTC, Amantini1997 commented on frontend/src/v5/ui/controls/assigneesSelect/assigneesSingleSelect.component.tsx
Most of the code in this file is the same as "assigneesMultiSelect", the major differences I have seen are:
- the `value` (single vs multiple)
- the `multiple` flag
- some content
![Screenshot 2023-05-30 171145](https://github.com/3drepo/3drepo.io/assets/43547703/dad7edc9-ee2c-4a16-9c49-6bac3ec3a595)


Maybe some of the shared can be moved inside `assigneesSelectMenu`.

2023-05-30 16:44 UTC, Amantini1997 commented on frontend/src/v5/ui/controls/assigneesSelect/assigneesMultiSelect.component.tsx
> +	const filteredValue: string[] = intersection(value, allUsersAndJobs.map((i) => i.user || i._id)) ?? [];
`filteredValues` has been renamed and lost the `s` at the end, but it is an array, so I think the `s` good to indicate it was an collection

2023-05-31 13:45 UTC, The-Daniel commented
/azp run

2023-05-31 13:47 UTC, george-hadfield commented
> This is a single select, but all the options have the checkbox, is this correct? ![image](https://user-images.githubusercontent.com/43547703/242023396-61baeb11-1546-4c64-af54-97227a25badd.png)

You can have multiple users assigned though, so would need to visualise the previous selections

2023-05-31 13:49 UTC, george-hadfield commented
The one of functionality I have not discussed with anyone. Where has this feature come from?

2023-05-31 14:00 UTC, The-Daniel commented
@george-hadfield The oneOf functionality has been there from the start. This is just a custom oneOf (or manyOf) property where the values are 'jobsAndUsers' instead of an array of specified values. The same can be done for 'riskCategories'.

Before (when this issue's bug didn't happen) they looked like regular selects but I've added the new assignee select components. Partially out of ease since that component already exists now, and also because it condenses the information better than a default select. I should have run it by you first, let me know of any changes you'd like to be made

2023-06-01 14:35 UTC, The-Daniel commented
/azp run

2023-06-07 14:26 UTC, george-hadfield approved these changes

2023-06-09 15:15 UTC, sanmont3drepo approved these changes

2023-06-09 15:17 UTC, sanmont3drepo commented
/azp run

2023-06-12 15:27 UTC, Amantini1997 approved these changes

2023-06-13 13:12 UTC, merged