ISSUE #4190 - Shareable link for custom tickets
3drepo/3drepo.io pull request #4403
Opened 2023-08-11 14:23 UTC by The-Daniel

This fixes #4190

#### Description
Adds the ability to use the URL to share a custom ticket. The URL now contains a parameter "ticketId" when a custom ticket is open.

NOTE:  I have removed the selectedTickedId from the redux state as this resulted in multiple sources of truth for the ticketId. However the ticket pins required this (when you highlight an item in the ticket list and the pins change). So I have kept a state called 'highlightedTicketId' for this purpose

#### Test cases
Try sharing a link
Try sharing a link with an invalid ticket id
Check that the pins in the ticket list still work

2023-08-30 12:09 UTC, Amantini1997 commented
There is a problem with other viewer search params:
- Open the risks panel and expand one item;
- Open the tickets panel and expand one item;
- Click the back arrow in the risk panel (so clear the respective search param) and close the panel;
- Click the back arrow in the ticket panel.
The search param for the risk is set back and the risk panel is opened

https://github.com/3drepo/3drepo.io/assets/43547703/497c89c5-49fd-4b7b-bd5c-33ae89ad8ea1

2023-08-30 12:14 UTC, Amantini1997 commented
This is similar to the issue cited above (in the sense that it concerns the search params) but not the same.

When you expand an issue item, the respective id is added to the URL, the same goes for risks and tickets. At one point, it is possible to have one of each as a search params. This creates a glitch when one of the two open panels closes

Uploading Registrazione 2023-08-30 130821.mp4…

2023-08-30 13:14 UTC, Amantini1997 requested changes

2023-09-01 13:38 UTC, The-Daniel commented on frontend/src/v5/ui/routes/viewer/openTicketFromUrl/openTicketFromUrl.component.tsx
I've had a brief attempt at this method but it rand into methods in that it gets called before the initial fetchData which fetches the revisions. As such it opens the card details without having the ticket object and crashes. Whilst it should be possible to fix this in some way I don't want to add too much logic that depends on V4 and think it might be better to move away from the V4 code especially since it's a small file and could eventually be extended to handle all viewer search params

2023-09-01 17:13 UTC, The-Daniel commented on frontend/src/v5/ui/routes/viewer/tickets/ticketDetails/ticketsDetailsCard.component.tsx
> +	const ticket = tickets.find((t) => t._id === ticketId);
I tried this and unfortunately it doesn't work. The problem seems to be that it relies on the V4 selector `selectCurrentModel` which seems to not work on page render

2023-09-01 17:19 UTC, The-Daniel commented on frontend/src/v5/ui/routes/viewer/openTicketFromUrl/openTicketFromUrl.component.tsx
> +	}, [hasTicketData]);
It doesn't work for me which might be because I have a lot of tickets on the model I'm testing so it will take longer to load them.

2023-09-12 13:27 UTC, carmenfan commented
> When I repeat the same flow with a ticket, the ticketId search param is removed. Maybe the behaviour should be the same for both?

I think we want this behaviour over what's currently on v4 issue. That was very annoying when I use 3drepo and had issues that I closed the panel and it would reappear when I refresh

2023-09-26 15:18 UTC, Amantini1997 approved these changes

2023-09-26 15:18 UTC, merged