Issue 4359 - Tabular view: Group By
3drepo/3drepo.io pull request #4420
Opened 2023-08-29 09:12 UTC by Amantini1997

This fixes #4359 

#### Description
- Allow to group tickets by properties
- Refine URL search params
- Include "new ticket" in the group section
- Refactor selection page

#### Test cases
Group tickets by different group options

2023-08-29 14:47 UTC, The-Daniel requested changes

2023-08-29 14:47 UTC, The-Daniel commented on frontend/src/v5/ui/routes/dashboard/projects/tickets/ticketsTable/ticketsTableContent/ticketsTableGroup/ticketsTableRow/ticketsTableRow.component.tsx
> +				{!assignees?.length && (
![image](https://github.com/3drepo/3drepo.io/assets/62481250/419cb38e-ca98-42d8-bd5d-414c6df75bb3)
If the assignees is an empty array the component is prefaced by a "0". 

Also the ticket above doesn't have an assignees key in the ticket object (hence it doesn't have this problem). It is the same template, so this points to another problem in that I think the property isn't added to the redux state until it is edited.

2023-08-29 14:47 UTC, The-Daniel commented on frontend/src/v5/ui/routes/dashboard/projects/tickets/ticketsTable/ticketsTable.components.tsx
filename should be *component* not *components*

2023-08-29 14:47 UTC, The-Daniel commented on frontend/src/v5/ui/routes/dashboard/projects/tickets/ticketsTable/ticketsTableContent/ticketsTableGroup/ticketsTableGroup.component.tsx
> +type TicketTableGroupProps = {
Should probably be name TicketsTableGroupProps to match the component

2023-08-29 15:51 UTC, Amantini1997 commented on frontend/src/v5/store/tickets/tickets.selectors.ts
> +		const ticketsWithModelId: Array<ITicket & { modelId: string }> = containersAndFederationsIds.flatMap((modelId) => (
Good shout!

2023-08-30 11:14 UTC, The-Daniel reviewed
Just that one small change and I think I'm okay to approve

2023-08-30 15:41 UTC, merged