Issue 4358 - Ticket side panel
3drepo/3drepo.io pull request #4429
Opened 2023-09-04 09:53 UTC by Amantini1997

This fixes #4358

#### Description
Handle side panel with:
- Editing ticket;
- Creating new ticket (with/without default values);
- Prevent new ticket creation;
- Open in viewer button;
- Add realtime

#### Test cases
- Edit a ticket;
- Create a new ticket without default values;
- Create a new ticket with default values (that belong/do not belong to the template);
- Prevent new ticket creation when the template comes with required property that can only be set in the viewer;
- Open a ticket in the viewer; (this actually depends on #4190 so you should only see the `?ticketId` query param in the URL)
- Create a new ticket from the viewer in another tab and see it in the tabular view;
- Edit a ticket from the viewer in another tab and see it in the tabular view;

2023-09-04 09:54 UTC, Amantini1997 commented
/azp run

2023-09-04 15:06 UTC, george-hadfield commented
### Menu position for new ticket needs changing
The menu to select the Fed or cont when creating a new ticket from the last table row always appears centrally. Can it be moved to open next to where the user has clicked?

<img width="973" alt="image" src="https://github.com/3drepo/3drepo.io/assets/78047794/7b77a6b7-7ee6-4838-b386-0d6550d467dc">

2023-09-04 15:50 UTC, george-hadfield commented
### Reduce button padding

Reduce to standard padding size

<img width="188" alt="image" src="https://github.com/3drepo/3drepo.io/assets/78047794/69eb9c83-a6b1-4fae-b794-0b099c9e9ee6">

2023-09-06 10:41 UTC, Amantini1997 commented
/azp run

2023-09-06 15:33 UTC, Amantini1997 commented
/azp run

2023-09-07 09:52 UTC, Charence commented
/azp run

2023-09-07 11:14 UTC, george-hadfield approved these changes

2023-09-11 16:05 UTC, The-Daniel requested changes

2023-09-13 13:37 UTC, Amantini1997 commented on frontend/src/v5/ui/routes/dashboard/projects/tickets/ticketsList/slides/ticketSlide.component.tsx
I have done it on purpose to avoid changing something and you lose all the data. @carmenfan what do you think?

2023-09-13 13:56 UTC, carmenfan commented on frontend/src/v5/ui/routes/dashboard/projects/tickets/ticketsList/slides/ticketSlide.component.tsx
hmmm not sure, I think there's an element of ambiguity there. 

So if let's say I selected `model A`, opened the ticket panel and started creating a new ticket, without saving it, I changed the model selection to `model B` then saved the ticket, does that belong to model A or model B?

2023-09-13 13:59 UTC, carmenfan commented on frontend/src/v5/ui/routes/dashboard/projects/tickets/ticketsList/slides/ticketSlide.component.tsx
I think the ideal scenario would be either:

- we wipe the unfinished changes from the ticket panel when we change critical state like model selection, but we have a warning that the user can cancel their action if they wish to finish off what they're doing
- we have some clear labelling on where this ticket belongs, and it doesnt' change even if the state of the tabular view has changed. (Though I think doing this can still be confusing and maybe the former would work better)

@george-hadfield  this is probably more of an UX question

2023-09-13 15:05 UTC, george-hadfield commented on frontend/src/v5/ui/routes/dashboard/projects/tickets/ticketsList/slides/ticketSlide.component.tsx
I think the first option works:

> we wipe the unfinished changes from the ticket panel when we change critical state like model selection, but we have a warning that the user can cancel their action if they wish to finish off what they're doing

2023-09-19 15:54 UTC, The-Daniel approved these changes

2023-09-20 15:16 UTC, merged