Issue 4428 - Federation's containers have group
3drepo/3drepo.io pull request #4436
Opened 2023-09-05 16:44 UTC by Amantini1997

This fixes #4428

#### Description
- The frontend understands the new federation interface and adheres to it
- The frontend also uses the newly created design for federation settings (not the modal UI, an issue has been created to address that as it's something generic https://github.com/3drepo/3drepo.io/issues/4435)

#### Test cases
- Use the edit/create federation as before to add/remove containers (regression test);
- Assign groups to the containers (only groups in the federation should allow groups)

2023-09-06 12:47 UTC, george-hadfield commented
### Add right padding to plus and minus icons

Just needs a bit more to match the design

<img width="91" alt="image" src="https://github.com/3drepo/3drepo.io/assets/78047794/7f5b7dc9-16e5-4bbd-8c67-107310f553d1">

2023-09-06 12:47 UTC, george-hadfield commented
### Change plus icon colour when on blue background
Change to white

<img width="64" alt="image" src="https://github.com/3drepo/3drepo.io/assets/78047794/86cd092b-21ee-4e1d-a6fa-f0f0e629af17">

2023-09-06 12:48 UTC, george-hadfield requested changes
Couple of small ones

2023-09-06 16:23 UTC, Amantini1997 commented
/azp run

2023-09-07 09:54 UTC, Charence commented
/azp run

2023-09-11 14:33 UTC, george-hadfield approved these changes

2023-09-14 15:36 UTC, carmenfan commented
@Amantini1997 i merged in changes from the parent branch and it had conflicts (https://github.com/3drepo/3drepo.io/pull/4436/commits/ffd41431179e56ff56699159d7d6308095647efc)

and it now white screens 😢

2023-09-15 12:58 UTC, Amantini1997 commented
> @Amantini1997 i merged in changes from the parent branch and it had conflicts ([ffd4143](https://github.com/3drepo/3drepo.io/commit/ffd41431179e56ff56699159d7d6308095647efc))
> 
> and it now white screens 😢

It should work again now, although the "cancel" button in the modals 

> @Amantini1997 i merged in changes from the parent branch and it had conflicts ([ffd4143](https://github.com/3drepo/3drepo.io/commit/ffd41431179e56ff56699159d7d6308095647efc))
> 
> and it now white screens 😢

It should work again now

2023-09-19 14:59 UTC, The-Daniel requested changes

2023-09-19 14:59 UTC, The-Daniel commented on frontend/src/v5/ui/routes/dashboard/projects/federations/editFederationModal/editFederationContext.tsx
> +	const groups = uniq(existingGroups.concat(Object.values(groupsByContainer))).filter(Boolean);
![image](https://github.com/3drepo/3drepo.io/assets/62481250/fea5c91e-4ff4-47bd-a5dc-41579cbb8970)
These should probably be sorted alphabetically

2023-09-19 14:59 UTC, The-Daniel commented on frontend/src/v5/ui/routes/dashboard/projects/federations/editFederationModal/editFederation/editFederationContainersList/editFederationContainersListItem/editFederationContainersListItem.styles.ts
> +export const Autocomplete = styled(AutocompleteBase)`
![image](https://github.com/3drepo/3drepo.io/assets/62481250/8f2fc68b-d9fd-4f90-99a5-d0093483676a)
There's a shadow floating when the list is empty

2023-09-22 15:43 UTC, carmenfan requested changes
Can we make a change on the groups suggested list drop down?

Currently if I type something that doesn't exist and I tab away it gets deleted. This is a bit of an expected behaviour (and it's quite annoying!). Can we assume that if the user change focus, they want to keep that group name instead of a cancel behaviour?

![img-22-40-23-04-40](https://github.com/3drepo/3drepo.io/assets/11945337/da19576e-6c57-4804-8d22-462103f31b1b)


If this changes the behaviour in the upload revision modal that's fine - that one is also really annoying.

Essentially I think we'd like the behaviour to be closer to v4 risks

![img-22-42-23-04-42](https://github.com/3drepo/3drepo.io/assets/11945337/cf650fec-f08f-42d9-bb66-9fbb6fc8e194)

2023-09-26 15:00 UTC, Amantini1997 commented
@carmenfan I only changed the behvaiour of the autocomplete in the edit/create federation modal.
I tried to tackle the upload file modal as well, but that impacted performance badly and since Dan is already refactoring that code, I decided to wait until then to do it again

2023-09-27 10:32 UTC, The-Daniel approved these changes

2023-10-06 17:20 UTC, carmenfan commented
/azp run

2023-10-09 10:14 UTC, carmenfan approved these changes

2023-10-09 10:16 UTC, merged