Issue 4391- Federation groups
3drepo/3drepo.io pull request #4445
Opened 2023-09-07 17:20 UTC by carmenfan

This fixes #4391

#### Description
New functionality added:
- The ability to assign groups to containers with a federation
  - schema has been altered to store this information in federation settings
  - swagger has been updated to reflect the new schema
- The ability to render the groups correctly in the tree
  - requires https://github.com/3drepo/3drepobouncer/issues/639
  - tree UI altered to understand where a model reference is in the tree (instead of assuming it's always the first child)

#### Test cases
-  v4
  - [ ] Can edit federations (pre/post migration)
  - [ ] Can create federation 
  - [ ] Can import BCF
  - [ ] account list is correct
- v5
  - [ ] Delete container - submodel check should function as before
  - [ ] Get TicketGroupByID should work as before (for purposes of getting ids from submodels)
  - [ ] GetModelStats should work
  - [ ] Can edit federations (pre/post migration)

2023-09-11 14:21 UTC, ChristosTsiotsias requested changes

2023-09-15 15:08 UTC, ChristosTsiotsias approved these changes

2023-10-09 17:08 UTC, Charence commented
/azp run

2023-10-10 10:41 UTC, sanmont3drepo requested changes

2023-10-10 10:41 UTC, sanmont3drepo commented on frontend/src/v5/ui/routes/dashboard/projects/federations/editFederationModal/editFederation/editFederationContainersList/editFederationContainersListItem/groupOption/groupOption.component.tsx
> +	return (
can we add a bit of a comment here stating that the css styles and behaviours from materialuitem will be applied through props?

2023-10-10 10:41 UTC, sanmont3drepo commented on frontend/src/v5/ui/routes/dashboard/projects/federations/editFederationModal/editFederation/editFederation.component.tsx
>  	};
I think we could get rid of these two and just call  `includeContainers([container])` and  `removeContainers([container])`.

2023-10-11 16:25 UTC, sanmont3drepo submitted a review, later dismissed

2023-10-13 09:50 UTC, Charence commented
/azp run

2023-10-13 10:25 UTC, merged