ISSUE #3959 - v4 textarea text does not overlap buttons
3drepo/3drepo.io pull request #4455
Opened 2023-09-14 10:43 UTC by Amantini1997

This fixes #3959

#### Description
V4 editable inputs using textarea now have some padding on the right to not overlap the buttons which are now vertically displayed to take less horizontal room

#### Test cases
Go to ay v4 components that has a description input, such as groups or issues

2023-09-14 10:43 UTC, Amantini1997 commented
/azp run

2023-09-18 14:28 UTC, george-hadfield submitted a review, later dismissed

2023-09-18 17:11 UTC, The-Daniel requested changes

2023-09-18 17:11 UTC, The-Daniel commented on frontend/src/v5/ui/v4Adapter/overrides/cards/issues/properties.overrides.ts
![image](https://github.com/3drepo/3drepo.io/assets/62481250/e812944a-d585-4e3b-8d20-135b5372ca3e)
Views

2023-09-21 11:17 UTC, The-Daniel commented on frontend/src/v5/ui/v4Adapter/overrides/cards/safetiBase/treatments.overrides.ts
I feel like a lot of the edit icons are now not centred
![image](https://github.com/3drepo/3drepo.io/assets/62481250/040277cd-5457-4316-a947-111106af322c)
^ Shapes
![image](https://github.com/3drepo/3drepo.io/assets/62481250/47f906a7-506b-4d28-bd84-3be024175b67)
^ Risk treatment

2023-09-27 09:30 UTC, The-Daniel approved these changes

2023-09-29 15:10 UTC, merged