ISSUE #4261 - ticket sagas testing refactor + missing tests
3drepo/3drepo.io pull request #4457
Opened 2023-09-18 10:49 UTC by The-Daniel

This fixes #4261 

#### Description
Refactor ticket saga tests to use new framework
Add missing tests for ticket groups

#### Test cases
Yarn test should pass

2023-09-18 16:15 UTC, Amantini1997 requested changes

2023-09-18 16:15 UTC, Amantini1997 commented on frontend/test/tickets/comments/ticketComments.sagas.spec.ts
>  import * as TicketCommentsSaga from '@/v5/store/tickets/comments/ticketComments.sagas';
This can be deleted

2023-09-18 16:15 UTC, Amantini1997 commented on frontend/test/tickets/comments/ticketComments.sagas.spec.ts
> +		onError;
Nice!

2023-09-18 16:15 UTC, Amantini1997 commented on frontend/test/tickets/comments/ticketComments.sagas.spec.ts
>  			mockServer
Shouldn't the store be populated?

2023-09-18 16:15 UTC, Amantini1997 commented on frontend/test/tickets/comments/ticketComments.sagas.spec.ts
>  			mockServer
same comment about populating the store

2023-09-20 10:29 UTC, The-Daniel commented on frontend/src/v5/store/tickets/tickets.redux.ts
> +		group: Partial<Group>,
It should be partial should it not? The user can update just one property (e.g. title). Passing just the title prop as the `group` will update the title and leave the rest of the ticket unchanged

2023-09-20 13:33 UTC, Amantini1997 requested changes

2023-09-20 13:33 UTC, Amantini1997 commented on frontend/src/v5/store/tickets/tickets.redux.ts
> +		group: Partial<Group>,
> The user can update just one property

Yes for the ticket, but this is about updating ticket's group. If you look at the how the code is executed, it's the whole group that is being passed

2023-09-26 15:19 UTC, Amantini1997 approved these changes

2023-09-27 15:39 UTC, Amantini1997 approved these changes

2023-09-27 15:40 UTC, merged