Issue 4384 - Augment field definition in ticket groups
3drepo/3drepo.io pull request #4459
Opened 2023-09-20 10:25 UTC by Amantini1997

This fixes #4384 

#### Description
Ticket groups use the new rule schema

#### Test cases
Open a ticket with groups and create/edit the rules.
The new interface should not allow to select the field, but that should be set with a rule (similar to the value)

2023-09-29 13:32 UTC, The-Daniel commented
There seems to be a few things missing that are listed in the 'notes' section of this issue. For example default operator being 'IS' and disabling the use of `+` (as well as `*` maybe?)

These also need to apply to the V4 PR

2023-10-03 16:26 UTC, The-Daniel requested changes

2023-10-03 16:26 UTC, The-Daniel commented on frontend/src/v5/ui/routes/viewer/tickets/ticketsForm/ticketGroups/groups/groupRulesForm/groupRulesInputs/ruleFieldValues/fieldValueInput/fieldValueInput.component.tsx
I'm not sure you want the autosuggest list when the type is 'regex' (maybe only for the 'is' type, but I don't know)

2023-10-03 16:26 UTC, The-Daniel commented on frontend/src/v5/ui/routes/viewer/tickets/ticketsForm/ticketGroups/groups/groupRulesForm/groupRulesInputs/ruleOperator/ruleOperator.component.tsx
![image](https://github.com/3drepo/3drepo.io/assets/62481250/194a6944-0589-403d-95f5-fd4acd236bd8)
Adding multiple invalid fields before switching to regex move makes the form invalid although all the visible input fields are valid
![image](https://github.com/3drepo/3drepo.io/assets/62481250/e412f2dc-ee9e-4b6e-9319-02e098a230a4)

2023-10-03 16:26 UTC, The-Daniel commented on frontend/src/v5/ui/routes/viewer/tickets/ticketsForm/ticketGroups/groups/groupRulesForm/groupRulesInputs/ruleOperator/ruleOperator.component.tsx
![image](https://github.com/3drepo/3drepo.io/assets/62481250/ed6db5aa-6ba9-4211-baf3-b2eb1658daae)
Cancelling and reopening the form does not seem to reset the field values
![image](https://github.com/3drepo/3drepo.io/assets/62481250/18b42d77-195c-4f6b-93c0-2696f22d3c00)
Everything else is reset

2023-10-03 16:26 UTC, The-Daniel commented on frontend/src/v5/ui/routes/viewer/tickets/ticketsForm/ticketGroups/groups/groupRulesForm/groupRulesInputs/ruleValues/ruleValues.component.tsx
I still seem able to use the invalid regex values `+` (and maybe* too, maybe ask Carmen?)

2023-10-03 16:26 UTC, The-Daniel commented on frontend/src/v5/ui/routes/viewer/tickets/ticketsForm/ticketGroups/groups/groupRulesForm/groupRulesForm.component.tsx
![image](https://github.com/3drepo/3drepo.io/assets/62481250/3ccbfd9c-0bda-491c-8e41-f1e63c82dfb3)
There's an unnecessary scrollbar

2023-10-03 16:41 UTC, Amantini1997 commented on frontend/src/v5/ui/routes/viewer/tickets/ticketsForm/ticketGroups/groups/groupRulesForm/groupRulesInputs/ruleFieldValues/fieldValueInput/fieldValueInput.component.tsx
It is actually specified in the issue _We should keep the suggested drop down and should be available regardless of operator (even regex, so the user can then trim it to their liking and add syntax to prevent typos)_

2023-10-03 16:42 UTC, Amantini1997 commented on frontend/src/v5/ui/routes/viewer/tickets/ticketsForm/ticketGroups/groups/groupRulesForm/groupRulesInputs/ruleValues/ruleValues.component.tsx
Also specified in the issue _if operator is REGEX, there can only be one value thus + should be disabled._

2023-10-04 10:10 UTC, carmenfan commented on frontend/src/v5/ui/routes/viewer/tickets/ticketsForm/ticketGroups/groups/groupRulesForm/groupRulesInputs/ruleValues/ruleValues.component.tsx
I'm a bit confused about the meaning behind this question. but to be clear:

the +/- button on the side should be disabled for regex, there should be 1 input given for regex

syntax within the regex `*`, `+` should be supported. i.e. I should be able to do something like `.*is.+`

2023-10-04 10:12 UTC, The-Daniel commented on frontend/src/v5/ui/routes/viewer/tickets/ticketsForm/ticketGroups/groups/groupRulesForm/groupRulesInputs/ruleValues/ruleValues.component.tsx
Ahh right. Yes, I misunderstood

2023-10-04 13:39 UTC, The-Daniel approved these changes

2023-10-09 10:57 UTC, merged