Issue 4109 - upgrade Typescript and Storybook
3drepo/3drepo.io pull request #4466
Opened 2023-09-25 11:14 UTC by Amantini1997

This fixes #4109 

#### Description
Upgraded typescript to v5
Upgraded storybook to v7

#### Test cases
Test storybook components and see if they still work (Note: some are already broken in staging)
Test the app to see if still works

2023-09-29 11:19 UTC, The-Daniel requested changes
Also notice the linter and tests are failing

2023-10-03 15:55 UTC, The-Daniel submitted a review, later dismissed

2023-10-06 11:17 UTC, The-Daniel approved these changes

2023-10-06 12:43 UTC, sanmont3drepo approved these changes

2023-10-06 12:46 UTC, merged