ISSUE #4400 - Fix template chip ticket count not updating
3drepo/3drepo.io pull request #4514
Opened 2023-10-11 14:49 UTC by The-Daniel

This fixes #4400

#### Description
The ticket count in the template chips now updates to reflect the number of tickets in the respective template that matches the search filters and completed state.
For a better explanation of how the numbers should work look at the comments in the issue

#### Test cases
Check that the numbers are right when selecting different chips and using different/multiple search terms

2023-10-12 10:53 UTC, Amantini1997 requested changes

2023-10-12 10:53 UTC, Amantini1997 commented on frontend/src/v5/ui/routes/viewer/tickets/ticketsList/ticketsList.component.tsx
> +	const applyTemplatesFilter = (items) => items.filter((ticket) => !selectedTemplates.size || selectedTemplates.has(ticket.type));
Can we rename this to something like "filterByTemplate"?

Also, you can check if there are no selected templates just once for all the tickets:

```ts
	const applyTemplatesFilter = (items) => {
		if (!selectedTemplates.size) return items;
		return items.filter((ticket) => selectedTemplates.has(ticket.type));
	};
```

2023-10-12 16:09 UTC, Amantini1997 approved these changes

2023-10-13 09:53 UTC, carmenfan commented
/azp run

2023-10-13 15:28 UTC, carmenfan approved these changes

2023-10-13 15:28 UTC, merged