ISSUE #4517 - fix: reset visual settings crashes the app
3drepo/3drepo.io pull request #4518
Opened 2023-10-13 14:13 UTC by Amantini1997

This fixes #4517

#### Description
"undefined" was passed as a string and saved in the local storage.
Reading and parsing such a value was the problem since the value was a string

#### Test cases
Change the viewer background color, save, and reset the settings

2023-10-13 14:41 UTC, The-Daniel requested changes

2023-10-13 14:41 UTC, The-Daniel commented on frontend/src/v4/modules/viewer/betaViewer.helpers.ts
> +export const setUseBetaViewer = (useBetaViewer = true) => localStorage.setItem(USE_BETA_VIEWER, JSON.stringify(useBetaViewer));
The 4GB viewer state acts weird with the reset
![image](https://github.com/3drepo/3drepo.io/assets/62481250/2125e8b2-4727-4c9b-8447-eebf17024242)
Pressing reset turns the toggle off (even though on is the default)
![image](https://github.com/3drepo/3drepo.io/assets/62481250/81598ee2-239c-47d2-9e94-5eaee77ce908)
But then upon pressing save and going back into the settings it is on again
![image](https://github.com/3drepo/3drepo.io/assets/62481250/fd0e258c-a562-475b-848b-8b46ffef859b)

2023-10-16 10:14 UTC, The-Daniel approved these changes

2023-10-16 10:53 UTC, carmenfan commented
/azp run

2023-10-16 11:16 UTC, carmenfan approved these changes

2023-10-16 11:16 UTC, merged