Issue 4524 - Project Images Endpoints
3drepo/3drepo.io pull request #4550
Opened 2023-10-24 10:07 UTC by ChristosTsiotsias

This fixes #4524 

#### Description
Endpoints for fetching, updating and deleting project images.
Swagger documentation, unit and e2e tests added.

#### Test cases
GET endpoint should retrieve the project image and return it in binary form
PUT endpoint should validate the payload (binary image), store the image in the filestream and insert the ref in the db. Also remove any previous refs and images from the fileshare
DELETE endpoint should remove an existing image from the fileshare and remove the ref from the db

2023-10-30 12:07 UTC, carmenfan requested changes

2023-10-30 12:07 UTC, carmenfan commented on backend/tests/v5/unit/processors/teamspaces/projects/projects.test.js
> +		test('should get image stream', async () => {
from your implementation we're not gettig image stream, we're getting the blob in this entirety?

2023-10-30 14:59 UTC, ChristosTsiotsias commented on backend/src/v5/middleware/dataConverter/inputs/teamspaces/projects/index.js
> +		if (!req.file) throw createResponseCode(templates.invalidArguments, 'A file must be provided');
it seems to pass singleFileMulterPromise without an exception being thrown

2023-10-30 15:07 UTC, ChristosTsiotsias commented on backend/src/v5/routes/teamspaces/projects/projects.js
> +	 *         description: Deletes the image of the project
do you mean like this ? 

![image](https://github.com/3drepo/3drepo.io/assets/71635617/aea153af-cd9b-4312-b9b1-76fd903ebab2)

I dont think I've seen it in another endpoint

2023-10-30 15:24 UTC, carmenfan commented on backend/src/v5/routes/teamspaces/projects/projects.js
> +	 *         description: Deletes the image of the project
yea

2023-10-30 15:29 UTC, carmenfan commented on backend/src/v5/middleware/dataConverter/inputs/teamspaces/projects/index.js
> +		if (!req.file) throw createResponseCode(templates.invalidArguments, 'A file must be provided');
in that case we either:

1. we check in `singleFileMulterPromise`  to ensure file is there, or;
2. add a check in `singleFileUpload` and throw an error there.


Either way I don't think we need another middleware that is a duplicate in 2 places to check the file needs to exist

2023-11-08 14:45 UTC, carmenfan requested changes

2023-11-08 14:45 UTC, carmenfan commented on backend/src/v5/routes/teamspaces/projects/projects.js
> +const uploadImage = async (req, res) => {
upload isn't really the action here anymore, it's more like `updateImage`

2023-11-17 12:57 UTC, ChristosTsiotsias commented on backend/src/v5/middleware/dataConverter/multer.js
> +	const ext = await fileExtensionFromBuffer(fileBuffer);
if filebuffer is undefined then ext will be undefined and will throw unsupportedFileFormat error

2023-12-06 09:48 UTC, carmenfan approved these changes

2023-12-06 09:48 UTC, merged