Issue 4580 - hot fix for groups issues
3drepo/3drepo.io pull request #4581
Opened 2023-11-10 13:59 UTC by sanmont3drepo

This fixes #4580 

#### Description
- Fixes edition of groups in tickets
- Creation of new groups in new tickets

#### Test cases

**1**
- Create a custom ticket with a default view and proceed to create 2 groups
- Refresh
- Try to edit one of the 2 groups
- The panel should be populated after the first click

**2**
- Click on  new ticket with a template with a viewpoint
- Without saving the new ticket create a group
- Edit the group
- The form should have the correct group data

**2**
- Click on  new ticket with a template with a viewpoint
- Without saving the new ticket create a group
- Try to create another group
- Both groups should appear and be editable

2023-11-10 14:01 UTC, carmenfan commented
/azp run

2023-11-10 14:44 UTC, Amantini1997 commented
Wrong colour applied to groups:
- Open the new ticket form and before saving the ticket, open the groups list;
- Click on "create group" in the coloured section;
- Without closing the panel, click on "create group" in the hidden section;

### Current behaviour
The colour that was selected for the coloured group is applied to the hidden group

### Expected behaviour
The new hidden group should be colourless

(Note: the opposite is also true)

Uploading Registrazione 2023-11-10 144139.mp4…

2023-11-10 15:14 UTC, sanmont3drepo commented
> Wrong colour applied to groups:
> 
> * Open the new ticket form and before saving the ticket, open the groups list;
> * Click on "create group" in the coloured section;
> * Without closing the panel, click on "create group" in the hidden section;
> 
> ### Current behaviour
> The colour that was selected for the coloured group is applied to the hidden group
> 
> ### Expected behaviour
> The new hidden group should be colourless
> 
> (Note: the opposite is also true)
> 
>  Registrazione.2023-11-10.144139.mp4

fixed

2023-11-10 15:14 UTC, sanmont3drepo commented
> Wrong colour applied to groups:
> 
> * Open the new ticket form and before saving the ticket, open the groups list;
> * Click on "create group" in the coloured section;
> * Without closing the panel, click on "create group" in the hidden section;
> 
> ### Current behaviour
> The colour that was selected for the coloured group is applied to the hidden group
> 
> ### Expected behaviour
> The new hidden group should be colourless
> 
> (Note: the opposite is also true)
> 
>  Registrazione.2023-11-10.144139.mp4

fixed

2023-11-10 15:29 UTC, carmenfan commented
/azp run

2023-11-10 16:34 UTC, carmenfan commented
/azp run

2023-11-10 16:54 UTC, Amantini1997 commented on frontend/src/v5/ui/routes/viewer/tickets/ticketsForm/ticketGroups/groups/groupActionMenu/groupSettingsForm/groupSettingsForm.component.tsx
> +		if (!isColored) {
This creates an error when the user selects the no-color option (the one with a red diagonal line)

2023-11-10 17:01 UTC, Amantini1997 commented on frontend/src/v5/ui/routes/viewer/tickets/ticketsForm/ticketGroups/ticketGroups.component.tsx
> +		setEditingOverride({ override: cloneDeep(state?.[type]?.[index]), type, editing:true });
This is not a change request, but in the future, could we rename "editingOverride" to something else, like sidePanelOverride? It is confusing to have a flag property "editing" for something called "editingOverride"

2023-11-10 17:08 UTC, carmenfan commented
/azp run

2023-11-13 11:45 UTC, carmenfan approved these changes

2023-11-13 11:56 UTC, carmenfan requested changes
#### Hide button doesn't seem to work in the group list
I have the roof hidden in this ticket: https://issue-4580.dev.3drepo.io/v5/viewer/DevTeamWorkspace/7b6c7bd0-054a-11ee-ac5b-59e952832776/0aed56a0-2d3f-11ee-8c0b-17a4bf167a31?ticketId=ba3523e9-19fc-425c-b8d4-8c3bb0e51ed6

Bit of I've unhide it on the group list, I can't seem to hide it again. I think it's to do with it being selected. Maybe it should auto unselect if the hide button is triggered?
![img-13-54-23-11-54](https://github.com/3drepo/3drepo.io/assets/11945337/904289d1-b4bf-49b2-9e3d-bdbc760231df)

2023-11-13 12:00 UTC, carmenfan commented
Wrong icon when we have partial toggle : 
![image](https://github.com/3drepo/3drepo.io/assets/11945337/ef28c296-ac4b-4892-9c23-d1cb54a88dd6)

2023-11-13 12:12 UTC, Amantini1997 commented
##### Update group creates a new group
- Go to the viewer and refresh the page;
- Click on new ticket (select a template with groups)
- Create a new group;
- Edit the group.

##### Expected behvaiour
The ticket should update

##### Actual behaviour
A new ticket is created

https://github.com/3drepo/3drepo.io/assets/43547703/1a62d8c4-1113-4b1c-bec0-691ba7154840

2023-11-13 12:33 UTC, Amantini1997 commented
##### Deleting a group being edited does not close the side panel
When an existing group is being edited, and (before saving the edit) deleted, the the side panel stays open

https://github.com/3drepo/3drepo.io/assets/43547703/7b91fd98-c3a8-496e-928d-25c201ab4834

2023-11-13 12:49 UTC, sanmont3drepo commented
> ##### Update group creates a new group
> * Go to the viewer and refresh the page;
> * Click on new ticket (select a template with groups)
> * Create a new group;
> * Edit the group.
> 
> ##### Expected behvaiour
> The ticket should update
> 
> ##### Actual behaviour
> A new ticket is created
> 
>  Registrazione.2023-11-13.120611.mp4

Fixed

2023-11-13 14:26 UTC, carmenfan commented
/azp run

2023-11-13 14:36 UTC, Amantini1997 approved these changes

2023-11-13 15:12 UTC, carmenfan approved these changes

2023-11-13 15:45 UTC, merged