Issue 4561 - Removed access to v4
3drepo/3drepo.io pull request #4605
Opened 2023-11-20 17:20 UTC by sanmont3drepo

This fixes #4561 

#### Description
- Removed access to v4.
- Removed isv5 conditional rendering
- Updated 404 now it only shows v5 version

2023-11-21 10:09 UTC, Amantini1997 commented
If I try to navigate to `https://3drepo.lan/dashboard`, I don't get redirected to v5 and the app crashes

2023-11-21 10:15 UTC, Amantini1997 requested changes

2023-11-21 10:15 UTC, Amantini1997 commented on frontend/src/main.tsx
If I try to navigate to `https://3drepo.lan/dashboard` or `https://3drepo.lan/viewer`, I don't get redirected to v5 and the app crashes.

Also, if I insert an invalid route(e.g. `https://3drepo.lan/reset-password`), I don't get a 404

2023-11-21 11:42 UTC, sanmont3drepo commented on frontend/src/main.tsx
cant reproduce

2023-11-21 11:42 UTC, Amantini1997 approved these changes

2023-11-21 12:24 UTC, The-Daniel requested changes

2023-11-21 12:24 UTC, The-Daniel commented on frontend/src/v4/routes/components/invitationDialog/invitationDialog.component.tsx
Not sure if it's specifically from this file, but trying to invite a user now causes a crash

2023-11-21 12:24 UTC, The-Daniel commented on frontend/src/v4/constants/viewerGui.ts
> +(clientConfigService.sequencesEnabled || panel !== VIEWER_PANELS.SEQUENCES)).map(getPanelConfig);
Opening the sequences panel is causing a crash

2023-11-21 12:24 UTC, The-Daniel commented on frontend/src/v5/ui/routes/viewer/groups/groupItem/groupItemContainer.component.tsx
> +				<TooltipButton action={onClickIsolate} label="Isolate" Icon={Visibility} disabled={disabled} />
This should be removed as the isV5 is negated. This causes the styling to look weird.

![image](https://github.com/3drepo/3drepo.io/assets/62481250/b620fdb0-d471-4144-a913-38a2e3ba1432)

(staging)
![image](https://github.com/3drepo/3drepo.io/assets/62481250/51b9358b-1174-4e08-ae98-0c1d4733bc10)

2023-11-22 10:41 UTC, Amantini1997 approved these changes

2023-11-22 11:42 UTC, merged