ISSUE 4582 - Move issue properties bar after description
3drepo/3drepo.io pull request #4610
Opened 2023-11-22 11:00 UTC by Amantini1997

This fixes #4582

#### Description
The issue properties bar has been moved

#### Test cases
See how it looks when it is rendered with and without properties below

2023-11-22 11:29 UTC, sanmont3drepo requested changes

2023-11-22 11:29 UTC, sanmont3drepo commented on frontend/src/v5/ui/routes/viewer/tickets/ticketsForm/propertiesList.component.tsx
> +
The bottom padding got lost also the line separating

<img width="332" alt="image" src="https://github.com/3drepo/3drepo.io/assets/42032433/f367d33d-9516-4207-8af0-87048e3efcd3">
 
take a lok at the padding here

![image](https://github.com/3drepo/3drepo.io/assets/11945337/65dc6364-0a41-4fb4-a94d-33ca9e5af6f6)

[original mockup](https://www.figma.com/file/3FjNEOdQbcHwzquVZxUqMl/3D-Repo?type=design&node-id=340-379&mode=design&t=xlhQ35jN4b2bmZCV-0)

2023-11-22 14:40 UTC, The-Daniel submitted a review, later dismissed

2023-11-23 11:35 UTC, sanmont3drepo approved these changes

2023-11-23 16:07 UTC, merged