Issue 4591 - Custom ticket groups - UX Improvements
3drepo/3drepo.io pull request #4611
Opened 2023-11-22 16:58 UTC by Amantini1997

This fixes #4591

#### Description
- When the user tries to hide all hidden groups, it should deselect any selected groups within the category
- Newly created hidden groups should be hidden by default instead of shown
- If the group you have selected is deleted, it should not auto select the next group

#### Test cases
Test them

2023-11-27 11:17 UTC, The-Daniel commented
Another few problems that could possibly be addressed???
1 - Should clicking 'Show all' in the toolbar change the visibility in the groups list? (Note the eye icon is not changing)
![image](https://github.com/3drepo/3drepo.io/assets/62481250/610206ac-7d2a-4683-a3c7-56c8abc27dd7)
![image](https://github.com/3drepo/3drepo.io/assets/62481250/5abb6561-0282-449f-9caa-4bd519875120)

2 - If you have a group list item selected and then click 'Clear overrides' in the toolbar the override briefly flickers off but stays highlighted. Should this deselect the list item and remove the override?

(Sorry. I know these will require diving into v4 code😬)

2023-11-27 12:46 UTC, sanmont3drepo requested changes

2023-11-27 12:46 UTC, sanmont3drepo commented on frontend/src/v5/ui/routes/viewer/tickets/ticketsForm/ticketGroups/groups/groupItem/groupItem.component.tsx
> +	const isHidden = groupType === 'hidden';
When editing an existing hidden group it the group stays selected showing the same problem
![show hidden group](https://github.com/3drepo/3drepo.io/assets/42032433/bbd27c1a-bd0f-4ae7-a0d0-fd0837694c4b)

2023-11-27 12:46 UTC, sanmont3drepo commented on frontend/src/v5/ui/routes/viewer/tickets/ticketsForm/ticketGroups/groups/groupItem/groupItem.component.tsx
> +	}, [isHighlighted]);
what is this new code for?

2023-11-28 14:59 UTC, sanmont3drepo commented
> Another few problems that could possibly be addressed??? 1 - Should clicking 'Show all' in the toolbar change the visibility in the groups list? (Note the eye icon is not changing) ![image](https://private-user-images.githubusercontent.com/62481250/285844104-610206ac-7d2a-4683-a3c7-56c8abc27dd7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDExODM3OTAsIm5iZiI6MTcwMTE4MzQ5MCwicGF0aCI6Ii82MjQ4MTI1MC8yODU4NDQxMDQtNjEwMjA2YWMtN2QyYS00NjgzLWEzYzctNTZjOGFiYzI3ZGQ3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI4VDE0NTgxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM1MTMzOTllZTVjZThiOTRhOTU2NGUwOTIyZDBjMmQ3YjAwMmQ5MDgwYWI1Zjg3YjU2MjJjNGE2MjQ0MjhjYjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.r67vQrt7Q414ybfmmhQXJ8zKaSNybL4oRBXA9J-FoU0) ![image](https://private-user-images.githubusercontent.com/62481250/285844301-5abb6561-0282-449f-9caa-4bd519875120.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDExODM3OTAsIm5iZiI6MTcwMTE4MzQ5MCwicGF0aCI6Ii82MjQ4MTI1MC8yODU4NDQzMDEtNWFiYjY1NjEtMDI4Mi00NDlmLTljYWEtNGJkNTE5ODc1MTIwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI4VDE0NTgxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNiNTMzYzA1OGE2MTJjNjQ0MDQ4ZjgwZjBlMzNhM2ZkMDM0N2YxZGY0M2M4NWM0NGQ2ZDUyYzI3NzMwODg5MTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.whX_AyiBCEaLYkHbzzzTPGfMymfoGsPfwDar9a5NQkM)
> 
> 2 - If you have a group list item selected and then click 'Clear overrides' in the toolbar the override briefly flickers off but stays highlighted. Should this deselect the list item and remove the override?
> 
> (Sorry. I know these will require diving into v4 code😬)

This will be addressed in #4617

2023-11-28 15:04 UTC, sanmont3drepo approved these changes

2023-11-29 10:48 UTC, merged