ISSUE 4613 - Now gotoviewpoint only shows it if there's relevant data
3drepo/3drepo.io pull request #4615
Opened 2023-11-23 15:54 UTC by sanmont3drepo

This fixes #4613 

#### Description
- When you try to show a viewpoint and it has no groups or camera or clipping planes, just ignore it.

2023-11-28 09:09 UTC, carmenfan commented
/azp run

2023-11-28 11:44 UTC, carmenfan requested changes
Found some bugs:

### Bug 1
- Go to this model : https://issue-4613.dev.3drepo.io/v5/viewer/DevTeamWorkspace/7b6c7bd0-054a-11ee-ac5b-59e952832776/0aed56a0-2d3f-11ee-8c0b-17a4bf167a31
- Click on `View 7` which hides some objects and colour overrides a tree
- Then click on the ticket `MNV:2 - test`

The ticket only has a camera, no groups - view moves to the right place and resets the hidden objects, but the tree is still pink

### Bug 2
Try to view `MNV:3`, it's white screening: https://issue-4613.dev.3drepo.io/v5/viewer/DevTeamWorkspace/7b6c7bd0-054a-11ee-ac5b-59e952832776/0aed56a0-2d3f-11ee-8c0b-17a4bf167a31

![img-28-47-23-11-47](https://github.com/3drepo/3drepo.io/assets/11945337/d8c3ef1d-0b4a-4450-bf2b-8c65eee197c1)

2023-11-28 13:46 UTC, sanmont3drepo commented
/azp run

2023-11-29 13:40 UTC, carmenfan approved these changes

2023-11-29 16:50 UTC, Amantini1997 requested changes

2023-11-29 16:50 UTC, Amantini1997 commented on frontend/src/v5/helpers/viewpoint.helpers.ts
> +	if (isEmpty(view?.state?.colored)  && isEmpty(view?.state?.hidden) && isEmpty(view?.camera) && isEmpty(view?.clippingPlanes)) {
Given this, I think you can delete line `108` in TicketDetailsCard.component.tsx (`if (isEmpty(defaultView)) return;`)

2023-11-29 17:40 UTC, Amantini1997 approved these changes

2023-11-30 09:46 UTC, merged