Issue 4608 - new Toolbar
3drepo/3drepo.io pull request #4624
Opened 2023-11-29 15:38 UTC by Amantini1997

This fixes #4608

#### Description
There is a new toolbar that uses the new design.

#### Test cases

2023-11-29 16:34 UTC, Amantini1997 commented
/azp run

2023-11-30 14:23 UTC, The-Daniel requested changes

2023-12-01 09:29 UTC, Amantini1997 commented
/azp run

2023-12-01 14:16 UTC, Amantini1997 commented
/azp run

2023-12-04 10:55 UTC, sanmont3drepo submitted a review, later dismissed

2023-12-04 11:32 UTC, The-Daniel commented on frontend/src/v5/ui/routes/viewer/toolbar/buttons/buttonOptionsContainer/clipButtons.component.tsx
On staging the clip button can be toggled on and off to show/hide the clipping GUI elements. In this branch you can't do this so the clipping GUI cannot be hidden. Is this intended?

2023-12-04 13:52 UTC, carmenfan requested changes
Can't run /azp with conflicts

2023-12-04 13:52 UTC, carmenfan commented on frontend/src/v5/ui/routes/viewer/toolbar/buttons/buttonOptionsContainer/clipButtons.component.tsx
you should still be able to do this

2023-12-04 18:22 UTC, carmenfan commented on frontend/src/v5/ui/routes/viewer/toolbar/buttons/buttonOptionsContainer/clipButtons.component.tsx
Just had a go... indeed, like before, we should be able to click on that button to toggle on/off edit mode of the clipping plane 
![image](https://github.com/3drepo/3drepo.io/assets/11945337/c38c60ff-77dc-4d4e-aea0-3a5bf23700b3)

2023-12-04 18:33 UTC, carmenfan requested changes
#### Having colour override imposed by a view is not triggering the tool bar icon to pop up
Going into a view here, you can see that it only triggered the show all button but not the colour override button:
![img-04-29-23-06-29](https://github.com/3drepo/3drepo.io/assets/11945337/a72f9a0c-75e9-4103-bc5a-c36b1d8f4ca1)

This is also not showing up when we have a colour override imposed by the sequence card

#### Transform reset? (feature request)
It's not in the original scope (sorry), but could we also get a button for transform reset? It's possible for us to move geometry via a sequence and even save it as part of a issues/risks viewpoint, you can find a sample model with such sequence here https://issue-4608.dev.3drepo.io/v5/viewer/DevTeamWorkspace/72d935e5-d15f-4bc4-8433-fb6d79d57301/bc8f82ef-db39-4cb0-a4f9-9bb47aa14dc9
![img-04-36-23-06-36](https://github.com/3drepo/3drepo.io/assets/11945337/6946576d-c69c-4abd-a9ff-d3da922546f2)

At the moment besides manipulating the sequence card or imposing a different view, there's no way for us to reset the transform, so it would be good if we can add a button for that like we do for colour overrides etc.

2023-12-05 15:07 UTC, Amantini1997 commented
> #### Having colour override imposed by a view is not triggering the tool bar icon to pop up
> Going into a view here, you can see that it only triggered the show all button but not the colour override button: ![img-04-29-23-06-29](https://private-user-images.githubusercontent.com/11945337/287796058-a72f9a0c-75e9-4103-bc5a-c36b1d8f4ca1.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE3NzcyMjYsIm5iZiI6MTcwMTc3NjkyNiwicGF0aCI6Ii8xMTk0NTMzNy8yODc3OTYwNTgtYTcyZjlhMGMtNzVlOS00MTAzLWJjNWEtYzM2YjFkOGY0Y2ExLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA1VDExNDg0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEyYThkODc0MmJhMzE3NDEyYTY3Zjk2YWMxY2YyZjhmZTY0ZjhlZDBjYjM0YmE2NGJiMmQ0MzIzY2E4ZDUzZDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.h3Um9mWwIsN2gre4ZgGIWStb_hvyB0LWYplb8cTyi3g) [ ![img-04-29-23-06-29](https://private-user-images.githubusercontent.com/11945337/287796058-a72f9a0c-75e9-4103-bc5a-c36b1d8f4ca1.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE3NzcyMjYsIm5iZiI6MTcwMTc3NjkyNiwicGF0aCI6Ii8xMTk0NTMzNy8yODc3OTYwNTgtYTcyZjlhMGMtNzVlOS00MTAzLWJjNWEtYzM2YjFkOGY0Y2ExLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA1VDExNDg0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEyYThkODc0MmJhMzE3NDEyYTY3Zjk2YWMxY2YyZjhmZTY0ZjhlZDBjYjM0YmE2NGJiMmQ0MzIzY2E4ZDUzZDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.h3Um9mWwIsN2gre4ZgGIWStb_hvyB0LWYplb8cTyi3g) ](https://private-user-images.githubusercontent.com/11945337/287796058-a72f9a0c-75e9-4103-bc5a-c36b1d8f4ca1.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE3NzcyMjYsIm5iZiI6MTcwMTc3NjkyNiwicGF0aCI6Ii8xMTk0NTMzNy8yODc3OTYwNTgtYTcyZjlhMGMtNzVlOS00MTAzLWJjNWEtYzM2YjFkOGY0Y2ExLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA1VDExNDg0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEyYThkODc0MmJhMzE3NDEyYTY3Zjk2YWMxY2YyZjhmZTY0ZjhlZDBjYjM0YmE2NGJiMmQ0MzIzY2E4ZDUzZDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.h3Um9mWwIsN2gre4ZgGIWStb_hvyB0LWYplb8cTyi3g) [ ](https://private-user-images.githubusercontent.com/11945337/287796058-a72f9a0c-75e9-4103-bc5a-c36b1d8f4ca1.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE3NzcyMjYsIm5iZiI6MTcwMTc3NjkyNiwicGF0aCI6Ii8xMTk0NTMzNy8yODc3OTYwNTgtYTcyZjlhMGMtNzVlOS00MTAzLWJjNWEtYzM2YjFkOGY0Y2ExLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA1VDExNDg0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEyYThkODc0MmJhMzE3NDEyYTY3Zjk2YWMxY2YyZjhmZTY0ZjhlZDBjYjM0YmE2NGJiMmQ0MzIzY2E4ZDUzZDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.h3Um9mWwIsN2gre4ZgGIWStb_hvyB0LWYplb8cTyi3g)
> 
> This is also not showing up when we have a colour override imposed by the sequence card
> 
> #### Transform reset? (feature request)
> It's not in the original scope (sorry), but could we also get a button for transform reset? It's possible for us to move geometry via a sequence and even save it as part of a issues/risks viewpoint, you can find a sample model with such sequence here https://issue-4608.dev.3drepo.io/v5/viewer/DevTeamWorkspace/72d935e5-d15f-4bc4-8433-fb6d79d57301/bc8f82ef-db39-4cb0-a4f9-9bb47aa14dc9 ![img-04-36-23-06-36](https://private-user-images.githubusercontent.com/11945337/287797393-6946576d-c69c-4abd-a9ff-d3da922546f2.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE3NzcyMjYsIm5iZiI6MTcwMTc3NjkyNiwicGF0aCI6Ii8xMTk0NTMzNy8yODc3OTczOTMtNjk0NjU3NmQtYzY5Yy00YWJkLWE5ZmYtZDNkYTkyMjU0NmYyLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA1VDExNDg0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg5Y2VmMGVhYWFkNGRlOWE0NzdiNDFlNzYyMjFmZWU3ZTBhYzQxNjIyMmMwODI0NGY4ZjU0YTc2Yjc0ZjNkYTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Bv_in7fiimSuDIjKPBeHkgo3fLmX9YYs55LGfjuOipU) [ ![img-04-36-23-06-36](https://private-user-images.githubusercontent.com/11945337/287797393-6946576d-c69c-4abd-a9ff-d3da922546f2.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE3NzcyMjYsIm5iZiI6MTcwMTc3NjkyNiwicGF0aCI6Ii8xMTk0NTMzNy8yODc3OTczOTMtNjk0NjU3NmQtYzY5Yy00YWJkLWE5ZmYtZDNkYTkyMjU0NmYyLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA1VDExNDg0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg5Y2VmMGVhYWFkNGRlOWE0NzdiNDFlNzYyMjFmZWU3ZTBhYzQxNjIyMmMwODI0NGY4ZjU0YTc2Yjc0ZjNkYTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Bv_in7fiimSuDIjKPBeHkgo3fLmX9YYs55LGfjuOipU) ](https://private-user-images.githubusercontent.com/11945337/287797393-6946576d-c69c-4abd-a9ff-d3da922546f2.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE3NzcyMjYsIm5iZiI6MTcwMTc3NjkyNiwicGF0aCI6Ii8xMTk0NTMzNy8yODc3OTczOTMtNjk0NjU3NmQtYzY5Yy00YWJkLWE5ZmYtZDNkYTkyMjU0NmYyLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA1VDExNDg0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg5Y2VmMGVhYWFkNGRlOWE0NzdiNDFlNzYyMjFmZWU3ZTBhYzQxNjIyMmMwODI0NGY4ZjU0YTc2Yjc0ZjNkYTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Bv_in7fiimSuDIjKPBeHkgo3fLmX9YYs55LGfjuOipU) [ ](https://private-user-images.githubusercontent.com/11945337/287797393-6946576d-c69c-4abd-a9ff-d3da922546f2.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE3NzcyMjYsIm5iZiI6MTcwMTc3NjkyNiwicGF0aCI6Ii8xMTk0NTMzNy8yODc3OTczOTMtNjk0NjU3NmQtYzY5Yy00YWJkLWE5ZmYtZDNkYTkyMjU0NmYyLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA1VDExNDg0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg5Y2VmMGVhYWFkNGRlOWE0NzdiNDFlNzYyMjFmZWU3ZTBhYzQxNjIyMmMwODI0NGY4ZjU0YTc2Yjc0ZjNkYTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Bv_in7fiimSuDIjKPBeHkgo3fLmX9YYs55LGfjuOipU)
> 
> At the moment besides manipulating the sequence card or imposing a different view, there's no way for us to reset the transform, so it would be good if we can add a button for that like we do for colour overrides etc.

I made an issue for the feature request https://github.com/3drepo/3drepo.io/issues/4636

2023-12-05 18:05 UTC, Amantini1997 commented
/azp run

2023-12-06 10:13 UTC, carmenfan requested changes
Hidden objects are detected when the objects are hidden by a sequence, but colour overrides are ignored (completely, can't even remove them!)
![img-06-11-23-10-11](https://github.com/3drepo/3drepo.io/assets/11945337/766b81b8-a5f5-4c70-9546-ff704ff12c0c)

Model: https://issue-4608.dev.3drepo.io/v5/viewer/DevTeamWorkspace/72d935e5-d15f-4bc4-8433-fb6d79d57301/bc8f82ef-db39-4cb0-a4f9-9bb47aa14dc9

2023-12-06 11:50 UTC, Amantini1997 commented
> Hidden objects are detected when the objects are hidden by a sequence, but colour overrides are ignored (completely, can't even remove them!) 
> **[IMAGE]**
> Model: https://issue-4608.dev.3drepo.io/v5/viewer/DevTeamWorkspace/72d935e5-d15f-4bc4-8433-fb6d79d57301/bc8f82ef-db39-4cb0-a4f9-9bb47aa14dc9

I checked on staging and it seems the clearOverrides button is also not clearing geometry overrides from sequences.
I created a new issue to address this feature https://github.com/3drepo/3drepo.io/issues/4640

2023-12-07 11:06 UTC, The-Daniel approved these changes

2023-12-07 15:34 UTC, sanmont3drepo approved these changes

2023-12-07 15:35 UTC, merged