ISSUE #4661 - Use A-Site privacy page
3drepo/3drepo.io pull request #4675
Opened 2024-01-08 15:52 UTC by Amantini1997

This fixes #4661 

#### Description
Use Asite privacy page instead of 3dRepo
Trying to access privacy page will result in a redirect to ASite privacy page

#### Test cases
Try to access the privacy page via different links:
- copy paste link in the URL bar;
- footer;
- navlink from cookies/terms page

2024-01-08 15:58 UTC, The-Daniel submitted a review, later dismissed

2024-01-08 16:32 UTC, Amantini1997 commented
/azp run

2024-01-08 16:40 UTC, carmenfan requested changes

2024-01-08 16:40 UTC, carmenfan commented on frontend/src/v5/ui/components/shared/sso/microsoftText.component.tsx
> +					PrivacyLink: (label) => <a href={PRIVACY_ROUTE} target="_blank">{label}</a>,
The link is rendered differently, can we unify it?

on staging
![image](https://github.com/3drepo/3drepo.io/assets/11945337/3a979801-3bf6-4869-bc22-34063bb63cdb)
on this branch
![image](https://github.com/3drepo/3drepo.io/assets/11945337/544879e1-4b5d-481b-91c6-9bab6356006a)

2024-01-08 16:40 UTC, carmenfan commented on frontend/src/v5/ui/components/legal/LegalLayout/legalAppBar/legalAppBar.component.tsx
> +				<PrivacyLink href={PRIVACY_ROUTE} target="_blank">
Can we fix the formatting here too:
staging:
![image](https://github.com/3drepo/3drepo.io/assets/11945337/c889f2fc-3683-4183-b741-622f67b0263f)

this branch:
![image](https://github.com/3drepo/3drepo.io/assets/11945337/4a0686c7-2c50-4d73-94ab-c2379fcf33bc)

2024-01-10 13:56 UTC, Amantini1997 commented
/azp run

2024-01-11 10:51 UTC, carmenfan requested changes
![24-01-11 10-49-32](https://github.com/3drepo/3drepo.io/assets/11945337/fa0a9788-758e-4bc9-8cc2-bc78fd630298)


the footer is not going to the privacy page

2024-01-11 11:16 UTC, Amantini1997 commented
/azp run

2024-01-11 15:58 UTC, carmenfan approved these changes

2024-01-11 17:07 UTC, The-Daniel approved these changes

2024-01-11 17:35 UTC, merged