ISSUE #4689 - add revision param to fetchTicketGroup
3drepo/3drepo.io pull request #4700
Opened 2024-01-18 17:54 UTC by Amantini1997

This fixes #4689 

#### Description
Revision Id is included as an optional search param when calling GET ticketGroup.
Since to avoid unnecessary calls to the backend, we were not re-fetching a group when it was already stored in redux, but different revisions have different object ids, the groups are cleared every time a different revision is selected

#### Test cases
Open a container with 2 ifc/revit revisions (upload the same revision twice) and proceed to create a smart ticket group from either revision. Then switch revision. The object count should be the same.

2024-01-19 14:22 UTC, The-Daniel requested changes

2024-01-19 17:13 UTC, Amantini1997 commented on frontend/test/tickets/tickets.sagas.spec.ts
> +		fit('should call fetchFederationTicket endpoint', async () => {
it was a leftover

2024-01-19 17:41 UTC, The-Daniel approved these changes

2024-01-22 16:36 UTC, sanmont3drepo approved these changes

2024-01-22 16:37 UTC, merged