ISSUE #4380 - 2d Milestone 1
3drepo/3drepo.io pull request #4836
Opened 2024-03-15 14:33 UTC by sanmont3drepo

This fixes #4380 

#### Description
- Milestone 1  for 2d drawing. More details [here](https://github.com/3drepo/3D-Repo-Product-Team/issues/377)

2024-08-23 09:42 UTC, sanmont3drepo commented
/azp run

2024-08-27 09:27 UTC, carmenfan commented on backend/.vscode/launch.json
> +{
The sizing logic here is a bit odd (this is half of a 1080 screen):
![image](https://github.com/user-attachments/assets/51c7c133-313d-4d8c-af7f-3c9492f1e040)

2024-08-27 09:29 UTC, carmenfan commented on backend/.vscode/launch.json
> +{
Behaviour also seems to change  for no clear reason depending on whether I upload a pdf or dwg, the drawing side panel only pops up automatically if I upload a pdf:

![24-08-27 10-28-13](https://github.com/user-attachments/assets/e292afe7-6553-43b6-a214-962cff27add6)

2024-08-27 10:46 UTC, carmenfan commented
/azp run

2024-08-27 11:06 UTC, carmenfan requested changes

2024-08-27 16:35 UTC, carmenfan commented
/azp run

2024-08-27 16:38 UTC, sanmont3drepo commented on backend/.vscode/launch.json
> +{
moved into #5127

2024-08-27 16:48 UTC, sanmont3drepo commented on backend/.vscode/launch.json
> +{
Moved into #5128

2024-09-12 12:53 UTC, carmenfan submitted a review, later dismissed
Generally fine just a small tooltip that needs fixing

2024-09-12 12:53 UTC, carmenfan commented on backend/.vscode/launch.json
![image](https://github.com/user-attachments/assets/18aada28-ed7d-4031-8eba-10e5ef5e6106)

Tooltip doesn't give correct information on drawings (it expands/collapse the revision list, it doesn't launch the drawing)

2024-09-12 13:32 UTC, carmenfan approved these changes

2024-09-12 14:17 UTC, merged