Issue 4867 - V4 manual group validation broken with hidden meshes
3drepo/3drepo.io pull request #4884
Opened 2024-04-12 11:50 UTC by Amantini1997

This fixes #4867 

#### Description
- New groups do not show "last upated" or "objects count"
- Selected nodes (in redux state) should always reflect what is effectively selected. As such, selecting all the objects and the hiding them all will make a new group invalid

#### Test cases
- Select all the objects;
- Click on "new group" (the group should be saveable)
- Hide all the objects; (the groups should not be saveable)

2024-04-15 10:42 UTC, The-Daniel requested changes

2024-04-15 10:42 UTC, The-Daniel commented on frontend/src/v4/helpers/groups.ts
![image](https://github.com/3drepo/3drepo.io/assets/62481250/fba394ba-968b-46f6-8c98-b4dd0973c0ce)
Tickets groups is now broken. Object count is stuck at 0 so you can't create a manual group

2024-04-24 14:35 UTC, The-Daniel requested changes

2024-04-24 14:35 UTC, The-Daniel commented on frontend/src/v4/modules/tree/tree.sagas.ts
The isolate and hide functions in the toolbar are broken.
## Isolate
![image](https://github.com/3drepo/3drepo.io/assets/62481250/cb0cc999-a076-45ee-8d0b-f47a09425593)

## Hide
![image](https://github.com/3drepo/3drepo.io/assets/62481250/a6b6f9f9-7e98-440f-a35c-6307b1a72a4a)

2024-04-24 14:35 UTC, The-Daniel commented on frontend/src/v4/modules/tree/tree.sagas.ts
> +	const delectedNodes = yield select(selectSelectedNodes);
Delectable

2024-04-25 11:55 UTC, The-Daniel commented on frontend/src/v4/modules/tree/tree.sagas.ts
> +	const delectedNodes = yield select(selectSelectedNodes);
It's delectable again

2024-04-26 14:12 UTC, The-Daniel submitted a review, later dismissed

2024-05-01 14:17 UTC, sanmont3drepo requested changes

2024-05-01 14:17 UTC, sanmont3drepo commented on frontend/src/v4/helpers/groups.ts
> +import { selectNumNodesByMeshSharedIdsArray } from '../modules/tree';
I still can reproduce the original bug

2024-05-08 10:35 UTC, carmenfan approved these changes

2024-05-08 10:42 UTC, The-Daniel approved these changes

2024-05-08 11:25 UTC, sanmont3drepo approved these changes

2024-05-08 11:26 UTC, merged