Issue 4921 - FIX: tickets table slide not loading and custom status is missing
3drepo/3drepo.io pull request #4936
Opened 2024-04-26 09:22 UTC by Amantini1997

This fixes #4921 

#### Description
Template data was not fetched, this was fixed.
There was also a problem with the status chip for custom status that was empty, that has also been fixed

#### Test cases
Use the template provided in the issue description and check you can access a ticket slide without it loading forever.
Check also the status chip is always displayed

2024-04-26 09:26 UTC, sanmont3drepo requested changes

2024-04-26 09:26 UTC, sanmont3drepo commented on frontend/src/v5/store/projects/projects.selectors.ts
> +import { DEFAULT_STATUS_CONFIG } from '@controls/chip/chip.types';
Status is not showing when opening the ticket
<img width="1137" alt="image" src="https://github.com/3drepo/3drepo.io/assets/42032433/cea43525-4592-484b-a7a6-1037f3a2483d">

2024-04-26 15:05 UTC, sanmont3drepo requested changes

2024-04-26 15:05 UTC, sanmont3drepo commented on frontend/src/v5/ui/routes/viewer/tickets/ticketsForm/ticketsTopPanel/statusProperty/statusProperty.component.tsx
> +		: TicketsHooksSelectors.selectStatusConfigByTemplateId(containerOrFederation, templateId);
can we change TicketsHooksSelectors.selectStatusConfigByTemplateId so it also takes information from the projecttemplates?

2024-04-26 16:04 UTC, The-Daniel approved these changes

2024-05-01 12:37 UTC, sanmont3drepo approved these changes

2024-05-01 12:38 UTC, sanmont3drepo commented
/azp run

2024-05-01 12:39 UTC, merged