Issue 4942: [2D MVP] Milestone 3: 2D Vector drawing
3drepo/3drepo.io pull request #4970
Opened 2024-05-23 11:14 UTC by Amantini1997

This fixes #4942 

#### Description
Create a layer to draw arrow on top of the 2d viewer

#### Test cases
Play around with the arrow, check it creates correctly, the app doesn't crush, and the coordinates are correct

2024-05-29 12:22 UTC, sanmont3drepo requested changes

2024-05-29 12:46 UTC, sanmont3drepo commented on frontend/src/v5/ui/components/viewer/drawingViewer/drawingViewer.component.tsx
> +			setViewBox({ ...transform, ...zoomHandler.getOriginalSize() });
also.. why do you need the original size?

2024-05-29 12:47 UTC, sanmont3drepo requested changes

2024-05-29 12:47 UTC, sanmont3drepo commented on frontend/src/v5/ui/components/viewer/drawingViewer/viewerLayer2D/viewerLayer2D.component.tsx
> +	const handleMouseDown = () => previousViewBox.current = viewBox;
It takes a couple of clicks before starting to draw
![drawing arrow](https://github.com/3drepo/3drepo.io/assets/42032433/c5f24a5e-ecc8-4024-91a6-9f8566206788)

2024-05-29 13:48 UTC, Amantini1997 commented on frontend/src/v5/ui/components/viewer/drawingViewer/drawingViewer.component.tsx
> +			setViewBox({ ...transform, ...zoomHandler.getOriginalSize() });
That's for the drawing layer to know how big it should be.
The transform object only contains info about the zoom level and the offsets, but not about the size

2024-05-29 14:43 UTC, Amantini1997 commented on frontend/src/v5/ui/components/viewer/drawingViewer/drawingViewer.component.tsx
> +			setViewBox({ ...transform, ...zoomHandler.getOriginalSize() });
The transform object only contains the offset and the zoom level, which are not enough for the drawingContainer to know where the image ends, and so what are the boundaries to draw the arrow (or hovering circle), to know that, it needs the original image sizes

2024-05-29 14:45 UTC, Amantini1997 commented on frontend/src/v5/ui/components/viewer/drawingViewer/viewerLayer2D/viewerLayer2D.component.tsx
> +	const layerStyle: CSSProperties = {
This is current code. The panzoom object modifies directly the image via css `transform: matrix`. In order to adjust the other layers to overlap the image, they also need to adjust their transformation to it

2024-05-30 11:59 UTC, Amantini1997 commented on frontend/src/v5/ui/components/viewer/drawingViewer/viewerLayer2D/svgCircle/svgCircle.component.tsx
> +		<Svg
I couldn't see noticeable improvements

2024-06-12 14:43 UTC, sanmont3drepo requested changes

2024-06-12 14:43 UTC, sanmont3drepo commented on frontend/src/v5/ui/components/viewer/drawingViewer/viewerLayer2D/viewerLayer2D.component.tsx
> +/**
Pan and zoom using the mouse no longer works

2024-06-17 10:10 UTC, sanmont3drepo requested changes

2024-06-17 12:03 UTC, sanmont3drepo approved these changes

2024-06-19 09:37 UTC, The-Daniel approved these changes

2024-06-19 15:15 UTC, merged