Issue 4826 - Milestone 1: backend integration
3drepo/3drepo.io pull request #5077
Opened 2024-07-23 09:10 UTC by Amantini1997

This fixes #4826 

#### Description
- Added API calls and wired in the backend for both drawings and drawing revisions
- Added tests for both of them
- Added events for drawings (not drawing revisions)
- Fixed the interfaces and propagated the changes over the app

#### Test cases
Create/Edit/Delete drawings, set them as favourite and test the events for them
Create/Delete/Change Void status for revisions
All the changes should persist upon refresh

2024-07-23 11:25 UTC, The-Daniel requested changes

2024-07-23 11:25 UTC, The-Daniel commented on frontend/test/drawings/drawings.store.spec.ts
> +			expect(drawingIsIncluded).not.toBeTruthy();
I think this could be `toBeFalsey` instead of `not.toBeTruthy`

2024-07-23 11:25 UTC, The-Daniel commented on frontend/src/v5/services/api/drawingRevisions.ts
>  export const getRevisionFileUrl = (teamspace: string, projectId: string, drawingId: string, revision: string) => (
Has this been implemented yet? When I try to download a drawing revision I get a `Container not found` error.
![image](https://github.com/user-attachments/assets/6bf40ea5-2d04-45cb-b50c-7ff4dae4f041)

2024-07-31 10:28 UTC, The-Daniel approved these changes

2024-08-02 10:30 UTC, sanmont3drepo approved these changes

2024-08-22 15:08 UTC, merged