Milestone 3: Step 2 - 2D calibration points
3drepo/3drepo.io pull request #5097
Opened 2024-08-09 10:39 UTC by Amantini1997

This fixes #4910

#### Description
2d calibration mode is only available when calibrating step 2.
The 2d vector data is correctly stored and shown again when re-calibrating

#### Test cases
- Opening a drawing should not show the calibration
- 2d vector can only be set when is calibrating step 2

2024-08-12 15:54 UTC, The-Daniel requested changes

2024-08-12 15:54 UTC, The-Daniel commented on frontend/src/v5/ui/routes/dashboard/projects/calibration/calibrationHeader/calibrationHeader.component.tsx
> +		if (step === 1) return !!(vector2D[0] && vector2D[1]);
Vector2D does not seem to be reset when the user clicks to change the arrow, unlike in the 3D calibration. This means that if the user clicks to start a new arrow the continue button is still valid which will use the old values for the 2D vector.
Gif showing how for 3D calibration the continue buttons gets disabled until the arrow is complete. There is also a secondary bug here where the user can go back to step 1 whilst in the middle of calibrating the 2D vector so it is still enabled but the toolbar option is hidden.
![arrows](https://github.com/user-attachments/assets/fdb056ef-4439-4764-9dfd-3f8164ecab19)
In fact just going backwards after setting the 2D vector keeps the 2D calibration tool vector so you can change it whilst in the 3D step. Is this okay?

2024-08-13 15:13 UTC, The-Daniel approved these changes

2024-08-16 10:37 UTC, sanmont3drepo approved these changes

2024-08-16 10:39 UTC, merged