ISSUE #5009 - Make V5 card headers match the style of V4 card headers
3drepo/3drepo.io pull request #5105
Opened 2024-08-13 13:10 UTC by The-Daniel

This fixes #5009

#### Description
Slightly adjust the V5 card header so that it matches the existing V4 headers

#### Test cases
Check the card headers in all 3 stages of the tickets card
The spacing and font style should match that of the v4 cards (e.g. groups, sequences, compare)

2024-08-15 09:43 UTC, Amantini1997 requested changes

2024-08-15 09:43 UTC, Amantini1997 commented on frontend/src/v5/ui/components/viewer/cards/card.styles.ts
>  	display: flex;
you can delete this as you change the display mode later

2024-08-19 16:00 UTC, Amantini1997 approved these changes

2024-08-23 14:57 UTC, sanmont3drepo submitted a review, later dismissed

2024-08-27 09:12 UTC, Amantini1997 approved these changes

2024-08-27 09:23 UTC, merged