ISSUE #5125 - Milestone 3: Tweaks to calibration plane overlays
3drepo/3drepo.io pull request #5152
Opened 2024-09-10 13:28 UTC by The-Daniel

This fixes #5125

#### Description
- Adds a white background to any images that are overlayed
- Only applies the drawing to the selected plane. The other plane has a mildly transparent white background

#### Test cases
Test out the vertical calibration

2024-09-10 13:28 UTC, The-Daniel commented
/azp run

2024-09-11 09:49 UTC, carmenfan requested changes

2024-09-11 09:49 UTC, carmenfan commented on frontend/unity/default/unity/Build/unity.data.unityweb
I don't know if this is relevant to this issue, but it applies on every step:

by default the calibration should not be active as soon as you enter. This is why the help wizard tells you to click on it 
![image](https://github.com/user-attachments/assets/9c1da618-60d2-42f0-81b4-47bb7c3b3174)

This applies to every single step in the calibration

2024-09-11 09:49 UTC, carmenfan commented on frontend/unity/default/unity/Build/unity.data.unityweb
![image](https://github.com/user-attachments/assets/4931e5a4-bcbd-4484-91cd-f1ba76cee9b3)

2024-09-11 09:49 UTC, carmenfan commented on frontend/unity/default/unity/Build/unity.data.unityweb
![image](https://github.com/user-attachments/assets/5b58afcd-f34c-470d-8ecc-8cd02fb63a4a)
For this page, the help wizard needs to have a similar message telling them to Cliick on the <icon> to start placing the bottom adn top places

Whole point of this is to allow the user to impose clip plane/hide objects before they start.

2024-09-11 09:49 UTC, carmenfan commented on frontend/unity/default/unity/Build/unity.data.unityweb
It is not putting the plane on the correct place:

Notice how I clipped the objects to select the floor on level 1, and the bottom plane still defaulted to the roof
![24-09-11 10-44-02](https://github.com/user-attachments/assets/02dc218b-db58-4f62-9e82-b84d089c9652)

2024-09-11 09:49 UTC, carmenfan commented on frontend/unity/default/unity/Build/unity.data.unityweb
I think the transparency isn't working well, is there a unity utils command I can use to tweak either of the planes? @The-Daniel  @sebjf  
![image](https://github.com/user-attachments/assets/4a95a417-789d-4664-ab97-eb6960aed580)

2024-09-11 09:52 UTC, carmenfan commented on frontend/unity/default/unity/Build/unity.data.unityweb
@sebjf  it could also be to do with the dwg lines are too faint... 🙈 

@The-Daniel  can you pull latest of milestone 2 in so I can try other files that I uploaded for real?

2024-09-12 11:02 UTC, sebjf commented on frontend/unity/default/unity/Build/unity.data.unityweb
Hi @carmenfan,

>is there a unity utils command I can use to tweak either of the planes?

`setCalibrationToolSelectedColors` & `setCalibrationToolUnselectedColors` take an HTML colour string including transparency, which can be used to control the opacity of the planes.

I can tweak the minimum line width in bouncer easily to make the line stronger too! We can decide on a suitable value before making the PR for 695.

2024-09-13 14:59 UTC, carmenfan commented on frontend/unity/default/unity/Build/unity.data.unityweb
> For this page, the help wizard needs to have a similar message telling them to Cliick on the to start placing the bottom adn top places
Whole point of this is to allow the user to impose clip plane/hide objects before they start.

@sebjf To do this, we need a third state. At the moment (or at least @sanmont3drepo tells me!) once you've selected a plane, we can't unselect them.

instead of `selectCalibrationToolLowerPlane` and `selectCalibrationToolUpperPlane`, could we do something like `selectCalibrationToolPlane(string)` where if it's the string parameter is undefined, we do not select any plane?

The behaviour should be:

If top plane is selected, image is rendered on the top plane
If bottom plane is selected, image is rendered on the bottom plane
If none are selected:
   if top plane exists, image is rendered on the top plane (but no edit gizmo)
   otherwise:
      if bottom plane exists: image is rendered on the bottom plane (but no edit gizmo)
     otherwise:
       nothing 😆 

I'm not sure if i'm making any sense, let me know if this is not clear!

2024-09-13 17:04 UTC, carmenfan commented on frontend/unity/default/unity/Build/unity.data.unityweb
@sanmont3drepo  

Could we try this?
UnityUtil.setCalibrationToolSelectedColors("#FFFFFF77", "#ffffff");
UnityUtil.setCalibrationToolUnselectedColors("#FFFFFF00", "#ffffff");

2024-09-16 10:12 UTC, sebjf commented on frontend/unity/default/unity/Build/unity.data.unityweb
Hi @carmenfan, @The-Daniel,

I've changed how the viewer handles the colours a little. Instead of setting selected and unselected colours, UnityUtil now  has the frontend set the colours of each plane directly via

`setCalibrationToolVerticalPlaneColours(plane, fill, border, drawing)`

The method to assign the gizmo is now

`selectCalibrationToolVerticalPlane(plane)`

Passing anything other than "upper" or "lower" will deactivate the gizmo. 

"Selecting" now only chooses which plane the gizmo acts on. The frontend must update the colours when changing the selected plane to see a visual change. However there is a lot more flexibility in them now.

*  fill is the tint applied to the drawing, after the background.
*  border is the colour of the border around the image.
*  drawing is the tint applied to the image, before the background.

These can be combined to create various effects.

For example..

```
// Turn off the drawing entirely - leave a translucent white background
UnityUtil.setCalibrationToolVerticalPlaneColours("upper","#ffffffa0","#ffffffff","#ffffff00")

// The same thing, but with a solid background
UnityUtil.setCalibrationToolVerticalPlaneColours("upper","#ff0000ff","#ffffffff","#ffffff00")

// Solid white plane, but with a very faint drawing
UnityUtil.setCalibrationToolVerticalPlaneColours("upper","#ffffffff","#ffffffff","#ffffff30")

// Set the bottom to solid red, and the top to translucent blue image
UnityUtil.setCalibrationToolVerticalPlaneColours("upper","#0000ff40","#ffffffff","#ffffffff")
UnityUtil.setCalibrationToolVerticalPlaneColours("lower","#ff0000ff","#ffffffff","#ffffff00")
```

The viewer changes are on 545 and I've pushed an update viewer to 5125

2024-09-16 16:16 UTC, carmenfan approved these changes

2024-09-16 16:16 UTC, merged