Issue 4833 - Milestone 2
3drepo/3drepo.io pull request #5154
Opened 2024-09-10 15:40 UTC by sanmont3drepo

This fixes #4833 

#### Description
- The user can view the drawings in the viewer from the drawings list
- The user can view the drawing and pan and zoom

2024-09-10 15:40 UTC, sanmont3drepo commented
/azp run

2024-09-10 15:55 UTC, sanmont3drepo commented
/azp run

2024-09-10 16:16 UTC, carmenfan requested changes

2024-09-10 16:16 UTC, carmenfan commented on backend/src/v5/services/eventsListener/components/modelEvents.js
>  			{ _id: 0, tag: 1, author: 1, timestamp: 1, desc: 1, rFile: 1, format: 1, statusCode: 1, revCode: 1 });
![image](https://github.com/user-attachments/assets/fbb083c3-1519-4e22-a400-4f05c6757f76)
Can we set the SVG drawing to have a white background so it looks like a 2D sheet and also it won't be hindered by users setting a custom background colour

2024-09-10 16:16 UTC, carmenfan commented on backend/src/v5/services/eventsListener/components/modelEvents.js
>  			{ _id: 0, tag: 1, author: 1, timestamp: 1, desc: 1, rFile: 1, format: 1, statusCode: 1, revCode: 1 });
Background colour of the viewer should change as depicted by viewer settings
![image](https://github.com/user-attachments/assets/9be45dc1-3f1a-4a0d-983f-fe77e4f427ee)

2024-09-10 16:16 UTC, carmenfan commented on backend/src/v5/services/eventsListener/components/modelEvents.js
>  			{ _id: 0, tag: 1, author: 1, timestamp: 1, desc: 1, rFile: 1, format: 1, statusCode: 1, revCode: 1 });
I recall talking to @Amantini1997  about this so maybe it's fixed in a different milestone, but the drawing panel should be visible if the enters the viewer with a drawing ID in the query. I.e. it should look like this:

![image](https://github.com/user-attachments/assets/78538a1b-a799-4ed8-a193-85b483740775)

At the moment it looks like this:
![image](https://github.com/user-attachments/assets/1629664b-d03d-4af8-80e7-f93085205036)

2024-09-10 16:16 UTC, carmenfan commented on backend/src/v5/services/eventsListener/components/modelEvents.js
>  			{ _id: 0, tag: 1, author: 1, timestamp: 1, desc: 1, rFile: 1, format: 1, statusCode: 1, revCode: 1 });
I think we need to allow the user to zoom out for more than the original image size.

For e.g. here, I'm looking at a corner of the picture and I can't zoom out to see the whole picture without re-centering the image, which doesn't feel natural:

![24-09-10 05-14-18](https://github.com/user-attachments/assets/ef9029d5-3a74-4163-96ea-c39d7375b67d)

2024-09-10 16:44 UTC, carmenfan requested changes

2024-09-10 16:44 UTC, carmenfan commented on backend/src/v5/services/eventsListener/components/modelEvents.js
>  			{ _id: 0, tag: 1, author: 1, timestamp: 1, desc: 1, rFile: 1, format: 1, statusCode: 1, revCode: 1 });
![image](https://github.com/user-attachments/assets/1904bbeb-2da4-431e-a0c0-383607c7f800)
We're missing an overflow strategy here, @apeitup  can you clarify what we should do here?

2024-09-10 16:44 UTC, carmenfan commented on backend/src/v5/services/eventsListener/components/modelEvents.js
>  			{ _id: 0, tag: 1, author: 1, timestamp: 1, desc: 1, rFile: 1, format: 1, statusCode: 1, revCode: 1 });
Drawing list is catching the chat signal for new revisions on existing drawings ok, but new drawings are ignored
![24-09-10 05-35-35](https://github.com/user-attachments/assets/18aef75c-6a4a-4ef3-95d4-1d56503e965b)

2024-09-10 16:54 UTC, carmenfan commented on backend/src/v5/services/eventsListener/components/modelEvents.js
>  			{ _id: 0, tag: 1, author: 1, timestamp: 1, desc: 1, rFile: 1, format: 1, statusCode: 1, revCode: 1 });
To clarify, the end result should have the area highlighted in red being white (approx) and the area outside of the red boundary should be the current background colour

2024-09-11 10:27 UTC, sanmont3drepo commented
/azp run

2024-09-12 17:08 UTC, carmenfan requested changes

2024-09-12 17:08 UTC, carmenfan commented on backend/src/v5/services/eventsListener/components/modelEvents.js
![24-09-12 06-00-08](https://github.com/user-attachments/assets/f6533b53-8069-4bff-a943-da292ca601c6)

Scrolling should keep the selected drawing in view (just like custom tickets)

2024-09-12 17:08 UTC, carmenfan commented on backend/src/v5/services/eventsListener/components/modelEvents.js
>  			{ _id: 0, tag: 1, author: 1, timestamp: 1, desc: 1, rFile: 1, format: 1, statusCode: 1, revCode: 1 });
we went for ellipsis with tool tip here... can we confirm with @apeitup that this is what we want?
![image](https://github.com/user-attachments/assets/888d1b93-88c7-4e39-bb50-1dade2e999d4)


@AsiteZane showed me a mockup of multiline instead when I mentioned it
![image](https://github.com/user-attachments/assets/866f97c9-6829-4eb9-a974-efb5ca7e2e2f)

2024-09-12 17:08 UTC, carmenfan commented on backend/src/v5/services/eventsListener/components/modelEvents.js
It doesn't look like there's a sort logic on the drawing list at all?

Waiting on @AsiteZane  to confirm by what we should be sorting by 😆

2024-09-12 19:17 UTC, AsiteZane commented on backend/src/v5/services/eventsListener/components/modelEvents.js
Last updated please :)

2024-09-18 09:28 UTC, carmenfan approved these changes

2024-09-18 09:28 UTC, merged