Issue 5038 - Milestone 4 & 5
3drepo/3drepo.io pull request #5193
Opened 2024-10-07 12:17 UTC by sanmont3drepo

This fixes #5038 

#### Description
- This pr shows the camera  and pins positions on a calibrated drawing
- The user can drop pins in 2d and 3d

2024-10-08 13:29 UTC, carmenfan requested changes
@sanmont3drepo  as discussed i'll pause and wait till the fix on the 2D viewer before further testing

2024-10-09 13:43 UTC, carmenfan requested changes

2024-10-09 15:36 UTC, carmenfan commented on frontend/assets/icons/viewer/camera.svg.tsx
Sorry this is more to do with milestone 1, but can we tweak this menu slightly so it's more inline with containers:

![image](https://github.com/user-attachments/assets/73b4e0fa-c1f9-4bab-b908-e70377abb209)

- Move `Upload` to the top and rename it to `Upload new revision`
- Rename `Calibrate` to `Calibrate latest revision`

2024-10-10 09:31 UTC, carmenfan commented on frontend/assets/icons/viewer/camera.svg.tsx
The icon we're using on 2D viewer is incorrect for intersection/node snapping:
![image](https://github.com/user-attachments/assets/65c4998a-3986-49fe-8e8d-3a08860a7144)

Should be the same one (and colour) as the corner snapping icon on 3D:
![image](https://github.com/user-attachments/assets/a8d62053-d115-4ab0-a635-7cf279c72294)

2024-10-11 16:54 UTC, sanmont3drepo commented on frontend/assets/icons/viewer/camera.svg.tsx
@sebjf  can you check what the problem might be with this?

2024-10-15 09:04 UTC, sebjf commented on frontend/assets/icons/viewer/camera.svg.tsx
Hi @sanmont3drepo, @carmenfan, I am unable to reproduce this (see below!). I have tried on both my high DPI and low DPI monitor. @carmenfan is it repeatable for you? 

https://github.com/user-attachments/assets/34ae7f3c-7e9c-48c0-8bf3-a8a1ffe201fe

I have tried placing pins, different sizes, zoom levels & Firefox. 

Looking at it the only thing that jumps to mind is the inertia emulation going over some limit in one dimension. If that is turned off, does the issue go away?

2024-10-15 10:43 UTC, sanmont3drepo commented on frontend/assets/icons/viewer/camera.svg.tsx
Can you assume that that case can happen and make it work for that case?

2024-10-15 10:59 UTC, sanmont3drepo commented on frontend/assets/icons/viewer/camera.svg.tsx
@sebjf another piece of  info: I can only reproduce it if after I switch drawings.

2024-10-15 11:07 UTC, carmenfan commented on frontend/assets/icons/viewer/camera.svg.tsx
@sebjf Yes it's repeatable and it seems to only happen if I've changed drawing
![24-10-15 12-06-20](https://github.com/user-attachments/assets/e3d01c2d-92fd-4faf-88c4-ad1b2c0c5c74)

2024-10-15 11:18 UTC, sebjf commented on frontend/assets/icons/viewer/camera.svg.tsx
OK I can reproduce now, looking into it..

2024-10-15 16:09 UTC, carmenfan submitted a review, later dismissed

2024-10-15 16:09 UTC, carmenfan commented on frontend/assets/icons/viewer/camera.svg.tsx
![24-10-15 05-08-06](https://github.com/user-attachments/assets/cc5f5a42-7d20-4937-aefc-cbaccfbefb7d)

Hovering on the out of camera icon  should change the cursor just like the in view camera gizmo

2024-10-16 11:32 UTC, carmenfan commented
/azp run

2024-10-16 14:27 UTC, carmenfan approved these changes

2024-10-16 14:35 UTC, merged