Issue 5198 - Markdown - textbox pushes canvas out of the view
3drepo/3drepo.io pull request #5228
Opened 2024-10-28 15:29 UTC by Amantini1997

This fixes #5198

#### Description
The code had me refactoring it a bit in order to fix this behaviour as the logic from v4 was very convoluted.

#### Test cases
Create a text (plain or with a callout) and try writing some text that should break according to the box view. The text should never push the canvas out of the box and, on overflow, the text should disappear without following the caret (i.e., if you are typing and the caret is out of view, the textbox should always display the first line, ignoring the current caret position)

2024-11-04 10:20 UTC, sanmont3drepo approved these changes

2024-11-11 11:44 UTC, The-Daniel requested changes

2024-11-11 11:44 UTC, The-Daniel commented on frontend/src/v4/routes/components/screenshotDialog/components/typingHandler/typingCalloutHandler.component.tsx
Textboxes aren't being saved (all other markup objects are fine)

https://github.com/user-attachments/assets/d7525b93-c098-4da9-8074-94b629f9a109

2024-11-13 15:33 UTC, The-Daniel approved these changes

2024-11-19 13:41 UTC, sanmont3drepo approved these changes

2024-11-19 13:42 UTC, merged