Issue 5235 - Custom tickets show only allowed users/jobs in the assignee list
3drepo/3drepo.io pull request #5246
Opened 2024-11-12 14:54 UTC by Amantini1997

This fixes #5235 

#### Description
Each model is linked to some users and jobs. To be linked to a user, it means that that user has at least viewer access. To be linked to job, it means at least of one of the linked user is assigned to that job.

Given this, only linked jobs and users are considered valid for a job/user list. Note, for the `assignee property` (i.e. the one in the ticket top panel), only user with a role higher than viewer are considered valid.

As it is possible to have some users/jobs already assigned to user/job property, the invalid values will be indicated:
- a value that still exists in the teamspace will have a red background (for instance, the user has been demoted to `unassigned` for that model);
- a value that cannot be found in the teamspace will be in different list section ("job or user not found"), with a _ad hoc_ circle popover, and with a red background

If it is a multi-select list, toggling ANY job/user, will remove all the invalid jobs/users from the list

#### Test cases
- Add some user/job to the list, and then unlink them. The user/job data should be available in the popover, but the background should be red.
- Add some user/job to the list and then remove them from the teamspace. The user/job data should be unavailable, the background should be red, and hovering the popover circle should better inform the user. Also, the latter users/jobs should be listed in a separate list section

2024-11-19 13:29 UTC, The-Daniel requested changes

2024-11-21 11:07 UTC, sanmont3drepo requested changes

2024-11-21 11:42 UTC, Amantini1997 commented on frontend/src/v5/store/containers/containers.selectors.ts
> +			if (!teamspaceJob) return teamspaceJobs;
What I did was this:
- create a job
- assign a user to that job
- create (or edit) a ticket and select that job
- delete that job

2024-11-21 11:46 UTC, sanmont3drepo commented on frontend/src/v5/store/containers/containers.selectors.ts
> +			if (!teamspaceJob) return teamspaceJobs;
Doesnt make sense. There still shouldnt exist in the container but it should exist in the asignees for that particular ticket.

2024-11-21 12:40 UTC, Amantini1997 commented on frontend/src/v5/ui/components/shared/popoverCircles/errorPopoverCircle/errorPopover.component.tsx
> +export const ErrorPopover = ({ value, message }) => (
I'm not sure I get this right, but I assume you are referring to what's inside `UserPopover`.
![image](https://github.com/user-attachments/assets/5a449252-1904-4d41-a804-2fbe3b2cc6d7)

If that's the case, the component was not extracted, nor was the `UserPopover` affected by this change.
The idea is that `UserPopover` is called when we know we are dealing with a user that is no longer a teamspace member. This happens, for instance, when you are you looking at a ticket comment from a user that no longer exists in that teamspace
![image](https://github.com/user-attachments/assets/7bfad18f-a146-49f5-8408-c33aa08cb035)

The idea here was that we don't know if we are dealing with a user or a job, so calling the `UserPopover` felt wrong. Also, the message shall be different

2024-11-21 13:04 UTC, Amantini1997 commented on frontend/src/v5/store/containers/containers.selectors.ts
> +			if (!teamspaceJob) return teamspaceJobs;
This is for when, in the viewer, you have already fetched the given container/federation jobs/users, but the jobs/users for that teamspace are still being fetched.
As a result, you get `teamspaceJob = undefined`, which eventually leads to the app crash.

You can test this yourself by:
- deleting line `95`;
- heading to the viewer
- expanding a ticket (so the ticketId is the URL) with populated assignees;
- refreshing the page

2024-11-21 14:25 UTC, Amantini1997 commented on frontend/src/v5/store/containers/containers.selectors.ts
> +			if (!teamspaceJob) return teamspaceJobs;
**TLDR**
What might be misleading here is the name `teamspaceJob` inside the `if`, as may you think the condition is true when the job does not exist in the teamspace, but it in reality, that's the case if the job has not been fetched yet.


**Longer explanation**
Right now, there 2 ways of fetching a job:
- **Fetch Model Jobs**: fetches the jobs for a given container/federation, which will only provide the job id (and whether or not it's a viewer using the `excludeViewers` search param);
- **Fetch Teamspace Jobs**: fetches all the jobs for a teamspace, which will provide much more data

The problem is in the viewer, when you try to reach a ticket via URL (including `ticketId` as a search param). In this scenario, the model jobs are fetched before the teamspace jobs.

This means that `teamspaceJob` will always be `undefined` until the teamspace jobs are fetched. This way, instead, the selector will return a list with valid jobs

2024-12-06 16:24 UTC, The-Daniel approved these changes

2024-12-09 12:17 UTC, sanmont3drepo approved these changes

2024-12-09 12:18 UTC, merged