Issue 5243 - Slope measurements
3drepo/3drepo.io pull request #5249
Opened 2024-11-13 15:31 UTC by Amantini1997

This fixes #5243

#### Description
Added slope measurement to measure panel and issues/risks card

#### Test cases
Select the tool and click anywhere on the model. The data should appear on the measurements list.
Other than that, it should behave the same way as the angle tool:
- data displayed in degrees;
- no "total" at the top;
- you can change colour and edit the name

## Edit
Unity is now delegating the frontend to decide whether or not to display the snapping icon
> this is not entirely true as, calling `UnityUtils.enableSnapping` will set the snapping cursor to visible, hence, `UnityUtils.disableCursor` should always be called after `UnityUtils.enableSnapping`

There are 2 new unity methods that can be called from the frontend to toggle on/off the snapping icon.
The idea is that Slope measurement has its own icon which may overlap with the snapping one, so the latter should be disabled for and only for the slope tool

2024-11-13 16:27 UTC, Amantini1997 commented
/azp run

2024-11-13 16:45 UTC, FJThiel commented
/azp run

2024-11-19 10:18 UTC, The-Daniel requested changes

2024-11-19 10:18 UTC, The-Daniel commented on frontend/assets/icons/measurements/slope.svg.tsx
Error 400 when creating a slope measurement on an issue/risk. This happens in both federations and containers.
![image](https://github.com/user-attachments/assets/34fdf812-89bc-4b2c-ae35-8031185222d6)
The payload: 
![image](https://github.com/user-attachments/assets/d020ad29-d89c-41ce-a0a7-fdf881fbc9d3)

2024-11-21 14:45 UTC, The-Daniel submitted a review, later dismissed

2024-11-26 15:50 UTC, sanmont3drepo approved these changes

2024-12-02 09:43 UTC, sebjf commented
/azp run

2024-12-02 11:37 UTC, sebjf commented
/azp run

2024-12-02 14:54 UTC, sebjf commented
/azp run

2024-12-02 16:23 UTC, carmenfan requested changes
@sebjf believes we're missing the units convertion option in the hamburger menu, see
https://github.com/3drepo/3drepo.io/issues/5243#issuecomment-2506278869

2024-12-09 12:25 UTC, sanmont3drepo approved these changes

2024-12-10 10:45 UTC, Amantini1997 commented
@sebjf My bad, I missed that feature. I've now added that.
Please note, in issues/risks items it is not possible to switch slope units from degrees to percentage. Instead, the units displayed reflects what is set in the measurements card

2024-12-10 10:48 UTC, sebjf commented
> @sebjf My bad, I missed that feature. I've now added that. Please note, in issues/risks items it is not possible to switch slope units from degrees to percentage. Instead, the units displayed reflects what is set in the measurements card

Hi @Amantini1997, can the units for the other measurements be changed in issues/risks? If so we should update the viewer to match.

2024-12-10 10:53 UTC, carmenfan commented
@sebjf  we really don't care about issues/risks (as we aim to decommission the feature next year). The slope measurement can even be skipped on issues/risks if it's easier. So @Amantini1997 please do whatever is easiest

2024-12-16 14:00 UTC, sanmont3drepo approved these changes

2024-12-19 11:01 UTC, carmenfan commented
/azp run

2024-12-19 12:56 UTC, carmenfan requested changes
2 things:

1. default units for slope measurements should be %
2. can we rename the metres one to `Length units` ? 
![image](https://github.com/user-attachments/assets/0cbb911f-6155-4526-b4c4-241100a9dfcf)

@FJThiel unity side is probably good for a PR/rebuild with latest from staging!

2025-01-02 18:06 UTC, Amantini1997 commented
> 2 things:
> 
> 1. default units for slope measurements should be %
> 2. can we rename the metres one to `Length units` ?
>    ![image](https://private-user-images.githubusercontent.com/11945337/397383162-0cbb911f-6155-4526-b4c4-241100a9dfcf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU4Mzk2MjQsIm5iZiI6MTczNTgzOTMyNCwicGF0aCI6Ii8xMTk0NTMzNy8zOTczODMxNjItMGNiYjkxMWYtNjE1NS00NTI2LWI0YzQtMjQxMTAwYTlkZmNmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAxMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMTAyVDE3MzUyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM5OTNmYTRjYTA2ZjUzZGU2Y2UxYmJjNGM5NWRkZjgxNGY5YTNjMmRkMmExN2M0YjFjMjFhYTE1NTIzMzI4ZjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.NhbuuwWoQJh2TvdLG8bQxAQRd7cuhH29IZYk40vGfyY)
> 
> @FJThiel unity side is probably good for a PR/rebuild with latest from staging!

I updated the frontend to assume the default slope unit is in percentage. Unity shall also update to account for it as, right now, it's sending and displaying the value in degrees @FJThiel

2025-01-02 18:18 UTC, carmenfan commented
> > 2 things:
> > 
> > 1. default units for slope measurements should be %
> > 2. can we rename the metres one to `Length units` ?
> >    ![image](https://private-user-images.githubusercontent.com/11945337/397383162-0cbb911f-6155-4526-b4c4-241100a9dfcf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU4Mzk2MjQsIm5iZiI6MTczNTgzOTMyNCwicGF0aCI6Ii8xMTk0NTMzNy8zOTczODMxNjItMGNiYjkxMWYtNjE1NS00NTI2LWI0YzQtMjQxMTAwYTlkZmNmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAxMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMTAyVDE3MzUyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM5OTNmYTRjYTA2ZjUzZGU2Y2UxYmJjNGM5NWRkZjgxNGY5YTNjMmRkMmExN2M0YjFjMjFhYTE1NTIzMzI4ZjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.NhbuuwWoQJh2TvdLG8bQxAQRd7cuhH29IZYk40vGfyY)
> > 
> > @FJThiel unity side is probably good for a PR/rebuild with latest from staging!
> 
> I updated the frontend to assume the default slope unit is in percentage. The Unity player shall also update to account for this requirement as, right now, it's sending and displaying the value in degrees @FJThiel

@Amantini1997 instead of assuming the 2 system have the same default, frontend should always instruct unity about the preferred default so there's no room for error. This is how we've done it for all the viewer settings (I know this one isn't technically a viewer setting)

2025-01-06 10:24 UTC, carmenfan requested changes
Will retest when @FJThiel has pushed the latest version of unity (with latest of staging) in here

2025-01-07 15:25 UTC, sebjf commented
Hi @carmenfan, @Amantini1997, I have updated the viewer to the head of staging. This has all the updates so this PR can be used to update the viewer for .io for everything when its merged.

2025-01-08 10:24 UTC, carmenfan commented
/azp run

2025-01-08 10:25 UTC, carmenfan requested changes
@Amantini1997  frontend linter is failing

2025-01-09 16:48 UTC, Amantini1997 commented
/azp run

2025-01-10 09:30 UTC, carmenfan commented
/azp run

2025-01-10 09:57 UTC, carmenfan approved these changes

2025-01-10 11:09 UTC, sanmont3drepo approved these changes

2025-01-10 11:55 UTC, The-Daniel approved these changes

2025-01-10 13:08 UTC, merged