ISSUE #5195 - Bugs with Drag and Drop area "drag over" state
3drepo/3drepo.io pull request #5277
Opened 2024-12-02 16:50 UTC by The-Daniel

This fixes #5195

#### Description
Updated react-dropzone.
Changed component to use hooks and isDragActive which fixes the two bugs

#### Test cases

- The drag and drop works fully
- Dragging and dropping text into the area has no effect
- When dragging a file into the zone the state does not become disabled when dragging over text/buttons inside the component

2024-12-03 17:56 UTC, Amantini1997 requested changes

2024-12-03 17:56 UTC, Amantini1997 commented on frontend/src/v5/ui/controls/dragAndDrop/dragAndDrop.component.tsx
> +export const DragAndDrop = ({ children, onDrop, ...props }: IDragAndDrop) => {
In staging, dropping a file with an invalid (not supported) extension on the container revision upload modal does nothing. Now, instead, it creates a new revision entry
![image](https://github.com/user-attachments/assets/1710d64b-bf18-4795-b71e-52e12f1bf2f3)

2024-12-03 17:56 UTC, Amantini1997 commented on frontend/src/v5/ui/controls/dragAndDrop/dragAndDrop.component.tsx
> -	hidden?: boolean;
This was used to hide the dragAndDrop container. If you want to remove it, you may need to adjust the components that were passing it (I can only think of of ticket comments creation and after uploading a new revision file, but there may be others)

e.g. container revision upload after uploading:

staging (after uploading)
![image](https://github.com/user-attachments/assets/bd8242bb-f9a8-46a9-a0c3-930a89e17599)


now (after uploading)
![image](https://github.com/user-attachments/assets/b9e551a8-b33a-484c-8438-e0172c96f6ec)

2024-12-05 14:43 UTC, Amantini1997 submitted a review, later dismissed

2024-12-09 17:59 UTC, sanmont3drepo submitted a review, later dismissed

2024-12-10 13:05 UTC, sanmont3drepo approved these changes

2024-12-10 16:10 UTC, merged