Issue 5264 - Ticket filters: string filter form
3drepo/3drepo.io pull request #5280
Opened 2024-12-06 15:34 UTC by Amantini1997

This fixes #5264

#### Description
Added string filter handling:
- show only valid operators;
- allow fields count and their addition/removal depending on the operator
- validate form for string

#### Test cases
Test the different operators:
- [not ]exists should be always valid;
- other operators should have the fields filled to be valid. Furthermore, there's a limit on the string depending on if it is a text (120 chars) or a long text (1,200);
- adding and removing the fields should work as expected;
- the form should handle any fields changes (if needed) upon changing the operator

2024-12-06 17:15 UTC, sanmont3drepo requested changes

2024-12-06 17:15 UTC, sanmont3drepo commented on frontend/src/v5/ui/routes/viewer/tickets/ticketsForm/ticketGroups/groups/groupRulesForm/groupRulesInputs/ruleFieldValues/ruleFieldValues.component.tsx
> +						<FieldValueInput
![image](https://github.com/user-attachments/assets/128d5c05-d030-4d43-8c8c-e06319403c50)

2024-12-06 17:15 UTC, sanmont3drepo commented on frontend/src/v5/ui/routes/viewer/tickets/ticketsForm/ticketGroups/groups/groupRulesForm/groupRulesForm.helpers.ts
> +		values: mapArrayToFormArray(field.values || []),
maybe `mapArrayToFormArray` can cater for undefined or null values and treat them as []. You  reckon there could be a problem with that?

2024-12-06 17:15 UTC, sanmont3drepo commented on frontend/src/v5/ui/controls/inputs/arrayFieldContainer/arrayFieldContainer.component.tsx
> +export const ArrayFieldContainer = ({ children, onRemove, onAdd, disableAdd, disableRemove }: ArrayFieldContainerProps) => (
Can we add a couple of  examples of this in storybook? maybe with a textfield and another one with a select as children.

2024-12-09 10:03 UTC, Amantini1997 commented on frontend/src/v5/ui/components/viewer/cards/cardFilters/filterForm/filterFormValues/filterFormValues.componen.tsx
> +/**
Dan, is that you?

2024-12-09 16:00 UTC, sanmont3drepo requested changes

2024-12-10 16:17 UTC, sanmont3drepo approved these changes

2024-12-11 10:48 UTC, The-Daniel requested changes

2024-12-12 15:39 UTC, The-Daniel approved these changes

2024-12-12 16:10 UTC, merged