ISSUE #5292 - fixed user removed from teamspace crashing the tickets list
3drepo/3drepo.io pull request #5293
Opened 2024-12-10 10:23 UTC by The-Daniel

This fixes #5292

#### Description
Users that were removed from the teamspace but still assigned to a ticket was causing a crash when opening the tickets list

#### Test cases
Try to open the tickets list with tickets that are assigned to users who have been removed from this teamspace

2024-12-10 10:43 UTC, Amantini1997 requested changes

2024-12-10 10:43 UTC, Amantini1997 commented on frontend/src/v5/ui/controls/assigneesSelect/assigneesSelect.component.tsx
> +		...validValues.map((v) => valueToJobOrUser || ({ invalidItemName: v })),
This `||` shouldn't be here: the "invalidItemName" should only be used if the value is invalid, so what's on the line below.
Also, you are no longer invoking the `valueToJobOrUser`

2024-12-10 10:43 UTC, Amantini1997 commented on frontend/src/v5/ui/controls/assigneesSelect/assignees.helpers.ts
> +	return { users, jobs, notFound } as { users: IUser[], jobs: IJob[], notFound: { invalidItemName: string }[] };
I think it's better to keep the `notFoundName` here and rename `invalidItemName` instead

2024-12-11 15:12 UTC, sanmont3drepo approved these changes

2024-12-11 15:13 UTC, Amantini1997 requested changes

2024-12-11 15:25 UTC, sanmont3drepo requested changes

2024-12-11 15:25 UTC, sanmont3drepo commented on frontend/src/v5/store/containers/containers.selectors.ts
> +		return (container?.users || []).map((user) => ({ ...user, ...users[user.user], isNotTeamspaceUser: !some(users, ((u) => u.user === user.user)) }));
I dont think is necesarry to use "some" users is a dictionary
```suggestion
				return (container?.users || []).map((user) => ({ ...user, ...users[user.user], isNotTeamspaceUser: !Boolean(users[user.user])}));
```

2025-01-02 15:00 UTC, Amantini1997 approved these changes

2025-01-02 15:07 UTC, sanmont3drepo approved these changes

2025-01-02 16:09 UTC, merged