[Snyk] Upgrade react-hook-form from 7.12.2 to 7.53.2
3drepo/3drepo.io pull request #5308
Opened 2024-12-13 19:09 UTC by carmenfan

![snyk-top-banner](https://redirect.github.com/andygongea/OWASP-Benchmark/assets/818805/c518c423-16fe-447e-b67f-ad5a49b5d123)

<h3>Snyk has created this PR to upgrade react-hook-form from 7.12.2 to 7.53.2.</h3>

:information_source: Keep your dependencies up-to-date. This makes it easier to fix existing vulnerabilities and to more quickly identify and fix newly disclosed vulnerabilities when they affect your project.

<hr/>

- The recommended version is **171 versions** ahead of your current version.

- The recommended version was released on **a month ago**.

---

> [!IMPORTANT]
>
> - Check the changes in this PR to ensure they won't cause issues with your project.
> - This PR was automatically created by Snyk using the credentials of a real user.

---

**Note:** _You are seeing this because you or someone else with access to this repository has authorized Snyk to open upgrade PRs._

**For more information:** <img src="https://api.segment.io/v1/pixel/track?data=eyJ3cml0ZUtleSI6InJyWmxZcEdHY2RyTHZsb0lYd0dUcVg4WkFRTnNCOUEwIiwiYW5vbnltb3VzSWQiOiI5NzRjN2I2NS05Y2U4LTRmMDQtOTZjYi1jOWM0NDY0ODllNDgiLCJldmVudCI6IlBSIHZpZXdlZCIsInByb3BlcnRpZXMiOnsicHJJZCI6Ijk3NGM3YjY1LTljZTgtNGYwNC05NmNiLWM5YzQ0NjQ4OWU0OCJ9fQ==" width="0" height="0"/>

> - 🧐 [View latest project report](https://app.snyk.io/org/trosadoasite.com/project/b58fc8dc-9724-493c-bf0e-f10535c283f4?utm_source&#x3D;github&amp;utm_medium&#x3D;referral&amp;page&#x3D;upgrade-pr)
> - 📜 [Customise PR templates](https://docs.snyk.io/scan-using-snyk/pull-requests/snyk-fix-pull-or-merge-requests/customize-pr-templates?utm_source=&utm_content=fix-pr-template)
> - 🛠 [Adjust upgrade PR settings](https://app.snyk.io/org/trosadoasite.com/project/b58fc8dc-9724-493c-bf0e-f10535c283f4/settings/integration?utm_source&#x3D;github&amp;utm_medium&#x3D;referral&amp;page&#x3D;upgrade-pr)
> - 🔕 [Ignore this dependency or unsubscribe from future upgrade PRs](https://app.snyk.io/org/trosadoasite.com/project/b58fc8dc-9724-493c-bf0e-f10535c283f4/settings/integration?pkg&#x3D;react-hook-form&amp;utm_source&#x3D;github&amp;utm_medium&#x3D;referral&amp;page&#x3D;upgrade-pr#auto-dep-upgrades)

[//]: # 'snyk:metadata:{"customTemplate":{"variablesUsed":[],"fieldsUsed":[]},"dependencies":[{"name":"react-hook-form","from":"7.12.2","to":"7.53.2"}],"env":"prod","hasFixes":false,"isBreakingChange":false,"isMajorUpgrade":false,"issuesToFix":[],"prId":"974c7b65-9ce8-4f04-96cb-c9c446489e48","prPublicId":"974c7b65-9ce8-4f04-96cb-c9c446489e48","packageManager":"yarn","priorityScoreList":[],"projectPublicId":"b58fc8dc-9724-493c-bf0e-f10535c283f4","projectUrl":"https://app.snyk.io/org/trosadoasite.com/project/b58fc8dc-9724-493c-bf0e-f10535c283f4?utm_source=github&utm_medium=referral&page=upgrade-pr","prType":"upgrade","templateFieldSources":{"branchName":"default","commitMessage":"default","description":"default","title":"default"},"templateVariants":[],"type":"auto","upgrade":[],"upgradeInfo":{"versionsDiff":171,"publishedDate":"2024-11-08T22:15:09.008Z"},"vulns":[]}'

2025-08-06 15:10 UTC, Didi-Kwan-Asite-3DRepo commented
/azp run

2025-08-07 07:21 UTC, Didi-Kwan commented
/azp run

2025-08-07 09:36 UTC, sanmont3drepo commented
/azp run

2025-08-07 11:10 UTC, sanmont3drepo commented
/azp run

2025-08-12 13:53 UTC, Didi-Kwan requested changes
Round 1 testing is complete. Here is the [test summary report](https://asitesol-my.sharepoint.com/:x:/g/personal/ylokkwan_asite_com/EbZOt_Z7xaVEmjfGSXdqoxEBOmIDKKPR0GuXV51qfoxGKg?e=d84OU5).

2025-08-12 13:53 UTC, Didi-Kwan commented on frontend/package.json
> +		"react-hook-form": "7.61.1",
Bug Report 5308-001
Missing success alert when updating profile.

https://github.com/user-attachments/assets/2858b3f6-a774-42d4-9028-9e0a7477c07a

2025-08-12 13:53 UTC, Didi-Kwan commented on frontend/package.json
> +		"react-hook-form": "7.61.1",
Bug Report 5308-002
The `Create Drawing` button should be disabled until all required fields are filled in.

<img width="2559" height="1392" alt="NewDrawing" src="https://github.com/user-attachments/assets/257559b4-ac50-4520-8b20-a1a1de0b2c4b" />

2025-08-12 13:53 UTC, Didi-Kwan commented on frontend/package.json
> +		"react-hook-form": "7.61.1",
Bug Report 5308-003
Required properties `Viewpoint`, `Image` and `Image List` already highlighted in red in new ticket form.

<img width="395" height="1142" alt="Required" src="https://github.com/user-attachments/assets/582b1058-84d3-45d1-9fea-64ba1870d9d8" />

2025-08-12 13:53 UTC, Didi-Kwan commented on frontend/package.json
> +		"react-hook-form": "7.61.1",
Bug Report 5308-004
Error occurs when adding filters to ticket list.

https://github.com/user-attachments/assets/f9ed9dcb-0daa-40ee-b2ff-528b11017d22

2025-08-12 13:53 UTC, Didi-Kwan commented on frontend/package.json
> +		"react-hook-form": "7.61.1",
Bug Report 5308-005
The `Update filter` button stays disabled when updating groups smart filter's name.

https://github.com/user-attachments/assets/7c935f0f-113a-4433-b97b-da3eef3c3cc4

2025-08-12 13:53 UTC, Didi-Kwan commented on frontend/package.json
> +		"react-hook-form": "7.61.1",
Bug Report 5308-006
No Open Street Map option in GIS.

<img width="1273" height="1390" alt="GIS" src="https://github.com/user-attachments/assets/fa7c59d7-c36d-49f2-99b8-8a9d0423a6f7" />

2026-04-28 16:12 UTC, sanmont3drepo commented
This one is addressed in #5883

2026-04-28 16:12 UTC, closed without merging