Issue 5267 - Ticket filters: Date
3drepo/3drepo.io pull request #5315
Opened 2024-12-19 10:24 UTC by Amantini1997

This fixes #5167

#### Description
Added support and validation for date filters

#### Test cases
Test normal date as well as ranges
- Make sure validation is correct;
- Check they are correctly rendered in the filter chip;
- Make sure in validation, the invalid dates are correctly disabled

2025-01-02 17:06 UTC, sanmont3drepo requested changes

2025-01-03 14:32 UTC, Amantini1997 commented on frontend/src/v5/ui/components/viewer/cards/cardFilters/filterForm/filterFormValues/rangeInput/dateRangeInput.component.tsx
> +				formError={!!error}
I kept the same design for errors in smart groups:
![image](https://github.com/user-attachments/assets/0211aa82-0d27-4edf-a92a-190a09d5ba49)

Shall I show keep it as is, or update it, and maybe create an issue to update the design in groups as well?

2025-01-03 14:37 UTC, Amantini1997 commented on frontend/src/v5/ui/components/viewer/cards/cardFilters/cardFilters.helpers.ts
> +	if (type === 'date') return ['eq', 'lte', 'gte', 'rng', 'nrng', 'ex', 'nex'];
The difference is that the extra date-types defined in `DATE_TYPES_VARIANTS` are ticket input types that do not have any meaning when it comes to ticket filters, so they are simply mapped to "date".
For text types, instead, you have "text" and "longText" that have different validations

2025-01-03 17:18 UTC, sanmont3drepo commented on frontend/src/v5/ui/components/viewer/cards/cardFilters/filterForm/filterFormValues/rangeInput/dateRangeInput.component.tsx
> +				formError={!!error}
Create an issue for groups. And fixed it here.

2025-01-06 16:06 UTC, The-Daniel requested changes

2025-01-08 11:33 UTC, sanmont3drepo approved these changes

2025-01-08 12:05 UTC, sanmont3drepo requested changes

2025-01-08 12:05 UTC, sanmont3drepo commented on frontend/src/v5/ui/components/viewer/cards/cardFilters/filterForm/filterFormValues/rangeInput/useRangeEffect.ts
> + *  Copyright (C) 2025 3D Repo Ltd
There's a white page being thrown by dates
steps to reproduce
- open the ticket filters modal.
- select a date property to filter
- change the criteria to "In Range"
- select the date in the left field (leave the right one empty)
- click on "back" button
- select another date property to filter (it could be the same)
- the page goes blank

2025-01-10 10:59 UTC, sanmont3drepo approved these changes

2025-01-13 16:07 UTC, merged