Issue 5287
3drepo/3drepo.io pull request #5328
Opened 2024-12-31 11:35 UTC by Bogdan-Crn

This fixes #5287 

#### Description
Created the new endpoints for the containers and federations.

Once hit it retrieves the revision's metadata and hashes the file.

On void revisions it returns a blank array back as a response for containers or it simply omits it from federations.

2025-01-08 12:44 UTC, carmenfan requested changes

2025-01-08 12:44 UTC, carmenfan commented on backend/tests/v5/unit/processors/teamspaces/projects/models/federations.test.js
> +		// it should get an empty array if user doesn't have rights to the container
redundant comments should be removed 😆 that's just the test description

2025-01-15 12:35 UTC, Bogdan-Crn commented
Moved most of the modelList logic to the filesManager.
Updated the federation check to see if the user has access to the container.
Updated what happens if the federation is empty.
Updated the tests to contain generateRandomString() where necessary.

2025-01-15 15:39 UTC, carmenfan requested changes
Looking good, just a few minor comments 😆

2025-01-15 15:39 UTC, carmenfan commented on backend/src/v5/processors/teamspaces/projects/models/commons/modelList.js
>  	const uploadedAt = new Date(rev.timestamp).getTime();
Leave this as a Date object for now and do the serialisation in the middleware

2025-01-15 15:39 UTC, carmenfan commented on backend/src/v5/processors/teamspaces/projects/models/commons/modelList.js
> +	const code = rev.tag;
Sorry I probably wasn't being clear last time 😅 

Can we keep this as tag on the return value?

2025-01-15 15:39 UTC, carmenfan commented on backend/src/v5/services/filesManager.js
> +	if (Object.keys(refEntry).includes('MD5Hash')) {
I think you can probably abbreviate this bit with ES6 style syntax?

Also can we call it `md5Hash` just for consistency in naming convention?

```suggestion
const {size, md5Hash: hash }= await getRefEntry(teamspace, `${container}.history.ref`, filename);

if(hash) {
  return {size, hash};
}
```

2025-01-15 15:39 UTC, carmenfan commented on backend/src/v5/services/filesManager.js
> +	const file = await FilesManager.getFile(teamspace, `${container}.history`, filename);
getting filesManager to append history is a bit too coupled (whilst we're only using it in history atm, we can in theory get md5 for anything).

I would rename container to collection and get the processor to pass in `${container}.history` instead

2025-01-17 09:37 UTC, Bogdan-Crn commented on backend/src/v5/processors/teamspaces/projects/models/commons/modelList.js
> +	const code = rev.tag;
Ok, so instead of code the key will be named tag, what about the value that it holds? Should that stay as the tag of the revision?

2025-01-17 09:48 UTC, carmenfan commented on backend/src/v5/processors/teamspaces/projects/models/commons/modelList.js
> +	const code = rev.tag;
yea same data just call it tag on the response is good 👍

2025-01-21 15:21 UTC, carmenfan approved these changes

2025-01-21 15:21 UTC, merged